//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: add.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
}

export function AddIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--add', props.className)}
      style={props.style}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      <path
        fill="#222"
        fillRule="evenodd"
        d="M31.85 8.005L32 8a2 2 0 0 1 1.995 1.85L34 10v20h20a2 2 0 0 1 1.995 1.85L56 32a2 2 0 0 1-1.85 1.995L54 34H34v20a2 2 0 0 1-1.85 1.995L32 56a2 2 0 0 1-1.995-1.85L30 54V34H10a2 2 0 0 1-1.995-1.85L8 32a2 2 0 0 1 1.85-1.995L10 30h20V10a2 2 0 0 1 1.85-1.995L32 8l-.15.005z"
      />
    </svg>
  );
}
