//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: arrow-up.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function ArrowUpIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--arrow-up', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M32.853 19.097L52.447 43.26a2 2 0 0 0 3.106-2.52l-21.083-26a2 2 0 0 0-3.054-.062l-22.916 26a2 2 0 1 0 3 2.644l21.353-24.225z"
      />
    </svg>
  );
}
