//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: arrow-subdirectory.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
}

export function ArrowSubdirectoryIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--arrow-subdirectory', props.className)}
      style={props.style}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      <path
        fill="#222"
        fill-rule="evenodd"
        d="M51.41 35.41l-12 12a2 2 0 0 1-2.82-2.82L45.17 36H20a8 8 0 0 1-8-8V18a2 2 0 1 1 4 0v10a4 4 0 0 0 4 4h25.17l-8.58-8.59a2 2 0 0 1 2.82-2.82l12 12a2 2 0 0 1 0 2.82z"
      />
    </svg>
  );
}
