//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: arrow-small-right.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
}

export function ArrowSmallRightIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--arrow-small-right', props.className)}
      style={props.style}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      <path
        fill="#222"
        fillRule="evenodd"
        d="M45.286 33.386L24.45 47.728c-.73.502-1.71.289-2.19-.477a1.716 1.716 0 0 1-.259-.91V17.658C22 16.743 22.708 16 23.581 16c.309 0 .61.095.868.272l20.837 14.341c.73.503.934 1.531.455 2.297"
      />
    </svg>
  );
}
