//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: attach.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
}

export function AttachIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--attach', props.className)}
      style={props.style}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      <path
        fill="#222"
        fillRule="evenodd"
        d="M53.77 27.82L45.64 36 36 45.55l-5.21 5.25c-5.293 5.146-13.737 5.087-18.957-.133-5.22-5.22-5.279-13.664-.133-18.957l15.56-15.56A2.008 2.008 0 0 1 30.09 19L14.53 34.54A9.521 9.521 0 1 0 28 48l5.31-5.3L51 25a6 6 0 0 0-4.3-10.25 6 6 0 0 0-4.24 1.75l-3.13 3.13v.06L24.78 34.18 23 36a2.5 2.5 0 0 0 0 3.53 2.56 2.56 0 0 0 3.54 0l16.27-16.31a2.001 2.001 0 0 1 2.83 2.83L29.38 42.31a6.5 6.5 0 1 1-9.19-9.19l19.44-19.44a10 10 0 0 1 14.14 14.14z"
      />
    </svg>
  );
}
