//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: camera.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
}

export function CameraIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--camera', props.className)}
      style={props.style}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      <path
        fill="#222"
        fillRule="evenodd"
        d="M37.53 6C39.94 6 42 7.79 43 10.68L45.44 18H50a8 8 0 0 1 8 8v24a8 8 0 0 1-8 8H14a8 8 0 0 1-8-8V26a8 8 0 0 1 8-8h4.56L21 10.68C22 7.79 24.06 6 26.47 6zM50 22H14a4 4 0 0 0-4 4v24a4 4 0 0 0 4 4h36a4 4 0 0 0 4-4V26a4 4 0 0 0-4-4zm-18 4c6.627 0 12 5.373 12 12s-5.373 12-12 12-12-5.373-12-12 5.373-12 12-12zm0 4a8 8 0 1 0 0 16 8 8 0 0 0 0-16zm5.53-20H26.47c-.47 0-1.25.67-1.68 1.94L22.77 18h18.44l-2-6.06c-.43-1.27-1.17-1.94-1.68-1.94z"
      />
    </svg>
  );
}
