//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: cloud.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function CloudIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--cloud', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M50 50H16a12 12 0 0 1-1.88-23.85 14 14 0 0 1 26.58-4.06c.43-.06.865-.09 1.3-.09a10 10 0 0 1 9.83 8.17A10 10 0 0 1 50 50zM16 30a8 8 0 1 0 0 16h34a6 6 0 1 0 0-12h-2v-2a6 6 0 0 0-7.91-5.68l-1.93.68-.61-2A10 10 0 0 0 18 28v2h-2z"
      />
    </svg>
  );
}
