//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: delivery.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
}

export function DeliveryIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--delivery', props.className)}
      style={props.style}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      <path
        fill="#222"
        fillRule="evenodd"
        d="M59.54 31.72l-10-12A2 2 0 0 0 48 19h-4v-2a6 6 0 0 0-6-6H10a6 6 0 0 0-6 6v24a6 6 0 0 0 6 6h.08a7 7 0 0 0 13.84 0h12.16a7 7 0 0 0 13.84 0H58a2 2 0 0 0 2-2V33a2 2 0 0 0-.46-1.28zM19.82 47a3 3 0 0 1-5.64 0 2.771 2.771 0 0 1-.18-1 3 3 0 0 1 6 0c.002.342-.059.68-.18 1zm16.86-4H23.32a7 7 0 0 0-12.64 0H10a2 2 0 0 1-2-2V17a2 2 0 0 1 2-2h28a2 2 0 0 1 2 2v22.68A7 7 0 0 0 36.68 43zm9.14 4A3 3 0 0 1 40 46a3.19 3.19 0 0 1 0-.54 3 3 0 0 1 2-2.27 2.77 2.77 0 0 1 1.63-.12A3 3 0 0 1 45.82 45a2.87 2.87 0 0 1 0 2zM56 43h-6.68A7 7 0 0 0 44 39.08V23h3.06L56 33.72V43z"
      />
    </svg>
  );
}
