//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: document-pdf.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
}

export function DocumentPdfIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--document-pdf', props.className)}
      style={props.style}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      <path
        fill="#222"
        fill-rule="evenodd"
        d="M50 4a4 4 0 0 1 4 4v44a8 8 0 0 1-8 8H14a4 4 0 0 1-4-4V12a8 8 0 0 1 8-8zm0 4H18a4 4 0 0 0-4 4v44h32a4 4 0 0 0 4-4V8zM25.094 40.6c1.104 0 1.992.528 2.448 1.356.228.42.336.888.336 1.404 0 .768-.372 1.488-.924 1.98s-1.236.768-1.92.768h-1.44v1.656c0 .66-.42 1.308-.84 1.308s-.828-.756-.828-.96V41.38c0-.384.612-.78 1.2-.78zm17.208 0c.3 0 .444.144.444.42 0 .432-.192.864-.432 1.092-.132.108-.252.168-.372.168h-3.048v1.752h2.652c.276 0 .42.132.42.396 0 .588-.372 1.164-.756 1.164h-2.316v2.172c0 .66-.42 1.308-.84 1.308s-.828-.732-.828-.96V41.38c0-.384.612-.78 1.2-.78h3.876zm-10.368 0c1.584 0 2.892.804 3.576 2.04.336.612.504 1.296.504 2.028 0 1.764-.756 3.108-2.016 3.804-.636.348-1.356.528-2.184.528h-2.088c-.42 0-.828-.732-.828-.96v-6.66c0-.384.612-.78 1.2-.78zm.084 1.632h-1.452v5.136h1.344c1.5 0 2.388-.984 2.388-2.652 0-1.488-.924-2.484-2.28-2.484zm-6.972-.072h-1.452v2.388h1.452c.684 0 1.212-.516 1.212-1.188 0-.708-.504-1.2-1.212-1.2zM41 26c1.657 0 3 .895 3 2s-1.343 2-3 2H23c-1.657 0-3-.895-3-2s1.343-2 3-2zm0-8c1.657 0 3 .895 3 2s-1.343 2-3 2H23c-1.657 0-3-.895-3-2s1.343-2 3-2z"
      />
    </svg>
  );
}
