//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: document-ppt.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function DocumentPptIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--document-ppt', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M50 4H18a8 8 0 0 0-8 8v44a4 4 0 0 0 4 4h32a8 8 0 0 0 8-8V8a4 4 0 0 0-4-4zm0 48a4 4 0 0 1-4 4H14V12a4 4 0 0 1 4-4h32v44zM25.58 40.6c1.104 0 1.992.528 2.448 1.356.228.42.336.888.336 1.404 0 .768-.372 1.488-.924 1.98s-1.236.768-1.92.768h-1.44v1.656c0 .66-.42 1.308-.84 1.308s-.828-.756-.828-.96V41.38c0-.384.612-.78 1.2-.78zm6.972 0c1.104 0 1.992.528 2.448 1.356.228.42.336.888.336 1.404 0 .768-.372 1.488-.924 1.98s-1.236.768-1.92.768h-1.44v1.656c0 .66-.42 1.308-.84 1.308s-.828-.756-.828-.96V41.38c0-.384.612-.78 1.2-.78zm9.24 0c.312 0 .468.144.468.432 0 .66-.42 1.308-.84 1.308h-1.596v5.424c0 .66-.42 1.308-.84 1.308s-.828-.732-.828-.96V42.34h-1.644c-.42 0-.828-.732-.828-.96 0-.384.612-.78 1.2-.78h4.908zm-16.26 1.56H24.08v2.388h1.452c.684 0 1.212-.516 1.212-1.188 0-.708-.504-1.2-1.212-1.2zm6.972 0h-1.452v2.388h1.452c.684 0 1.212-.516 1.212-1.188 0-.708-.504-1.2-1.212-1.2zM42 26a2 2 0 1 1 0 4H30a2 2 0 1 1 0-4zm-20 0a2 2 0 1 1 0 4 2 2 0 0 1 0-4zm19-8c1.657 0 3 .895 3 2s-1.343 2-3 2H23c-1.657 0-3-.895-3-2s1.343-2 3-2z"
      />
    </svg>
  );
}
