//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: entertainment.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function EntertainmentIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--entertainment', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M57 21v29.69a6.6 6.6 0 0 1-.26 1.84A6.72 6.72 0 1 1 44.11 48 6.68 6.68 0 0 1 50 44c.09-.01.18-.01.27 0a6.75 6.75 0 0 1 2.73.54V33.1H34v17.59a6.6 6.6 0 0 1-.22 1.84A6.72 6.72 0 1 1 26.62 44h-.04c.093-.01.187-.013.28-.01l.125.009L27 44l.103-.009c.07-.003.138 0 .207.009.23-.015.46-.015.69 0a6.76 6.76 0 0 1 2 .54V27.05l.001-.107-.001.107v-.95h.08l.027-.164A6.082 6.082 0 0 1 36.09 21H57zm-6.73 27H50a2.73 2.73 0 1 0 2.32 4.53h-.04a2.68 2.68 0 0 0 .72-1.84A2.73 2.73 0 0 0 50.27 48zm-22.8-.01h-.04l-.16.01h-.44a2.73 2.73 0 1 0 2.49 4.53 2.68 2.68 0 0 0 .68-1.84A2.73 2.73 0 0 0 27.75 48h.005-.445l.016-.001-.016.001a2.59 2.59 0 0 1 .16-.01zM47 6a8 8 0 0 1 8 8v4h-4v-4a4 4 0 0 0-4-4H15a4 4 0 0 0-4 4v26a4 4 0 0 0 4 4h5.29A9.58 9.58 0 0 0 18 48h-3a8 8 0 0 1-8-8V14a8 8 0 0 1 8-8zM21 34v6h-6v-6h6zm0-10v6h-6v-6h6zm32 1H36.09a2 2 0 0 0-1.85 1.1c-.16.29-.244.618-.24.95v2.05h19V25zM21 14v6h-6v-6h6zm26 0v4h-6v-4h6z"
      />
    </svg>
  );
}
