//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: filter.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
}

export function FilterIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--filter', props.className)}
      style={props.style}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      <path
        fill="#220"
        d="M24 14c3.728 0 6.86 2.55 7.748 6H54a2 2 0 1 1 0 4H31.748a8.003 8.003 0 0 1-15.496 0H10a2 2 0 1 1 0-4h6.252c.888-3.45 4.02-6 7.748-6zm0 4a4 4 0 1 0 0 8 4 4 0 0 0 0-8zm16 16a8.003 8.003 0 0 0-7.748 6H10a2 2 0 1 0 0 4h22.252a8.003 8.003 0 0 0 15.496 0H54a2 2 0 1 0 0-4h-6.252c-.888-3.45-4.02-6-7.748-6zm0 4a4 4 0 1 1 0 8 4 4 0 0 1 0-8z"
      />
    </svg>
  );
}
