//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: food.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
}

export function FoodIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--food', props.className)}
      style={props.style}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      <path
        fillRule="evenodd"
        d="M49.73 4.47a2 2 0 0 1 2 2v46.4A6.67 6.67 0 0 1 45 59.53a6.67 6.67 0 0 1-6.66-6.66v-.1L39.22 37a5.2 5.2 0 0 1-2-1.39 7.8 7.8 0 0 1-1.62-5.4V14.45a8.32 8.32 0 0 1 2.5-6.16c4-3.9 11.32-3.83 11.63-3.82zm-20.282.238A2 2 0 0 1 30.5 6.41l.56 18.47c.16 2.54-.12 5.92-3.95 7.12l1.07 20.49a6.64 6.64 0 0 1-6.45 6.64h-.4a6.65 6.65 0 0 1-6.46-6.64v-.11L16 32c-3.83-1.16-4.12-4.55-3.95-7.15l.56-18.4a2 2 0 1 1 4 .12L16 25c-.19 3 .38 3.17 2.22 3.34l1.92.18-1.27 24a2.66 2.66 0 0 0 5.31 0l-1.26-24 1.91-.18c1.85-.17 2.42-.37 2.23-3.27L26.5 6.53a2 2 0 0 1 2.948-1.822zM47.66 8.58c-2.15.25-5.14.93-6.81 2.57a4.41 4.41 0 0 0-1.32 3.3v15.86c.005.06.005.12 0 .18a3.94 3.94 0 0 0 .65 2.51 1.48 1.48 0 0 0 1.17.44 2 2 0 0 1 1.95 2.1l-.96 17.38a2.66 2.66 0 1 0 5.32-.05V8.58zM21.53 4.47a2 2 0 0 1 2 2v16.72a2 2 0 1 1-4 0V6.47a2 2 0 0 1 2-2z"
      />
    </svg>
  );
}
