//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: games.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
}

export function GamesIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--games', props.className)}
      style={props.style}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      <path
        fill="#222"
        fillRule="evenodd"
        d="M46 4a2 2 0 0 1 2 2v4a8 8 0 0 1-8 8 4 4 0 0 0-4 4v2h7.6c8.662-.133 15.892 6.581 16.4 15.23a16 16 0 0 1-25.66 13.52 4 4 0 0 0-2.41-.75h-.22a3.46 3.46 0 0 0-2.05.75A15.82 15.82 0 0 1 20 56 16 16 0 0 1 4 39.23c.508-8.649 7.738-15.363 16.4-15.23H32v-2a8 8 0 0 1 8-8 4 4 0 0 0 4-4V6a2 2 0 0 1 2-2zm-2.095 23.998L43.6 28H20.4C13.876 27.875 8.41 32.908 8 39.42a12 12 0 0 0 19.24 10.14A7.38 7.38 0 0 1 31.71 48h.22a8 8 0 0 1 4.83 1.56 12 12 0 0 0 15.92-1.28A11.91 11.91 0 0 0 56 39.42c-.41-6.512-5.876-11.545-12.4-11.42zM20 34a2 2 0 0 1 2 2v2h2a2 2 0 1 1 0 4h-2v2a2 2 0 1 1-4 0v-2h-2a2 2 0 1 1 0-4h2v-2a2 2 0 0 1 2-2zm22 6a2 2 0 1 1 0 4 2 2 0 0 1 0-4zm6-4a2 2 0 1 1 0 4 2 2 0 0 1 0-4z"
      />
    </svg>
  );
}
