//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: heart-filled.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
}

export function HeartFilledIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--heart-filled', props.className)}
      style={props.style}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      <path
        fillRule="evenodd"
        d="M53.82 12.35a14.08 14.08 0 0 0-20.35 0L32 13.87l-1.47-1.52a14.08 14.08 0 0 0-20.35 0c-5.562 5.833-5.562 15.007 0 20.84l19 19.59a4 4 0 0 0 5.74 0l19-19.59c5.534-5.86 5.49-15.033-.1-20.84z"
      />
    </svg>
  );
}
