//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: infinite.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
}

export function InfiniteIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--infinite', props.className)}
      style={props.style}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      <path
        fillRule="evenodd"
        d="M46.211 41.522c-1.058 0-3.494-.586-7.923-4.513a52.984 52.984 0 0 1-3.728-3.676 52.953 52.953 0 0 1 3.694-3.646c4.45-3.952 6.895-4.542 7.957-4.542 4.687 0 8.5 3.673 8.5 8.188 0 4.515-3.813 8.189-8.5 8.189m-20.5-4.513c-4.428 3.927-6.864 4.513-7.922 4.513-4.687 0-8.5-3.674-8.5-8.189 0-4.515 3.813-8.188 8.5-8.188 1.058 0 3.494.586 7.923 4.512a52.996 52.996 0 0 1 3.728 3.676 52.977 52.977 0 0 1-3.728 3.676m20.5-15.676c-2.913 0-6.492 1.868-10.64 5.552A56.002 56.002 0 0 0 32 30.374a56.002 56.002 0 0 0-3.573-3.489c-4.147-3.684-7.726-5.552-10.638-5.552-6.868 0-12.456 5.384-12.456 12 0 6.617 5.588 12 12.456 12 2.912 0 6.491-1.868 10.638-5.552A56.003 56.003 0 0 0 32 36.293a56.003 56.003 0 0 0 3.573 3.488c4.147 3.684 7.726 5.552 10.638 5.552 6.868 0 12.456-5.383 12.456-12 0-6.616-5.588-12-12.456-12"
      />
    </svg>
  );
}
