//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: insurance.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
}

export function InsuranceIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--insurance', props.className)}
      style={props.style}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      <path
        fill="#222"
        fillRule="evenodd"
        d="M40 4a8 8 0 0 1 8 8v40a8 8 0 0 1-8 8H24a8 8 0 0 1-8-8V12a8 8 0 0 1 8-8zm4 44H20v4a4 4 0 0 0 4 4h16a4 4 0 0 0 4-4v-4zm-12 2a2 2 0 1 1 0 4 2 2 0 0 1 0-4zm8-42H24a4 4 0 0 0-4 4v13.32l4.16-4.13a2 2 0 0 1 3.06.28l3.06 4.45 3.31-3.3a2 2 0 0 1 2.82 2.82l-5 5a2 2 0 0 1-1.59.58 2 2 0 0 1-1.47-.86l-3.06-4.44L20 31v13h24V12a4 4 0 0 0-4-4z"
      />
    </svg>
  );
}
