//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: login.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
}

export function LoginIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--login', props.className)}
      style={props.style}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      <path
        fill="#222"
        fill-rule="evenodd"
        d="M31.998 8a2 2 0 1 0 0 4h18a4 4 0 0 1 4 4v32a4 4 0 0 1-4 4h-18a2 2 0 1 0 0 4h18a8 8 0 0 0 8-8V16a8 8 0 0 0-8-8zm-3.303 10.685a2 2 0 0 0-.105 2.715l8.58 8.6H10a2 2 0 1 0 0 4h27.17l-8.58 8.59a2 2 0 1 0 2.82 2.82l12-12a1.79 1.79 0 0 0 .25-.3.55.55 0 0 0 .08-.15c.043-.063.08-.13.11-.2l.06-.2a.84.84 0 0 0 .05-.17 2 2 0 0 0 0-.78.84.84 0 0 0-.05-.17l-.06-.2a1.28 1.28 0 0 0-.11-.2.55.55 0 0 0-.08-.15 1.79 1.79 0 0 0-.25-.31l-12-12a2 2 0 0 0-2.715.105z"
      />
    </svg>
  );
}
