//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: logout.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
}

export function LogoutIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--logout', props.className)}
      style={props.style}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      <path
        fill="#222"
        fill-rule="evenodd"
        d="M34 8a2 2 0 1 1 0 4H16a4 4 0 0 0-4 4v32a4 4 0 0 0 4 4h18a2 2 0 1 1 0 4H16a8 8 0 0 1-8-8V16a8 8 0 0 1 8-8zm8.695 10.685a2 2 0 0 1 2.715-.105l12 12c.095.094.178.198.25.31a.55.55 0 0 1 .08.15c.043.063.08.13.11.2l.06.2a.84.84 0 0 1 .05.17 2 2 0 0 1 0 .78.84.84 0 0 1-.05.17l-.06.2a1.28 1.28 0 0 1-.11.2.55.55 0 0 1-.08.15 1.79 1.79 0 0 1-.25.3l-12 12a2 2 0 1 1-2.82-2.82L51.17 34H24a2 2 0 1 1 0-4h27.17l-8.58-8.6a2 2 0 0 1 .105-2.715z"
      />
    </svg>
  );
}
