//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: minus.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
}

export function MinusIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--minus', props.className)}
      style={props.style}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      <path
        fill="#222"
        fill-rule="evenodd"
        d="M17.333 35h29.334c.736 0 1.333-.895 1.333-2s-.597-2-1.333-2H17.333c-.736 0-1.333.895-1.333 2s.597 2 1.333 2z"
      />
    </svg>
  );
}
