//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: more.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
}

export function MoreIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--more', props.className)}
      style={props.style}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      <path
        fill="#222"
        fillRule="evenodd"
        d="M43 32c0 2.75 2.25 5 5 5s5-2.25 5-5-2.25-5-5-5-5 2.25-5 5zm-6 0c0-2.75-2.25-5-5-5s-5 2.25-5 5 2.25 5 5 5 5-2.25 5-5zm-16 0c0-2.75-2.25-5-5-5s-5 2.25-5 5 2.25 5 5 5 5-2.25 5-5z"
      />
    </svg>
  );
}
