//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: phone.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
}

export function PhoneIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--phone', props.className)}
      style={props.style}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      <path
        fill="#222"
        fillRule="evenodd"
        d="M56.426 41.187l-6.605-6.612c-2.1-2.1-5.53-2.1-7.628 0l-2.76 2.76a1.407 1.407 0 0 1-1.971 0L26.669 26.542a1.406 1.406 0 0 1 0-1.97l2.76-2.76a5.406 5.406 0 0 0 0-7.626l-6.613-6.613a5.407 5.407 0 0 0-7.627 0l-1.25 1.265c-8.796 8.795-5.729 19.983 7.608 33.309l.36.344.698.69c13 12.71 23.952 15.507 32.588 6.873l1.235-1.243a5.406 5.406 0 0 0-.002-7.625zm-2.833 4.803l-1.233 1.24c-6.678 6.678-15.32 4.47-26.95-6.9l-.718-.709-.352-.336c-11.826-11.817-14.33-20.632-7.767-27.42l1.453-1.471c.528-.528 1.425-.528 1.962.009l6.613 6.612a1.406 1.406 0 0 1 0 1.97l-2.76 2.76a5.406 5.406 0 0 0 0 7.627l10.792 10.79a5.407 5.407 0 0 0 7.628 0l2.76-2.759a1.407 1.407 0 0 1 1.97 0l6.606 6.612c.501.502.535 1.316.1 1.859l-.104.116z"
      />
    </svg>
  );
}
