//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: product-skjermforsikring.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
}

export function ProductSkjermforsikringIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--product-skjermforsikring', props.className)}
      style={props.style}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      <path
        fillRule="evenodd"
        d="M28.82 7a2 2 0 1 1 0 4h-7.06A3.78 3.78 0 0 0 18 14.78v29.73h22.93V34a2 2 0 0 1 2-2 2 2 0 0 1 2.02 2v18.29a7.78 7.78 0 0 1-7.77 7.77h-15.4A7.79 7.79 0 0 1 14 52.29V14.78A7.79 7.79 0 0 1 21.76 7zM41 48.51H18v3.78A3.77 3.77 0 0 0 21.76 56h15.4v.06A3.77 3.77 0 0 0 41 52.29v-3.78zm-11.54 1.84a1.93 1.93 0 1 1 0 3.86 1.93 1.93 0 0 1 0-3.86zm15.895-21.975A2.002 2.002 0 0 1 47.83 27l4.68 1.36v-.02a2 2 0 0 1-.55 3.93 2.09 2.09 0 0 1-.55-.08l-4.68-1.34a2.002 2.002 0 0 1-1.375-2.475zm-10.482-24a2 2 0 0 1 2.037-.325l3.82 1.28a7.77 7.77 0 0 1 4.87 9.86l-3.82 11.24a2 2 0 0 1-1.89 1.36 2.05 2.05 0 0 1-.64-.11A2 2 0 0 1 38 25.15l3.76-11.25a3.78 3.78 0 0 0-2.36-4.79l-3.78-1.28a2 2 0 0 1-.747-3.455zM51.08 18.66A2 2 0 0 1 53 22.17l-4.85 2.67a2.1 2.1 0 0 1-1 .24l.024-.001-.125-.003a2 2 0 0 1-1.756-1.327l-.048-.153a2 2 0 0 1 .965-2.266z"
      />
    </svg>
  );
}
