//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: product-svitsj.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function ProductSvitsjIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--product-svitsj', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M46 27.64a2 2 0 0 1 2 2V52a8 8 0 0 1-8 8H24a8 8 0 0 1-8-8V36.81l-1.78 1.78a2 2 0 1 1-2.83-2.82l4.68-4.68a2.81 2.81 0 0 1 .79-.55 2 2 0 0 1 2.28 0c.293.137.56.323.79.55l4.68 4.68a2 2 0 0 1-1.41 3.41 2 2 0 0 1-1.42-.59L20 36.81V44h24V29.64a2 2 0 0 1 2-2zM44 48H20v4a4 4 0 0 0 4 4h16a4 4 0 0 0 4-4v-4zm-12 2a2 2 0 1 1 0 4 2 2 0 0 1 0-4zm8-46a8 8 0 0 1 8 8v6.07l1.78-1.78a2 2 0 1 1 2.83 2.83l-4.68 4.68a2.73 2.73 0 0 1-3.86 0l-4.68-4.68a2.001 2.001 0 0 1 2.83-2.83L44 18.07V12a4 4 0 0 0-4-4H24a4 4 0 0 0-4 4v12.77a2 2 0 1 1-4 0V12a8 8 0 0 1 8-8z"
      />
    </svg>
  );
}
