//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: product-bedrift-click.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
}

export function ProductBedriftClickIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--product-bedrift-click', props.className)}
      style={props.style}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      <path
        fill="#222"
        fill-rule="evenodd"
        d="M31.44 7.86a2 2 0 0 1 0 4h-8.87A3.58 3.58 0 0 0 19 15.44V45h22V21.49a2 2 0 1 1 4 0V52.6a7.58 7.58 0 0 1-7.54 7.57H22.57A7.57 7.57 0 0 1 15 52.6V15.44a7.58 7.58 0 0 1 7.59-7.58zM41 49H19v3.6a3.57 3.57 0 0 0 3.59 3.57h14.87A3.57 3.57 0 0 0 41 52.6V49zm-10.98 1.74a1.86 1.86 0 1 1 0 3.72 1.86 1.86 0 0 1 0-3.72zm13.62-47.1A1.28 1.28 0 0 1 45.05 5v2.93h2.663a1.27 1.27 0 0 1 1.207 1.31c0 1.24-.82 2.62-1.92 2.62h-2v1.7c0 1.31-.86 2.77-2 2.77-1.14 0-2-1.49-2-2.23v-2.24h-2.24c-1.05 0-1.9-1.51-1.9-2.1a2 2 0 0 1 1.43-1.64 3 3 0 0 1 1.08-.19h1.66V5.64c0-1.11 1.43-2 2.61-2z"
      />
    </svg>
  );
}
