//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: product-mobilpant.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
}

export function ProductMobilpantIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--product-mobilpant', props.className)}
      style={props.style}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      <path
        fill="#222"
        fillRule="evenodd"
        d="M36.92 4a8 8 0 0 1 8 8v13.12l2.74-2.74a2 2 0 1 1 2.83 2.83l-5.54 5.54a2.89 2.89 0 0 1-4.05 0l-5.54-5.54a2.001 2.001 0 0 1 2.83-2.83l2.73 2.74V12a4 4 0 0 0-4-4h-16a4 4 0 0 0-4 4v32h24v-7.36a2 2 0 1 1 4 0V52a8 8 0 0 1-8 8h-16a8 8 0 0 1-8-8V12a8 8 0 0 1 8-8zm4 44h-24v4a4 4 0 0 0 4 4h16a4 4 0 0 0 4-4v-4zm-12 2a2 2 0 1 1 0 4 2 2 0 0 1 0-4z"
      />
    </svg>
  );
}
