//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: product-roam-like-home.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
}

export function ProductRoamLikeHomeIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--product-roam-like-home', props.className)}
      style={props.style}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      <path
        fillRule="evenodd"
        d="M47 19c7.18 0 13 5.82 13 13s-5.82 13-13 13H17C9.82 45 4 39.18 4 32s5.82-13 13-13h30zm0 4H17a9 9 0 0 0 0 18h30a9 9 0 0 0 0-18zm-2 2a7 7 0 1 1 0 14 7 7 0 0 1 0-14zm0 4a3 3 0 1 0 0 6 3 3 0 0 0 0-6z"
      />
    </svg>
  );
}
