//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: question.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
}

export function QuestionIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--question', props.className)}
      style={props.style}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      <path
        fillRule="evenodd"
        d="M31.912 40.408l6.592-7.04.64-.697c4.558-5.023 6.08-8.118 6.08-11.975 0-2.112-.512-4.096-1.6-5.824-2.112-3.456-6.144-5.632-11.2-5.632-5.32 0-10.516 2.753-13.616 7.183l-.208.305c-.448.64-.64 1.216-.64 1.664 0 1.088 1.856 4.544 3.904 4.544.384 0 .768-.128 1.152-.384.32-.256.832-.768 1.536-1.536 2.752-3.072 4.608-4.224 7.104-4.224 2.88 0 4.992 1.92 4.992 4.48 0 2.24-1.216 4.352-4.096 7.488l-6.208 6.592c-.448.576-.704 1.088-.704 1.6s.32 1.344.96 2.432c.96 1.472 1.984 2.24 3.072 2.24.704 0 1.408-.384 2.24-1.216zm-1.6 14.976c-2.496 0-4.864-4.16-4.864-5.76 0-2.24 3.648-4.608 7.168-4.608 1.856 0 2.816.832 2.816 2.56 0 2.624-1.216 5.312-2.752 6.72-.768.704-1.536 1.088-2.368 1.088z"
      />
    </svg>
  );
}
