//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: record.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function RecordIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--record', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="nonzero"
        d="M35.53 28.52a5 5 0 1 1-7 0 5 5 0 0 1 7 0zM58 32c0 14.36-11.64 26-26 26S6 46.36 6 32 17.64 6 32 6a26 26 0 0 1 26 26zm-4 0c0-12.15-9.85-22-22-22s-22 9.85-22 22 9.85 22 22 22 22-9.85 22-22z"
      />
    </svg>
  );
}
