//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: recycle.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
}

export function RecycleIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--recycle', props.className)}
      style={props.style}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      <path
        fillRule="evenodd"
        d="M48.434 32.187l5.09 8.82a6 6 0 0 1-5.2 9h-10.08l.83.83a2 2 0 1 1-2.82 2.83l-3.83-3.82a2.61 2.61 0 0 1 0-3.68l3.83-3.83a2 2 0 0 1 2.82 2.83l-.84.84h10.09a2 2 0 0 0 1.73-3l-5.09-8.82a2.003 2.003 0 1 1 3.47-2zm-27.55-4.61a2.61 2.61 0 0 1 1.22 1.58l1.39 5.23a2 2 0 0 1-1.93 2.52 2 2 0 0 1-1.93-1.49l-.3-1.13-5 8.72a2 2 0 0 0 1.73 3h10.1a2 2 0 1 1 0 4h-10.16a6 6 0 0 1-5.2-9l5-8.73-1.14.31a2 2 0 1 1-1-3.86l5.22-1.4a2.56 2.56 0 0 1 2 .25zM32.164 10a6 6 0 0 1 5.2 3.007l5 8.73.3-1.14a2 2 0 0 1 3.87 1l.04.04-1.41 5.22a2.6 2.6 0 0 1-3.19 1.84l-5.22-1.4a2 2 0 0 1 1-3.86l1.14.31-5-8.74a2 2 0 0 0-3.46 0l-5.1 8.82a2 2 0 1 1-3.46-2l5.09-8.82a6 6 0 0 1 5.2-3.007z"
      />
    </svg>
  );
}
