//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: robot.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
}

export function RobotIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--robot', props.className)}
      style={props.style}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      <path
        fill="#222"
        fill-rule="evenodd"
        d="M42 3.986a4 4 0 0 1 2 7.464V16h2a8 8 0 0 1 8 8v6a4 4 0 1 1 0 8v12a8 8 0 0 1-8 8H18a8 8 0 0 1-8-8V38a4 4 0 1 1 0-8v-6a8 8 0 0 1 8-8h2v-4.55a4 4 0 1 1 4 0V16h16v-4.55a4 4 0 0 1 2-7.464zM46 20H18a4 4 0 0 0-4 4v26a4 4 0 0 0 4 4h28a4 4 0 0 0 4-4V24a4 4 0 0 0-4-4zm-5.13 22.35a2 2 0 1 1 2.26 3.3C40.9 47.17 36.95 48 32 48c-4.95 0-8.9-.83-11.13-2.35a2 2 0 1 1 2.26-3.3C23.7 42.73 26 44 32 44c6 0 8.3-1.27 8.87-1.65zM24 26a6 6 0 1 1 0 12 6 6 0 0 1 0-12zm16 0a6 6 0 1 1 0 12 6 6 0 0 1 0-12zm-16 4a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm16 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4z"
      />
    </svg>
  );
}
