//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: services.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
}

export function ServicesIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--services', props.className)}
      style={props.style}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      <path
        fill="#222"
        fill-rule="evenodd"
        d="M13 46a5 5 0 1 1 0 10 5 5 0 0 1 0-10zm20 0a5 5 0 1 1 0 10 5 5 0 0 1 0-10zm18 0a5 5 0 1 1 0 10 5 5 0 0 1 0-10zM13 27a5 5 0 1 1 0 10 5 5 0 0 1 0-10zm19 0a5 5 0 1 1 0 10 5 5 0 0 1 0-10zm19 0a5 5 0 1 1 0 10 5 5 0 0 1 0-10zM13 8a5 5 0 1 1 0 10 5 5 0 0 1 0-10zm19 0a5 5 0 1 1 0 10 5 5 0 0 1 0-10zm19 0a5 5 0 1 1 0 10 5 5 0 0 1 0-10z"
      />
    </svg>
  );
}
