//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: shopping.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
}

export function ShoppingIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--shopping', props.className)}
      style={props.style}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      <path
        fill="#222"
        fillRule="evenodd"
        d="M55.33 49.19l-3.15-29.61a4 4 0 0 0-4-3.58H44c0-6.627-5.373-12-12-12S20 9.373 20 16h-4.2a4 4 0 0 0-4 3.58L8.67 49.2a8 8 0 0 0 8 8.8h30.7a8 8 0 0 0 8-8.81h-.04zM32 8a8 8 0 0 1 8 8H24a8 8 0 0 1 8-8zm18.34 44.68a4 4 0 0 1-3 1.32H16.63a4 4 0 0 1-4-4.38L15.8 20H20v8a2 2 0 1 0 4 0v-8h16v8a2 2 0 1 0 4 0v-8h4.2l3.15 29.6a4 4 0 0 1-1.01 3.08z"
      />
    </svg>
  );
}
