//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: signal.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
}

export function SignalIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--signal', props.className)}
      style={props.style}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      <path
        fillRule="evenodd"
        d="M32 32a2 2 0 0 1 2 2v22a2 2 0 1 1-4 0V34a2 2 0 0 1 2-2zM43.9 9.27a2.001 2.001 0 0 1 2.83 0 18 18 0 0 1 0 25.46 2 2 0 1 1-2.83-2.83 14 14 0 0 0 0-19.8 2.001 2.001 0 0 1 0-2.83zm-26.63 0a2.001 2.001 0 1 1 2.83 2.83A13.92 13.92 0 0 0 16 22a13.92 13.92 0 0 0 4.1 9.9 2.001 2.001 0 0 1-2.83 2.83 18 18 0 0 1 0-25.46zm7.075 5.073a2 2 0 0 1 1.415 3.417 6 6 0 0 0 0 8.48 2 2 0 1 1-2.83 2.83c-3.904-3.905-3.904-10.235 0-14.14a2 2 0 0 1 1.415-.587zm14.792.07a2.001 2.001 0 0 1 1.933.517c3.904 3.905 3.904 10.235 0 14.14a2.001 2.001 0 0 1-2.83-2.83 6 6 0 0 0 0-8.48 2.001 2.001 0 0 1 .897-3.348zM32 19a3 3 0 1 1 0 6 3 3 0 0 1 0-6z"
      />
    </svg>
  );
}
