//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: stop.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
}

export function StopIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--stop', props.className)}
      style={props.style}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      <path
        fill="#222"
        fill-rule="evenodd"
        d="M32 4a28 28 0 0 1 28 28c0 15.464-12.536 28-28 28S4 47.464 4 32 16.536 4 32 4zm0 4C18.745 8 8 18.745 8 32s10.745 24 24 24 24-10.745 24-24S45.255 8 32 8zm12 22a2 2 0 1 1 0 4H20a2 2 0 1 1 0-4h24z"
      />
    </svg>
  );
}
