//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: support.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
}

export function SupportIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--support', props.className)}
      style={props.style}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      <path
        fill="#222"
        fillRule="evenodd"
        d="M45.61 30.36A15.78 15.78 0 0 0 48 22a16 16 0 1 0-5.48 12c7.528.28 13.485 6.467 13.48 14v2a4 4 0 0 1-4 4H12a4 4 0 0 1-4-4v-2a14 14 0 0 1 4.76-10.52 26.11 26.11 0 0 0 15.65 8.26 4 4 0 1 0 .29-4 22.11 22.11 0 0 1-14.57-8.9A21.83 21.83 0 0 1 10 20a2 2 0 1 0-4 0 25.74 25.74 0 0 0 4.32 14.31A18.06 18.06 0 0 0 4 48v2a8 8 0 0 0 8 8h40a8 8 0 0 0 8-8v-2a18 18 0 0 0-14.39-17.64zM32 34c-6.627 0-12-5.373-12-12s5.373-12 12-12 12 5.373 12 12a12 12 0 0 1-12 12z"
      />
    </svg>
  );
}
