//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: table-view.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
}

export function TableViewIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--table-view', props.className)}
      style={props.style}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      <path
        fill="#222"
        fill-rule="evenodd"
        d="M10.958 56C9.877 56 9 55.105 9 54c0-.078.004-.156.013-.232A3.377 3.377 0 0 1 9 53.474V10.526C9 9.131 9.895 8 11 8c.152 0 .3.021.443.062.15-.04.31-.062.474-.062h42.166C55.142 8 56 8.895 56 10c0 .08-.004.158-.013.235.009.095.013.192.013.291l-.001 3.449L56 14v.025l-.001 19.95L56 34v19.474c0 .1-.005.198-.014.295.01.075.014.153.014.231 0 1.105-.877 2-1.958 2zM52 52V36H34v16h17.999zM30 36H13v16h17V36zm21.999-4V16H34v16h17.999zM30 16H13v16h17V16z"
      />
    </svg>
  );
}
