//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: undo.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
}

export function UndoIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--undo', props.className)}
      style={props.style}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      <path
        fill="#222"
        fillRule="evenodd"
        d="M56.461 34.915c.002 12.437-9.3 22.908-21.65 24.373-12.35 1.464-23.842-6.54-26.75-18.633a2 2 0 1 1 3.89-.93c2.51 10.416 12.601 17.153 23.182 15.478C45.714 53.527 53.231 44 52.398 33.319c-.832-10.68-9.734-18.927-20.447-18.944a20 20 0 0 0-2.45.15l3 3a2 2 0 0 1-2.82 2.83l-5.91-5.91a2.9 2.9 0 0 1-.86-2.07 2.94 2.94 0 0 1 .86-2.07l5.91-5.9a2 2 0 0 1 2.78 2.83l-3.29 3.29a25 25 0 0 1 2.74-.15c13.55.011 24.534 10.99 24.55 24.54z"
      />
    </svg>
  );
}
