//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: wrench.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
}

export function WrenchIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--wrench', props.className)}
      style={props.style}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      <path
        fill="#222"
        fill-rule="evenodd"
        d="M32.543 8.896A16 16 0 0 1 48 4.5a3.93 3.93 0 0 1 2.77 2.8 4 4 0 0 1-1 3.9l-7.1 7.1a2.19 2.19 0 0 0-.41 2.75 2 2 0 0 0 3.13.29L52.74 14a4 4 0 0 1 6.69 1.75 16 16 0 0 1-19.94 19.59L17 57.76A7.68 7.68 0 0 1 11.6 60h-.36a7.71 7.71 0 0 1-5.55-2.79 7.85 7.85 0 0 1 .68-10.45L28.7 24.5a16 16 0 0 1 3.843-15.604zM44 8a12 12 0 0 0-11.18 16.32l.47 1.22-24.1 24.05a3.82 3.82 0 0 0-.41 5.07A3.64 3.64 0 0 0 11.43 56a3.69 3.69 0 0 0 2.76-1.07l24.27-24.22 1.22.47a12 12 0 0 0 16.18-9.32 12.08 12.08 0 0 0-.28-5.06l-7.35 7.37a6 6 0 0 1-9.23-.82 6.15 6.15 0 0 1 .84-7.88l7.1-7.1A11.563 11.563 0 0 0 44 8zM12 50a2 2 0 1 1 0 4 2 2 0 0 1 0-4z"
      />
    </svg>
  );
}
