---
platform: linux

image_resource:
  type: docker-image
  # Pull image through Telia Company Artifacts for Docker Hub
  # See: https://github.com/TeliaSoneraNorge/common-artifacts-ecr-sync
  source:
    repository: http://987227049932.dkr.ecr.eu-west-1.amazonaws.com/node
    tag: '12.18.4'

inputs:
  - name: styleguide
  - name: node_modules
    path: /cache

params:
  npm_token:
  update_type:

outputs:
  - name: styleguide

run:
  path: sh
  args:
    - styleguide/ci/tasks/update-and-publish-npm/task.sh
