---
platform: linux

image_resource:
  type: docker-image
  source: {repository: node, tag: "8-alpine" }

inputs:
  - name: styleguide
  - name: node_modules
    path: /cache

params:
  npm_token:
  update_type:

outputs:
  - name: styleguide

run:
  path: sh
  args:
  - styleguide/ci/tasks/update-and-publish-npm/task.sh
