//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: activity-level.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function ActivityLevelIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--activity-level', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path d="M32 6a26 26 0 1026 26A26.029 26.029 0 0032 6zm0 48a22 22 0 1122-22 22.025 22.025 0 01-22 22zm16-22a2 2 0 01-4 0 11.974 11.974 0 00-.497-3.429 2.001 2.001 0 013.834-1.142c.44 1.484.664 3.023.663 4.571zm-10.586-2.586l8-8a2 2 0 00-2.828-2.828l-.781.781A15.99 15.99 0 0016 32a2 2 0 004 0 11.986 11.986 0 0118.945-9.773l-4.36 4.359-.004.006a6.023 6.023 0 102.827 2.827l.006-.005zM32 34a2 2 0 110-4 2 2 0 010 4z" />
    </svg>
  );
}
