//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: add.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function AddIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--add', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path d="M32 6a26 26 0 1026 26A26.029 26.029 0 0032 6zm0 48a22 22 0 1122-22 22.025 22.025 0 01-22 22zm14-22a2 2 0 01-2 2H34v10a2 2 0 01-4 0V34H20a2 2 0 010-4h10V20a2 2 0 014 0v10h10a2 2 0 012 2z" />
    </svg>
  );
}
