//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: ai-robot.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function AiRobotIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--ai-robot', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M54.76 30.973v-6.22a8.303 8.303 0 00-8.293-8.293h-2.073v-4.722a4.147 4.147 0 10-4.147 0v4.722H23.66v-4.722a4.147 4.147 0 10-4.147 0v4.722H17.44a8.303 8.303 0 00-8.293 8.293v6.22a4.147 4.147 0 000 8.294v12.44A8.303 8.303 0 0017.44 60h29.027a8.303 8.303 0 008.293-8.293v-12.44a4.147 4.147 0 100-8.294zm-4.146 20.733a4.151 4.151 0 01-4.147 4.147H17.44a4.151 4.151 0 01-4.147-4.147V24.753a4.151 4.151 0 014.147-4.147h29.027a4.151 4.151 0 014.147 4.147v26.953zM29.88 33.046a6.22 6.22 0 10-6.22 6.22 6.227 6.227 0 006.22-6.22zm-8.293 0a2.073 2.073 0 114.147 0 2.073 2.073 0 01-4.147 0zm18.66-6.22a6.22 6.22 0 106.22 6.22 6.227 6.227 0 00-6.22-6.22zm0 8.294a2.073 2.073 0 110-4.147 2.073 2.073 0 010 4.147zm3.787 9.2c.645.946.4 2.236-.546 2.88-2.304 1.57-6.4 2.433-11.534 2.433s-9.23-.863-11.534-2.432a2.074 2.074 0 012.334-3.428c.59.402 2.998 1.714 9.2 1.714 6.201 0 8.609-1.312 9.2-1.714a2.076 2.076 0 012.88.546z"
        clipRule="evenodd"
      />
    </svg>
  );
}
