//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: alarm.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function AlarmIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--alarm', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M54.72 47.988c-4.004-6.546-5.425-12.081-5.425-21.16 0-6.946-5.555-12.501-12.011-15.074a6.006 6.006 0 10-11.491 0c-6.456 2.573-12.011 8.128-12.011 15.074 0 9.079-1.422 14.614-5.426 21.16a2.593 2.593 0 000 2.623 2.683 2.683 0 002.323 1.381h41.719a2.683 2.683 0 002.352-1.381 2.593 2.593 0 00-.03-2.623zm-41.73 0c3.514-6.386 4.795-12.211 4.795-21.16 0-5.755 5.405-10.009 10.58-11.73a18.17 18.17 0 011.802-.52 38.744 38.744 0 01-.59-4.005 3.426 3.426 0 010-.41 1.555 1.555 0 010-.2 2.002 2.002 0 014.003 0c.004.066.004.133 0 .2.008.137.008.274 0 .41a38.744 38.744 0 01-.59 4.004c.609.142 1.21.316 1.801.52 5.175 1.752 10.58 6.006 10.58 11.732 0 8.948 1.281 14.773 4.795 21.16H12.99z"
        clipRule="evenodd"
      />
      <path d="M21.309 57.487A22.11 22.11 0 0031.539 60a22.1 22.1 0 0010.229-2.463 2.002 2.002 0 10-1.862-3.543 17.867 17.867 0 01-8.368 2.002c-2.91.015-5.78-.672-8.368-2.002a2.002 2.002 0 00-1.861 3.493z" />
    </svg>
  );
}
