//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: alarm-off.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function AlarmOffIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--alarm-off', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M42.419 54.049a2 2 0 01-.166 3.491A22.09 22.09 0 0132.033 60a22.09 22.09 0 01-10.22-2.51 2 2 0 011.86-3.49 18.09 18.09 0 008.36 2 17.85 17.85 0 008.36-2 2 2 0 012.026.049zM7.323 8.65l10.63 8.92 3 2.56L48.263 43l7.29 6.13 3.77 3.16a2 2 0 01.24 2.81l-.15.17a2 2 0 01-2.67.08L52.693 52l-4.77-4-29-24.36-3.19-2.67-11-9.2a2.027 2.027 0 012.59-3.12zm7.56 14.26l3.44 2.88a9.46 9.46 0 00-.06 1.07c0 8.94-1.28 14.76-4.79 21.14h31.34l4.77 4h-38.39a2.68 2.68 0 01-2.35-1.38 2.59 2.59 0 010-2.62c4-6.54 5.42-12.07 5.42-21.14a13 13 0 01.62-3.95zM35.569 5.127a6 6 0 012.244 6.623c6.45 2.57 12 8.12 12 15.06-.04 7.53.94 12.62 3.57 17.88l-6.26-5.24a49.26 49.26 0 01-1.35-12.64c0-5.75-5.4-10-10.57-11.72a18.16 18.16 0 00-1.8-.52 38.7 38.7 0 00.59-4 3.43 3.43 0 000-.41 1.56 1.56 0 000-.2 2 2 0 10-4 0 1.56 1.56 0 000 .2 3.43 3.43 0 000 .41 38.7 38.7 0 00.59 4 18.16 18.16 0 00-1.8.52 19.61 19.61 0 00-6.44 3.62l-3.01-2.59a22.38 22.38 0 017-4.37 6 6 0 019.236-6.623z"
      />
    </svg>
  );
}
