//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: arrow-right.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function ArrowRightIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--arrow-right', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path d="M55.414 33.414l-16 16a2 2 0 01-2.828-2.828L49.172 34H10a2 2 0 110-4h39.172L36.586 17.414a2 2 0 012.828-2.828l16 16a2 2 0 010 2.828z" />
    </svg>
  );
}
