//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: arrow-down.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function ArrowDownIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--arrow-down', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path d="M49.414 39.414l-16 16a1.999 1.999 0 01-2.828 0l-16-16a2 2 0 012.828-2.828L30 49.172V10a2 2 0 114 0v39.172l12.586-12.586a2 2 0 012.828 2.828z" />
    </svg>
  );
}
