//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: arrow-left.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function ArrowLeftIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--arrow-left', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path d="M56 32a2 2 0 01-2 2H14.828l12.586 12.586a2 2 0 11-2.828 2.828l-16-16a2 2 0 010-2.828l16-16a2 2 0 112.828 2.828L14.828 30H54a2 2 0 012 2z" />
    </svg>
  );
}
