//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: arrow-subdirectory.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function ArrowSubdirectoryIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--arrow-subdirectory', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M51.41 35.41l-12 12a2 2 0 01-2.82-2.82L45.17 36H20a8 8 0 01-8-8V18a2 2 0 114 0v10a4 4 0 004 4h25.17l-8.58-8.59a2 2 0 012.82-2.82l12 12a2 2 0 010 2.82z"
      />
    </svg>
  );
}
