//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: arrow-large-right.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function ArrowLargeRightIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--arrow-large-right', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M32.513 51.338a2 2 0 0 1 .026-2.704l.123-.12L48.788 34H10a2 2 0 0 1-1.995-1.85L8 32a2 2 0 0 1 1.85-1.995L10 30h38.789L32.662 15.487a2 2 0 0 1-.259-2.692l.11-.133a2 2 0 0 1 2.692-.259l.133.11 20.008 18.008.14.141.065.075.065.085.087.129.111.206.068.166.058.19.038.192.015.131.007.165-.007.162-.02.166-.02.105-.045.167-.054.15-.07.154-.08.144-.114.164-.111.133-.172.168-19.97 17.973a2 2 0 0 1-2.824-.15z"
      />
    </svg>
  );
}
