//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: arrow-large-left.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function ArrowLargeLeftIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--arrow-large-left', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M31.487 12.662a2 2 0 01-.026 2.704l-.123.12L15.212 30H54a2 2 0 011.995 1.85L56 32a2 2 0 01-1.85 1.995L54 34H15.211l16.127 14.513a2 2 0 01.259 2.692l-.11.133a2 2 0 01-2.692.259l-.133-.11L8.654 33.479l-.14-.141-.065-.075-.065-.085-.087-.129-.111-.206-.068-.166-.058-.19-.038-.192-.015-.131L8 31.999l.007-.162.02-.166.02-.105.045-.167.054-.15.07-.154.08-.144.114-.164.111-.133.172-.168 19.97-17.973a2 2 0 012.824.15z"
      />
    </svg>
  );
}
