//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: arrow-small-down.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function ArrowSmallDownIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--arrow-small-down', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M30.614 45.286L16.272 24.45c-.502-.73-.289-1.71.477-2.19.27-.169.586-.259.91-.259h28.683C47.257 22 48 22.708 48 23.581c0 .309-.095.61-.272.868L33.387 45.286c-.503.73-1.531.934-2.297.455"
      />
    </svg>
  );
}
