//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: attachment.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function AttachmentIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--attachment', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M56.772 26.488l-9.35 9.407-11.084 10.982-5.992 6.037c-6.086 5.917-15.797 5.85-21.799-.153-6.003-6.003-6.07-15.713-.153-21.8l17.893-17.893a2.31 2.31 0 113.254 3.278l-17.893 17.87c-4.274 4.277-4.271 11.21.006 15.484 4.277 4.274 11.21 4.271 15.484-.006l6.106-6.095 20.343-20.354a6.9 6.9 0 00-4.945-11.787 6.9 6.9 0 00-4.876 2.013l-3.6 3.6v.068l-16.73 16.663-2.048 2.093a2.875 2.875 0 000 4.06 2.944 2.944 0 004.071 0l18.71-18.756a2.301 2.301 0 113.254 3.254L28.725 43.15a7.475 7.475 0 11-10.568-10.568l22.355-22.355c4.512-4.358 11.684-4.296 16.12.14 4.436 4.436 4.498 11.608.14 16.12z"
        clipRule="evenodd"
      />
    </svg>
  );
}
