//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: b2b-customer.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function B2bCustomerIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--b2b-customer', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M21.414 17C22.72 12.383 26.964 9 32 9c5.035 0 9.28 3.383 10.586 8H52a8 8 0 018 8v22a8 8 0 01-8 8H12a8 8 0 01-8-8V25a8 8 0 018-8h9.414zm4.26 0a7 7 0 0112.652 0H25.674zM56 25a4 4 0 00-4-4H12a4 4 0 00-4 4v4a4 4 0 004 4h12v-.5a4 4 0 014-4h7a4 4 0 014 4v.5h13a4 4 0 004-4v-4zM12 37h12.03A4 4 0 0028 40.5h7a4 4 0 003.97-3.5H52c1.457 0 2.823-.39 4-1.07V47a4 4 0 01-4 4H12a4 4 0 01-4-4V35.93A7.963 7.963 0 0012 37zm16-4.5v4h7v-4h-7z"
        clipRule="evenodd"
      />
    </svg>
  );
}
