//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: bag.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function BagIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--bag', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path d="M55.33 49.191l-3.15-29.615A3.992 3.992 0 0048.203 16H44a12 12 0 00-24 0h-4.2a3.993 3.993 0 00-3.98 3.576L8.67 49.204A8 8 0 0016.631 58h30.74a8.001 8.001 0 007.96-8.809zM32.002 8a8.01 8.01 0 018 8h-16a8.009 8.009 0 018-8zm18.336 44.685A3.956 3.956 0 0147.371 54h-30.74a3.999 3.999 0 01-3.98-4.385L15.8 20H20v8a2 2 0 004 0v-8h16v8a2 2 0 004 0v-8h4.202l3.148 29.602a3.953 3.953 0 01-1.014 3.083z" />
    </svg>
  );
}
