//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: basketball.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function BasketballIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--basketball', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M51.905 51.669c10.832-10.944 10.788-28.584-.101-39.473-10.889-10.889-28.529-10.934-39.473-.1-.043.036-.09.065-.13.105-.04.04-.07.087-.106.13-10.833 10.944-10.788 28.584.101 39.473 10.889 10.889 28.529 10.934 39.473.1.043-.036.09-.065.13-.105.04-.04.07-.087.106-.13zm-21.99 3.926a23.583 23.583 0 01-13.067-5.398L32 35.046l4.554 4.554a27.91 27.91 0 00-6.639 15.995zm9.685-12.95l7.552 7.552a23.585 23.585 0 01-12.91 5.386A23.62 23.62 0 0139.6 42.645zm3.046-3.045a23.62 23.62 0 0112.937-5.358 23.584 23.584 0 01-5.386 12.91L42.646 39.6zm12.949-9.684a27.91 27.91 0 00-15.996 6.638L35.045 32l15.152-15.152a23.583 23.583 0 015.398 13.068zM13.803 16.848l7.466 7.467a23.623 23.623 0 01-12.845 5.35 23.587 23.587 0 015.379-12.817zm3.045-3.045a23.586 23.586 0 0112.816-5.379 23.622 23.622 0 01-5.35 12.845l-7.466-7.466zm17.144-5.405a23.582 23.582 0 0113.16 5.405L32 28.954l-4.64-4.639a27.913 27.913 0 006.632-15.917zM8.398 33.992a27.911 27.911 0 0015.917-6.631L28.955 32 13.803 47.15a23.582 23.582 0 01-5.405-13.159z"
        clipRule="evenodd"
      />
    </svg>
  );
}
