//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: battery.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function BatteryIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--battery', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M27.415 24.586A2 2 0 0026 24H15.82A3.674 3.674 0 0012 27.5v9a3.674 3.674 0 003.82 3.5H38a2 2 0 001.414-3.414l-12-12zM16 35.994V28h9.172l7.998 7.998L16 35.995zM56 22h-.252A8.015 8.015 0 0048 16H12a8.01 8.01 0 00-8 8v16a8.01 8.01 0 008 8h36a8.015 8.015 0 007.748-6H56c2.244 0 4-2.05 4-4.666V26.666C60 24.05 58.244 22 56 22zm0 15.334c.008.233-.051.465-.17.666H52v2a4.004 4.004 0 01-4 4H12a4.004 4.004 0 01-4-4V24a4.004 4.004 0 014-4h36a4.004 4.004 0 014 4v2h3.83c.119.201.178.433.17.666v10.668z"
        clipRule="evenodd"
      />
    </svg>
  );
}
