//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: battery.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function BatteryIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--battery', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M48 16a8 8 0 017.75 6H56c2.24 0 4 2.05 4 4.67v10.66C60 40 58.24 42 56 42h-.25A8 8 0 0148 48H12a8 8 0 01-8-8V24a8 8 0 018-8zm0 4H12a4 4 0 00-4 4v16a4 4 0 004 4h36a4 4 0 004-4v-2h3.83c.118-.203.176-.435.17-.67V26.67a1.275 1.275 0 00-.17-.67H52v-2a4 4 0 00-4-4zm-32.374 3.997l.194.003H26a2 2 0 011.41.59l12 12a2 2 0 01.44 2.18A2 2 0 0138 40H15.82A3.67 3.67 0 0112 36.5v-9a3.67 3.67 0 013.82-3.5zM25.17 28H16v8h17.17l-8-8z"
      />
    </svg>
  );
}
