//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: blood-pressure.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function BloodPressureIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--blood-pressure', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M55.826 34.275l-20.494 21.25a4.297 4.297 0 01-3.108 1.327h-.008a4.298 4.298 0 01-3.107-1.317L8.329 34.12a14.98 14.98 0 01-1.779-2.063 2.166 2.166 0 011.801-3.37h9.495l3.734-7.47a2.167 2.167 0 013.876 0l6.729 13.459 2.395-4.792a2.167 2.167 0 011.938-1.197h6.5a2.167 2.167 0 110 4.333h-5.161l-3.734 7.47a2.167 2.167 0 01-3.877 0l-6.728-13.46-2.395 4.791a2.167 2.167 0 01-1.939 1.198h-5.883l18.917 19.498 20.489-21.25c4.407-4.642 4.396-11.926-.025-16.553a10.927 10.927 0 00-7.894-3.38h-.017a10.929 10.929 0 00-7.9 3.404l-3.15 3.266c-.408.422-.97.661-1.557.662h-.003a2.166 2.166 0 01-1.555-.658l-3.159-3.256a10.928 10.928 0 00-7.894-3.38h-.016a10.93 10.93 0 00-7.901 3.404 11.907 11.907 0 00-3.244 9.411 2.167 2.167 0 01-4.314.409 16.24 16.24 0 014.439-12.829A15.226 15.226 0 0119.53 7.038h.023a15.227 15.227 0 0111.004 4.696l1.6 1.649 1.594-1.654A15.226 15.226 0 0144.764 7h.024a15.227 15.227 0 0111.004 4.696c6.03 6.313 6.045 16.248.034 22.579z"
        clipRule="evenodd"
      />
    </svg>
  );
}
