//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: bluetooth.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function BluetoothIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--bluetooth', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M31.126 8.201a2 2 0 012.11.226l14 11a2 2 0 010 3.146l-12 9.427 11.998 9.427a2 2 0 010 3.146l-14 11A2 2 0 0130 54V36.115l-10.765 8.458a2 2 0 01-2.47-3.146L28.762 32l-11.999-9.427a2 2 0 012.471-3.146L30 27.885V10a2 2 0 011.126-1.799zM34 36.115L42.763 43 34 49.885v-13.77zm0-8.23v-13.77L42.763 21 34 27.885z"
        clipRule="evenodd"
      />
    </svg>
  );
}
