//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: bookmark.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function BookmarkIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--bookmark', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path d="M46 6H18a8.01 8.01 0 00-8 8v41.839a3.97 3.97 0 002.268 3.605 3.97 3.97 0 004.23-.482L32 46.562l15.502 12.4A4 4 0 0054 55.839V14a8.01 8.01 0 00-8-8zM34.499 43.438a3.974 3.974 0 00-4.997 0L14 55.838V14a4.004 4.004 0 014-4h28a4.004 4.004 0 014 4l.013 41.848-15.514-12.41z" />
    </svg>
  );
}
