//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: broken-phone.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function BrokenPhoneIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--broken-phone', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path d="M33.56 7.914l3.77 1.277a3.77 3.77 0 012.353 4.777l-3.75 11.219a1.995 1.995 0 001.247 2.523c.206.07.421.107.638.11a1.995 1.995 0 001.885-1.357l3.81-11.209a7.749 7.749 0 00-4.857-9.833l-3.81-1.276a1.995 1.995 0 10-1.286 3.77zm-4.218 44.328a1.925 1.925 0 11-3.85 0 1.925 1.925 0 013.85 0z" />
      <path
        fillRule="evenodd"
        d="M38.856 34.012c0-1.102.893-1.995 1.994-1.995a1.995 1.995 0 012.014 1.995v18.24A7.758 7.758 0 0135.117 60H19.759A7.768 7.768 0 0112 52.252V14.845a7.768 7.768 0 017.739-7.758h7.04a1.994 1.994 0 010 3.989h-7.04a3.77 3.77 0 00-3.75 3.77v29.647h22.867V34.012zm-19.117 21.94h15.357v.059a3.76 3.76 0 003.83-3.76v-3.77H15.988v3.77a3.76 3.76 0 003.75 3.7zm25.369-30.836c.33-.003.655-.085.947-.239l4.837-2.662a1.995 1.995 0 10-1.915-3.5l-4.856 2.662a1.994 1.994 0 00.997 3.74h-.01zm-.04 0h-.01.05-.04z"
        clipRule="evenodd"
      />
      <path d="M45.736 27.031l4.668 1.357v-.02a1.994 1.994 0 01-.549 3.919 2.081 2.081 0 01-.548-.08l-4.668-1.336a1.996 1.996 0 111.097-3.84z" />
    </svg>
  );
}
