//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: bulb.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function BulbIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--bulb', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M59.999 32a2 2 0 01-2 2h-4a2 2 0 010-4h4a2 2 0 012 2zm-8.201-19.8a2 2 0 00-2.828 0l-2.828 2.828a2 2 0 102.828 2.828l2.828-2.828a2 2 0 000-2.828zM31.999 12a2 2 0 002-2V6a2 2 0 10-4 0v4a2 2 0 002 2zm-14.142 5.857a1.999 1.999 0 000-2.828l-2.828-2.828a2 2 0 10-2.828 2.828l2.828 2.828a1.999 1.999 0 002.828 0zM10 30H6a2 2 0 100 4h4a2 2 0 000-4zm37.999 2a15.968 15.968 0 01-5.53 12.075c-.347.314-.63.695-.831 1.119l-1.639 3.278v3.3a8.123 8.123 0 01-7.009 8.166A8.002 8.002 0 0124 52v-3.527l-1.642-3.284a3.583 3.583 0 00-.83-1.118A15.99 15.99 0 1147.998 32zm-12 18h-8v2a4.002 4.002 0 004.51 3.968A4.175 4.175 0 0036 51.77V50zm8-18a12 12 0 10-19.853 9.046 7.547 7.547 0 011.79 2.352l1.3 2.601h9.527l1.297-2.595a7.54 7.54 0 011.792-2.353 11.973 11.973 0 004.147-9.052z"
        clipRule="evenodd"
      />
    </svg>
  );
}
