//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: business-intelligence.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function BusinessIntelligenceIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--business-intelligence', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M46.553 24h-1.2a10.09 10.09 0 00-1.46-3.51l1.07-1.08a2 2 0 00-2.82-2.82l-1.08 1.07a10.09 10.09 0 00-3.51-1.46V15a2 2 0 10-4 0v1.2a10.09 10.09 0 00-3.51 1.46l-1.08-1.07a2 2 0 00-2.82 2.82l1.07 1.08a10.09 10.09 0 00-1.46 3.51h-1.2a2 2 0 100 4h1.2a10.09 10.09 0 001.46 3.51l-1.07 1.08a2 2 0 102.82 2.82l1.08-1.07a10.09 10.09 0 003.51 1.46V37a2 2 0 104 0v-1.2a10.09 10.09 0 003.51-1.46l1.08 1.07a2 2 0 002.82-2.82l-1.07-1.08a10.09 10.09 0 001.46-3.51h1.2a2 2 0 100-4zm-11 8a6 6 0 110-12 6 6 0 010 12z"
        clipRule="evenodd"
      />
      <path
        fill-rule="evenodd"
        d="M34.553 4c-12.404-.007-22.58 9.823-23 22.22l-4.54 5.12a4 4 0 003 6.66h1.54v8a4 4 0 004 4h6a4 4 0 014 4v2a4 4 0 004 4h16a4 4 0 004-4V44.91a24.08 24.08 0 008-17.91c0-12.703-10.298-23-23-23zm12.4 37.9a4 4 0 00-1.4 3V56h-16v-2a8 8 0 00-8-8h-6V34h-5.55l5.55-6.24V27c0-10.493 8.506-19 19-19 10.493 0 19 8.507 19 19a20.27 20.27 0 01-6.6 14.9z"
        clip-rule="evenodd"
      />
    </svg>
  );
}
