//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: business-intelligence.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function BusinessIntelligenceIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--business-intelligence', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M35 4c12.703 0 23 10.297 23 23a24.08 24.08 0 01-8 17.91V56a4 4 0 01-4 4H30a4 4 0 01-4-4v-2a4 4 0 00-4-4h-6a4 4 0 01-4-4v-8h-1.54a4 4 0 01-3-6.66L12 26.22C12.42 13.823 22.596 3.993 35 4zm0 4c-10.493 0-19 8.507-19 19v.76L10.45 34H16v12h6a8 8 0 018 8v2h16V44.9a4 4 0 011.4-3A20.27 20.27 0 0054 27c0-10.493-8.507-19-19-19zm1 5a2 2 0 012 2v1.2a10.09 10.09 0 013.51 1.46l1.08-1.07a2 2 0 012.82 2.82l-1.07 1.08A10.09 10.09 0 0145.8 24H47a2 2 0 110 4h-1.2a10.09 10.09 0 01-1.46 3.51l1.07 1.08a2 2 0 01-2.82 2.82l-1.08-1.07A10.09 10.09 0 0138 35.8V37a2 2 0 11-4 0v-1.2a10.09 10.09 0 01-3.51-1.46l-1.08 1.07a2 2 0 11-2.82-2.82l1.07-1.08A10.09 10.09 0 0126.2 28H25a2 2 0 110-4h1.2a10.09 10.09 0 011.46-3.51l-1.07-1.08a2 2 0 012.82-2.82l1.08 1.07A10.09 10.09 0 0134 16.2V15a2 2 0 012-2zm0 7a6 6 0 100 12 6 6 0 000-12z"
      />
    </svg>
  );
}
