//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: camera.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function CameraIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--camera', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M51.385 16.923h-4.909L43.848 9.04C42.812 5.931 40.554 4 37.957 4H26.043c-2.597 0-4.855 1.931-5.891 5.04l-2.628 7.883h-4.909A8.625 8.625 0 004 25.54v25.846A8.625 8.625 0 0012.615 60h38.77A8.625 8.625 0 0060 51.385V25.539a8.625 8.625 0 00-8.615-8.616zm-27.147-6.52c.459-1.376 1.255-2.095 1.805-2.095h11.913c.55 0 1.347.72 1.805 2.094l2.174 6.521h-19.87l2.173-6.52zm31.454 40.982a4.312 4.312 0 01-4.307 4.307h-38.77a4.312 4.312 0 01-4.307-4.307V25.539a4.312 4.312 0 014.307-4.308h38.77a4.312 4.312 0 014.307 4.307v25.847zM32 25.539c-7.137 0-12.923 5.785-12.923 12.922 0 7.138 5.786 12.924 12.923 12.924 7.137 0 12.923-5.786 12.923-12.923-.008-7.134-5.79-12.916-12.923-12.924zm0 21.538a8.615 8.615 0 118.615-8.615A8.625 8.625 0 0132 47.077z"
        clipRule="evenodd"
      />
    </svg>
  );
}
