//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: card-view.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function CardViewIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--card-view', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M12 8h40a4 4 0 014 4v14a4 4 0 01-4 4H12a4 4 0 01-4-4V12a4 4 0 014-4zm14 18h26V12H26v14zm-4 0V12H12v14h10zm-10 8h40a4 4 0 014 4v14a4 4 0 01-4 4H12a4 4 0 01-4-4V38a4 4 0 014-4zm0 4h10v14H12V38zm40 14H26V38h26v14z"
        clipRule="evenodd"
      />
    </svg>
  );
}
