//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: care.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function CareIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--care', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 65"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M57.402 36.72a8.615 8.615 0 00-2.685-1.881A17.017 17.017 0 0042.78 24.032a13.727 13.727 0 10-24.874.007A16.91 16.91 0 005 40.44v4.223a8.457 8.457 0 008.447 8.447h23.186l6.216 6.426a3.163 3.163 0 004.55-.001l10.003-10.341a9.042 9.042 0 000-12.472zM30.342 8.762a9.503 9.503 0 11-9.503 9.503 9.513 9.513 0 019.502-9.503zm-21.118 35.9v-4.223a12.686 12.686 0 0111.305-12.594 13.683 13.683 0 0019.619.007 12.78 12.78 0 019.68 6.384 8.49 8.49 0 00-4.684 2.486l-.02.02-.02-.02a8.483 8.483 0 00-12.259 0 9.04 9.04 0 00-.269 12.164H13.447a4.228 4.228 0 01-4.223-4.223zm45.142 1.595l-9.242 9.556-9.243-9.556a4.785 4.785 0 010-6.598 4.26 4.26 0 016.188 0l1.537 1.589a2.175 2.175 0 003.035 0l1.538-1.59a4.26 4.26 0 016.187 0 4.784 4.784 0 010 6.599z"
        clipRule="evenodd"
      />
    </svg>
  );
}
