//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: chat.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function ChatIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--chat', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M52 10H24a8 8 0 00-8 8v8h-4a8 8 0 00-8 8v12a8 8 0 008 8h7.17l5.71 5.71a3 3 0 002.12.88 3 3 0 003-3V54h10a8 8 0 008-8v-8h4a8 8 0 008-8V18a8 8 0 00-8-8zm-8 36a4 4 0 01-4 4H26v5.17L20.83 50H12a4 4 0 01-4-4V34a4 4 0 014-4h4a8 8 0 008 8h6v3.59a3 3 0 005.12 2.12L40.83 38H44v8zm12-16a4 4 0 01-4 4H39.17L34 39.17V34H24a4 4 0 01-4-4V18a4 4 0 014-4h28a4 4 0 014 4v12z"
      />
    </svg>
  );
}
