//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: chevron-up.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function ChevronUpIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--chevron-up', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M53.032 42.199a2.166 2.166 0 01-3.064 0L32 24.23 14.032 42.198a2.167 2.167 0 01-3.064-3.064l19.5-19.5a2.166 2.166 0 013.064 0l19.5 19.5a2.166 2.166 0 010 3.064z"
        clipRule="evenodd"
      />
    </svg>
  );
}
