//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: chevron-left.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function ChevronLeftIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--chevron-left', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M42.116 49.89a2.167 2.167 0 01-2.899 3.22l-21.666-19.5a2.166 2.166 0 010-3.22l21.666-19.5a2.167 2.167 0 012.9 3.22L22.237 32l19.878 17.89z"
        clipRule="evenodd"
      />
    </svg>
  );
}
