//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: child-boy.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function ChildBoyIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--child-boy', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M13.87 12.13c5.94-6.68 17.83-9.02 26.68-5.3a13.16 13.16 0 0110.54 5.76c2.47 3.76 2.8 8.76.91 13.76v1.43l.33.09v.02a7.82 7.82 0 010 15l-.76.21a20 20 0 01-39.14 0l-.81-.23a7.82 7.82 0 010-15l.44-.12c-2.8-5.51-2.19-11.14 1.81-15.62zM40 21.78a40.17 40.17 0 01-24 9V39c0 8.837 7.163 16 16 16s16-7.163 16-16V27.66c-3.3-.88-5.92-3.35-8-5.88zm-2.965 22.76a2 2 0 011.785 2.97v.06a7.8 7.8 0 01-6.537 4.01l-.283.005a7.8 7.8 0 01-6.82-4.015 2.011 2.011 0 013.49-2 3.8 3.8 0 006.65 0 2 2 0 011.715-1.03zM12 32a3.81 3.81 0 000 6.75zm40 0v6.7a3.82 3.82 0 000-6.7zm-22.27 3.33c.17.386.21.797.136 1.183a1.997 1.997 0 01-3.796.457 2.06 2.06 0 00-1.85-.8 2.1 2.1 0 00-1.86.8 2 2 0 01-3.872-.714 2 2 0 01.212-.926 5.92 5.92 0 015.52-3.2 5.84 5.84 0 015.51 3.2zm16 0c.17.386.21.797.136 1.183a1.997 1.997 0 01-3.796.457 2.06 2.06 0 00-1.85-.8 2.1 2.1 0 00-1.838.772l.008-.012a2.01 2.01 0 01-.186.302A2.002 2.002 0 0134.7 35.37c.19-.368.415-.71.67-1.024a5.915 5.915 0 014.85-2.216 5.84 5.84 0 015.51 3.2zm-6.838-24.909C31.547 7.38 21.722 9.267 16.86 14.74c-2.15 2.44-4.03 6.49-.78 12a35.77 35.77 0 0022.91-9.34 2 2 0 012.94.3c2.47 3.35 4.65 5.29 6.74 6a10.69 10.69 0 00-.98-8.96 9.15 9.15 0 00-7.64-4h-.06a1.6 1.6 0 01-.39-.05l-.36-.12z"
      />
    </svg>
  );
}
