//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: close.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function CloseIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--close', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M51.365 48.301a2.166 2.166 0 01-3.063 3.064L32.5 35.563 16.7 51.365a2.166 2.166 0 01-3.064-3.064l15.8-15.801-15.801-15.802a2.166 2.166 0 013.064-3.064L32.5 29.436l15.802-15.802a2.167 2.167 0 013.063 3.064L35.564 32.5l15.801 15.8z"
        clipRule="evenodd"
      />
    </svg>
  );
}
