//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: close-circle.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function CloseCircleIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--close-circle', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M32 56c13.255 0 24-10.745 24-24S45.255 8 32 8 8 18.745 8 32s10.745 24 24 24zm0 4c15.464 0 28-12.536 28-28S47.464 4 32 4 4 16.536 4 32s12.536 28 28 28z"
        clipRule="evenodd"
      />
      <path d="M25.277 22.695a2 2 0 10-2.9 2.755l6.864 7.225-6.764 7.12a2 2 0 002.9 2.755L32 35.58l6.622 6.97a2 2 0 102.9-2.755l-6.764-7.12 6.864-7.225a2 2 0 10-2.9-2.755L32 29.771l-6.723-7.076z" />
    </svg>
  );
}
