//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: cloud.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function CloudIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--cloud', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M51.832 30.169A10.017 10.017 0 0042 22c-.436 0-.872.029-1.304.087a14.005 14.005 0 00-26.574 4.06A12 12 0 0016 50h34a10 10 0 001.832-19.831zM50 46H16a8 8 0 110-16h2v-2a10.001 10.001 0 0119.547-2.985l.608 1.951 1.938-.65A5.988 5.988 0 0148 32v2h2a6 6 0 010 12z"
        clipRule="evenodd"
      />
    </svg>
  );
}
