//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: cloud-connect.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function CloudConnectIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--cloud-connect', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path d="M51.607 34.168A10.018 10.018 0 0041.775 26c-.436 0-.872.029-1.304.087a14.004 14.004 0 00-26.574 4.06A12 12 0 0015.775 54h34a10 10 0 001.832-19.832zM49.775 50h-34a8 8 0 010-16h2v-2a10 10 0 0119.547-2.984l.61 1.95 1.936-.65A5.989 5.989 0 0147.775 36v2h2a6 6 0 110 12zM38.663 9.15a2 2 0 011.346-2.487A16.018 16.018 0 0159.917 17.43a2.002 2.002 0 01-1.343 2.5 2 2 0 01-2.491-1.36 12.016 12.016 0 00-14.932-8.073 2.002 2.002 0 01-2.488-1.346zm13.223 10.184a2.002 2.002 0 01-1.22 2.552 2.001 2.001 0 01-2.552-1.22 4.006 4.006 0 00-5.103-2.44 2 2 0 01-1.338-3.77 8.006 8.006 0 0110.213 4.878z" />
    </svg>
  );
}
