//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: coffee.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function CoffeeIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--coffee', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M49.519 41.333a7.26 7.26 0 001.448-14.373 10.783 10.783 0 00-1.344-.142l-1.142-.001v-.002a4.152 4.152 0 00-4.148-4.148h-31.11a4.152 4.152 0 00-4.149 4.148v8.296a18.678 18.678 0 004.755 12.445H10.11A3.115 3.115 0 007 50.666v1.038A8.306 8.306 0 0015.296 60H42.26a8.306 8.306 0 008.297-8.296v-1.037a3.115 3.115 0 00-3.111-3.111h-3.718a18.712 18.712 0 003.683-6.223h2.109zm-.046-10.37c.224.008.448.029.67.062a3.112 3.112 0 01-.624 6.16h-1.162c.08-.688.122-1.38.125-2.074v-4.148h.991zM42.26 55.852H15.296a4.152 4.152 0 01-4.148-4.148h35.26a4.152 4.152 0 01-4.149 4.148zm-21.985-8.296a14.532 14.532 0 01-7.052-12.445v-8.296h31.111v8.296a14.532 14.532 0 01-7.052 12.445H20.275zm.993-35.867a2.077 2.077 0 000-2.933L20.052 7.54a2.074 2.074 0 112.933-2.933L24.2 5.823a6.227 6.227 0 010 8.798l-.357.357a2.074 2.074 0 00-.327 2.508 2.075 2.075 0 01-3.585 2.089 6.227 6.227 0 01.98-7.53l.356-.357zm10.371 0a2.076 2.076 0 000-2.933L30.423 7.54a2.074 2.074 0 112.933-2.933l1.215 1.216a6.227 6.227 0 010 8.798l-.356.357a2.074 2.074 0 00-.329 2.507 2.074 2.074 0 11-3.585 2.087 6.225 6.225 0 01.98-7.527l.357-.357z"
        clipRule="evenodd"
      />
    </svg>
  );
}
