//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: coffee.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function CoffeeIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--coffee', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M49 40.89a7 7 0 001.4-13.86 10.57 10.57 0 00-1.3-.14H48a4 4 0 00-4-4H14a4 4 0 00-4 4v8a18 18 0 004.58 12H11a3 3 0 00-3 3v1a8 8 0 008 8h26a8 8 0 008-8v-1a3 3 0 00-3-3h-3.58a18.23 18.23 0 003.58-6h2zm0-10c.214.008.428.028.64.06a3 3 0 01-.64 5.94h-1.12a19 19 0 00.12-2v-4h1zm-7 24H16a4 4 0 01-4-4h34a4 4 0 01-4 4zm-21.2-8a14 14 0 01-6.8-12v-8h30v8a14 14 0 01-6.8 12H20.8zm1-34.59a2 2 0 000-2.82L20.59 8.3a2 2 0 012.82-2.82l1.18 1.17a6 6 0 010 8.48l-.35.35a2 2 0 00-.31 2.41 2 2 0 01-.72 2.74 2.07 2.07 0 01-1 .27 2 2 0 01-1.73-1 6 6 0 01.94-7.26l.38-.34zm10 0a2 2 0 000-2.82L30.59 8.3a2 2 0 012.82-2.82l1.18 1.17a6 6 0 010 8.48l-.35.35a2 2 0 00-.31 2.41 2 2 0 01-3.46 2 6 6 0 01.94-7.26l.39-.33z"
      />
    </svg>
  );
}
