//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: connected.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function ConnectedIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--connected', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M8 32C8 18.745 18.745 8 32 8s24 10.745 24 24c0 12.581-9.68 22.902-22 23.918V47h1.948a6.277 6.277 0 004.165-1.58A5.609 5.609 0 0042 41.222V31a2 2 0 100-4h-4v-6a2 2 0 10-4 0v6h-5v-6a2 2 0 10-4 0v6h-4a2 2 0 100 4v10.086A5.914 5.914 0 0026.914 47H30v11a2 2 0 002 2c15.464 0 28-12.536 28-28S47.464 4 32 4 4 16.536 4 32c0 10.805 6.121 20.178 15.076 24.845a2 2 0 001.848-3.547C13.24 49.292 8 41.257 8 32zm17-1v10.086A1.914 1.914 0 0026.914 43h9.034c.557 0 1.094-.204 1.51-.573.345-.306.542-.744.542-1.204V31H25z"
        clipRule="evenodd"
      />
    </svg>
  );
}
