//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: connected-building.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function ConnectedBuildingIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--connected-building', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M46.34 25.745a4.15 4.15 0 00-5.866 0l-7.437 7.437V15.375a4.152 4.152 0 00-4.148-4.148H8.149A4.152 4.152 0 004 15.375v39.407a4.152 4.152 0 004.148 4.148h45.63a4.152 4.152 0 004.148-4.148V39.048a4.12 4.12 0 00-1.215-2.933l-10.37-10.37zM20.593 54.782h-4.149v-4.148h4.149v4.148zm8.296 0H24.74V48.56a2.074 2.074 0 00-2.074-2.074H14.37a2.074 2.074 0 00-2.074 2.074v6.222H8.148V15.375l20.74-.003v39.41zm24.889 0H33.037V39.048l10.37-10.37 10.37 10.37v15.734zM24.74 40.264a2.074 2.074 0 01-2.074 2.074H14.37a2.074 2.074 0 110-4.148h8.297c1.145 0 2.074.928 2.074 2.074zm0-8.297a2.074 2.074 0 01-2.074 2.074H14.37a2.074 2.074 0 110-4.148h8.297c1.145 0 2.074.929 2.074 2.074zm0-8.296a2.074 2.074 0 01-2.074 2.074H14.37a2.074 2.074 0 110-4.148h8.297c1.145 0 2.074.928 2.074 2.074zM39.259 38.19h8.297a2.074 2.074 0 010 4.148h-8.297a2.074 2.074 0 110-4.148zm10.37 10.37a2.074 2.074 0 01-2.073 2.074h-8.297a2.074 2.074 0 110-4.148h8.297c1.145 0 2.074.928 2.074 2.074zm8.888-29.123a2.07 2.07 0 01-2.58-1.397c-1.97-6.582-8.897-10.328-15.484-8.372a2.074 2.074 0 11-1.185-3.976c8.784-2.609 18.021 2.387 20.646 11.165a2.074 2.074 0 01-1.397 2.58zm-18.784-3.014a2.074 2.074 0 011.261-2.649 8.302 8.302 0 0110.591 5.058 2.074 2.074 0 11-3.911 1.381 4.154 4.154 0 00-5.292-2.53 2.074 2.074 0 01-2.649-1.26z"
        clipRule="evenodd"
      />
    </svg>
  );
}
