//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: construction.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function ConstructionIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--construction', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path d="M54 18a4.004 4.004 0 004-4v-4a4.004 4.004 0 00-4-4H14.83A3.973 3.973 0 0012 7.172l-5.707 5.707A3 3 0 008.414 18h3.587v6.35a5.997 5.997 0 107.196 8.651 2 2 0 10-3.463-2.002A2 2 0 1114 28a2 2 0 002-2v-8h18v36h-4a2 2 0 000 4h26a2 2 0 000-4h-4V18h2zm-6 36h-9.34l9.342-10.677V54zm-10-5.323V38h9.343L38 48.677zM48 34h-9.34l9.342-10.677V34zm-10-5.323V18h9.343L38 28.677zM10.83 14l4-4H54l.003 4H10.829z" />
    </svg>
  );
}
