//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: contact.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function ContactIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--contact', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M54 12a6 6 0 016 6v28a6 6 0 01-6 6H10a6 6 0 01-6-6V18a6 6 0 016-6h44zm0 4H10a2 2 0 00-1.995 1.85L8 18v28a2 2 0 001.85 1.995L10 48h44a2 2 0 001.995-1.85L56 46V18a2 2 0 00-2-2zm-29.5 4c3.945 0 7.143 3.168 7.143 7.077a6.932 6.932 0 01-1.067 3.698c3.74.758 6.425 4.02 6.424 7.802v.885C37 41.416 35.401 43 33.429 43H15.57C13.6 43 12 41.416 12 39.462v-.885c-.001-3.783 2.684-7.044 6.424-7.802a6.932 6.932 0 01-1.067-3.698c0-3.909 3.198-7.077 7.143-7.077zm3.712 13c-2.128 1.581-5.31 1.581-7.438 0-2.666.084-4.776 1.94-4.774 4.2v.6c0 .663.634 1.2 1.417 1.2h14.166c.783 0 1.417-.537 1.417-1.2v-.6c.002-2.265-2.117-4.122-4.788-4.2zM50 28a2 2 0 110 4H39a2 2 0 110-4h11zm-25.5-4a3.5 3.5 0 100 7 3.5 3.5 0 000-7zM50 21a2 2 0 110 4H39a2 2 0 110-4h11z"
      />
    </svg>
  );
}
