//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: copy.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function CopyIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--copy', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path d="M49.333 58H25.5c-.575 0-1.126-.21-1.532-.586A1.925 1.925 0 0123.333 56V26c0-2.122.913-4.157 2.539-5.657C27.497 18.843 29.702 18 32 18h23.833c.575 0 1.126.21 1.532.586.407.375.635.884.635 1.414v30c0 2.122-.913 4.157-2.538 5.657-1.626 1.5-3.83 2.343-6.129 2.343zm-21.666-4h21.666c1.15 0 2.252-.421 3.064-1.172.813-.75 1.27-1.767 1.27-2.828V22H32c-1.15 0-2.252.421-3.064 1.172-.813.75-1.27 1.767-1.27 2.828v28z" />
      <path d="M16.833 48H8.167c-.575 0-1.126-.21-1.532-.586A1.925 1.925 0 016 46V14c0-2.122.913-4.157 2.538-5.657C10.164 6.843 12.368 6 14.667 6H38.5c.575 0 1.126.21 1.532.586.407.375.635.884.635 1.414v4c0 .53-.228 1.04-.635 1.414A2.261 2.261 0 0138.5 14c-.574 0-1.126-.21-1.532-.586A1.925 1.925 0 0136.333 12v-2H14.668c-1.15 0-2.252.421-3.064 1.172-.813.75-1.27 1.767-1.27 2.828v30h6.5c.575 0 1.126.21 1.533.586.406.375.634.884.634 1.414 0 .53-.228 1.04-.634 1.414a2.262 2.262 0 01-1.533.586z" />
    </svg>
  );
}
