//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: core-router.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function CoreRouterIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--core-router', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path d="M38.642 18.243l-7.07-7.071-7.072 7.07a2 2 0 002.828 2.83l2.465-2.465V26a2 2 0 004 0v-6.95l2.02 2.021a2 2 0 102.83-2.828zm4.6 6.343l-7.07 7.07 7.07 7.072a2 2 0 002.829-2.829l-2.464-2.464H51a2 2 0 100-4h-6.95l2.02-2.021a2 2 0 00-2.828-2.828zm-4.6 21.171l-7.07 7.071-7.072-7.07a2 2 0 012.828-2.83l2.465 2.465V38a2 2 0 014 0v6.95l2.02-2.021a2 2 0 112.83 2.828zM20.758 24.586l7.07 7.07-7.07 7.072a2 2 0 01-2.829-2.829l2.464-2.464H13a2 2 0 110-4h6.95l-2.02-2.021a2 2 0 012.828-2.828z" />
      <path
        fillRule="evenodd"
        d="M32 8C18.745 8 8 18.745 8 32s10.745 24 24 24 24-10.745 24-24S45.255 8 32 8zM4 32C4 16.536 16.536 4 32 4s28 12.536 28 28-12.536 28-28 28S4 47.464 4 32z"
        clipRule="evenodd"
      />
    </svg>
  );
}
