//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: customer-dialogue.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function CustomerDialogueIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--customer-dialogue', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 65"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M52 16.5a2 2 0 01-2 2H36a2 2 0 110-4h14a2 2 0 012 2zm-8 4h-8a2 2 0 100 4h8a2 2 0 100-4zm16-6v10a8.01 8.01 0 01-8 8h-1.172l-5.707 5.707A3 3 0 0140 36.086V32.5h-4a11.924 11.924 0 01-1.984 6.594A14.02 14.02 0 0144 52.5a6.007 6.007 0 01-6 6H10a6.007 6.007 0 01-6-6 14.02 14.02 0 019.985-13.406A11.956 11.956 0 0126 20.68V14.5a8.01 8.01 0 018-8h18a8.01 8.01 0 018 8zm-44 18a8 8 0 108-8 8.01 8.01 0 00-8 8zm14.572 10.029a11.94 11.94 0 01-13.143 0A10.004 10.004 0 008 52.499a2.003 2.003 0 002 2h28a2.003 2.003 0 002-2 10.004 10.004 0 00-9.428-9.97zM56 14.5a4.004 4.004 0 00-4-4H34a4.004 4.004 0 00-4 4v7.623a12.046 12.046 0 015.3 6.377H44v5.172l5.172-5.172H52a4.004 4.004 0 004-4v-10z"
        clipRule="evenodd"
      />
    </svg>
  );
}
