//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: data-transfer.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function DataTransferIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--data-transfer', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path d="M13.373 10a1.994 1.994 0 00-1.518.68l-7.27 7.27a2 2 0 102.83 2.828l4.307-4.308V34a2 2 0 104 0V17.193l3.586 3.585a2 2 0 002.828-2.828l-7.27-7.27a1.994 1.994 0 00-1.493-.68zm15.349 19.53l-4.308-4.308a2 2 0 10-2.828 2.828l7.269 7.27a1.994 1.994 0 001.518.68 1.993 1.993 0 001.493-.68l7.27-7.27a2 2 0 10-2.828-2.828l-3.586 3.585V12a2 2 0 00-4 0v17.53zM45.74 47a2 2 0 104 0 2 2 0 00-4 0z" />
      <path
        fillRule="evenodd"
        d="M56 11a4 4 0 014 4v36a4 4 0 01-4 4H40a4 4 0 01-4-4V35.692a2 2 0 114 0v3.616h15.461c.187 0 .368.025.539.073V15H40v4.23a2 2 0 01-4 0V15a4 4 0 014-4h16zm0 32.234a2.002 2.002 0 01-.539.074H40V51h16v-7.766z"
        clipRule="evenodd"
      />
    </svg>
  );
}
