//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: delete-filled.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function DeleteFilledIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--delete-filled', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M55.414 15.414A2 2 0 0054 12H44V8a4.004 4.004 0 00-4-4H24a4.004 4.004 0 00-4 4v4H10a2 2 0 100 4h44a2 2 0 001.414-.586zM40 12H24V8h16v4zM12 50V22a2 2 0 012-2h36a2 2 0 012 2v28a8 8 0 01-8 8H20a8 8 0 01-8-8zm16-1V29a2 2 0 00-4 0v20a2 2 0 004 0zm12 0V29a2 2 0 00-4 0v20a2 2 0 004 0z"
        clipRule="evenodd"
      />
    </svg>
  );
}
