//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: delete.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function DeleteIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--delete', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path d="M50 20a2 2 0 00-2 2v28a4 4 0 01-4 4H20a4 4 0 01-4-4V22a2 2 0 00-4 0v28a8 8 0 008 8h24a8 8 0 008-8V22a2 2 0 00-2-2zM54 12H44V8a4 4 0 00-4-4H24a4 4 0 00-4 4v4H10a2 2 0 000 4h44a2 2 0 000-4zM24 8h16v4H24z" />
      <path d="M28 46V26a2 2 0 00-4 0v20a2 2 0 004 0zM40 46V26a2 2 0 00-4 0v20a2 2 0 004 0z" />
    </svg>
  );
}
