//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: desktop.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function DesktopIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--desktop', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path d="M52 12H12a8.01 8.01 0 00-8 8v20a8.01 8.01 0 008 8h40a8.01 8.01 0 008-8V20a8.01 8.01 0 00-8-8zm4 28a4.005 4.005 0 01-4 4H12a4.004 4.004 0 01-4-4V20a4.004 4.004 0 014-4h40a4.005 4.005 0 014 4v20zM44 52a2 2 0 01-2 2H22a2 2 0 010-4h20a2 2 0 012 2z" />
    </svg>
  );
}
