//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: devices.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function DevicesIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--devices', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M50 4a8 8 0 0 1 8 8v34a8 8 0 0 1-8 8H31.74A8 8 0 0 1 24 60H14a8 8 0 0 1-8-8V24a8 8 0 0 1 8-8h8v-4a8 8 0 0 1 8-8zM28 48H10v4a4 4 0 0 0 4 4h10a4 4 0 0 0 4-4v-4zm-8.99 2.01a2 2 0 1 1 0 4 2 2 0 0 1 0-4zM54 42H32v8h18a4 4 0 0 0 4-4v-4zm-13.99 2a2 2 0 1 1 0 4 2 2 0 0 1 0-4zM24 20H14a4 4 0 0 0-4 4v20h18V24a4 4 0 0 0-4-4zM50 8H30a4 4 0 0 0-4 4v4.27A8 8 0 0 1 32 24v14h22V12a4 4 0 0 0-4-4z"
      />
    </svg>
  );
}
