//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: doc.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function DocIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--doc', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M50.828 16L40 5.172A3.973 3.973 0 0037.172 4H20a8.01 8.01 0 00-8 8v44a4.004 4.004 0 004 4h28a8.01 8.01 0 008-8V18.828A3.972 3.972 0 0050.828 16zm-5.656 0H40v-5.172L45.172 16zM44 56H16V12a4.004 4.004 0 014-4h16v8a4.004 4.004 0 004 4h8v32a4.004 4.004 0 01-4 4zm-2-20a2 2 0 01-2 2H24a2 2 0 110-4h16a2 2 0 012 2zm0-10a2 2 0 01-2 2H24a2 2 0 110-4h16a2 2 0 012 2zm0 20a2 2 0 01-2 2H24a2 2 0 110-4h16a2 2 0 012 2z"
        clipRule="evenodd"
      />
    </svg>
  );
}
