//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: document.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function DocumentIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--document', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M50 4a4 4 0 014 4v44a8 8 0 01-8 8H14a4 4 0 01-4-4V12a8 8 0 018-8zm0 4H18a4 4 0 00-4 4v44h32a4 4 0 004-4V8zm-8 18a2 2 0 110 4H30a2 2 0 110-4zm-20 0a2 2 0 110 4 2 2 0 010-4zm20-8a2 2 0 110 4H30a2 2 0 110-4zm-20 0a2 2 0 110 4 2 2 0 010-4z"
      />
    </svg>
  );
}
