//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: download.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function DownloadIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--download', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M60 29.692v19.385a8.625 8.625 0 01-8.615 8.615h-38.77A8.625 8.625 0 014 49.077V29.692a2.154 2.154 0 014.308 0v19.385a4.313 4.313 0 004.307 4.308h38.77a4.313 4.313 0 004.307-4.308V29.692a2.154 2.154 0 014.308 0zM29.716 43.377a3.233 3.233 0 004.568 0l12.162-12.162A2.154 2.154 0 0043.4 28.17l-9.246 9.247V8.154a2.154 2.154 0 10-4.308 0v29.262L20.6 28.17a2.154 2.154 0 10-3.046 3.045l12.162 12.162z"
        clipRule="evenodd"
      />
    </svg>
  );
}
