//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: drone.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function DroneIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--drone', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path d="M54 18h-2v-4h6a2 2 0 000-4H42a2 2 0 000 4h6v4h-8.764l-.894-1.79A3.98 3.98 0 0034.764 14h-5.528a3.979 3.979 0 00-3.578 2.21L24.764 18H16v-4h6a2 2 0 000-4H6a2 2 0 100 4h6v4h-2a6.007 6.007 0 00-6 6v2a6.007 6.007 0 006 6h12.832a10.004 10.004 0 0018.334.002l.001-.002H54a6.007 6.007 0 006-6v-2a6.007 6.007 0 00-6-6zm2 8a2.003 2.003 0 01-2 2H40.485a2.975 2.975 0 00-2.816 1.973c-.05.143-.106.285-.166.423l-.002.003a6.003 6.003 0 01-11.168-.421A2.98 2.98 0 0023.509 28H10a2.003 2.003 0 01-2-2v-2a2.003 2.003 0 012-2h15.382a2.98 2.98 0 002.683-1.658L29.236 18h5.528l1.17 2.34A2.982 2.982 0 0038.618 22H54a2.003 2.003 0 012 2v2zM25.249 44.69a2 2 0 111.502-3.707 14.116 14.116 0 0010.498 0 2.001 2.001 0 111.502 3.707 18.056 18.056 0 01-13.502 0zm20.482 3.098a1.999 1.999 0 01-.73 2.733 26.029 26.029 0 01-26.002 0 1.999 1.999 0 112.002-3.463 22.03 22.03 0 0021.998 0 1.998 1.998 0 012.732.73z" />
    </svg>
  );
}
