//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: edit.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function EditIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--edit', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path d="M56.752 15.64L47.58 6.466a4.094 4.094 0 00-5.656 0L12.005 36.385a6.027 6.027 0 00-1.45 2.345L5.488 53.937a3.003 3.003 0 003.795 3.795l15.206-5.069a6.027 6.027 0 002.346-1.45l29.918-29.918a4 4 0 000-5.656zM13.625 42.17l7.424 7.423-11.134 3.71 3.71-11.134zm11.127 5.47l-9.172-9.173 23.172-23.172 9.172 9.172L24.752 47.64zm26-26l-9.172-9.173 3.172-3.172 9.174 9.17-3.174 3.174z" />
    </svg>
  );
}
