//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: education.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function EducationIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--education', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M17 4a8 8 0 00-8 8v40a8 8 0 008 8h36.5a2 2 0 100-4h-36a4 4 0 010-8h36a2 2 0 002-2V8a4 4 0 00-4-4H17zm34.5 40V8h-29v36h29zm-33-36H17a4 4 0 00-4 4v33.385A7.962 7.962 0 0117.5 44h1V8z"
        clipRule="evenodd"
      />
    </svg>
  );
}
