//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: email.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function EmailIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--email', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M52 12H12a8 8 0 00-8 8v24a8 8 0 008 8h40a8 8 0 008-8V20a8 8 0 00-8-8zm0 4a3.81 3.81 0 011 .15L39.17 30H24.83L11 16.15a3.81 3.81 0 011-.15h40zm4 28a4 4 0 01-4 4H12a4 4 0 01-4-4V20a3.81 3.81 0 01.15-1L22 32.83A4 4 0 0024.83 34h14.34A4 4 0 0042 32.83L55.85 19a3.8 3.8 0 01.15 1v24z"
      />
    </svg>
  );
}
