//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: entertainment.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function EntertainmentIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--entertainment', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path d="M45.133 32.589l-14 3.111A3.975 3.975 0 0028 39.604v7.343A8.823 8.823 0 0024 46c-4.411 0-8 3.14-8 7s3.589 7 8 7 8-3.14 8-7a6.157 6.157 0 00-.037-.635A1.94 1.94 0 0032 52V39.605l14-3.112v8.454A8.823 8.823 0 0042 44c-4.411 0-8 3.14-8 7s3.589 7 8 7 8-3.14 8-7a6.157 6.157 0 00-.037-.635A1.94 1.94 0 0050 50V36.493a4 4 0 00-4.867-3.904zM24 56c-2.168 0-4-1.374-4-3s1.832-3 4-3 4 1.374 4 3-1.832 3-4 3zm18-2c-2.168 0-4-1.374-4-3s1.832-3 4-3 4 1.374 4 3-1.832 3-4 3zm14-30H26.198l28.234-5.646a4 4 0 003.136-4.707l-1.137-5.692a4 4 0 00-4.707-3.139L7.216 13.718A4.01 4.01 0 004 17.64V50a4.004 4.004 0 004 4h4a2 2 0 000-4H8V28h48v22h-2a2 2 0 000 4h2a4.004 4.004 0 004-4V28a4.004 4.004 0 00-4-4zM45.94 10.485a1.99 1.99 0 00.056-.444l6.512-1.303 1.139 5.694-9.15 1.83 1.443-5.777zm-12 2c.003-.011.003-.023.005-.034l7.769-1.554-1.558 6.233-7.765 1.553 1.55-6.198zm-17.88 9.03a1.988 1.988 0 00-.056.445L8 23.56v-5.92l9.503-1.901-1.443 5.776zm5.784-6.644l7.765-1.553-1.55 6.197c-.002.011-.002.023-.005.035l-7.768 1.553 1.558-6.232z" />
    </svg>
  );
}
