//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: environment.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function EnvironmentIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--environment', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path d="M51.999 8h-20a24.093 24.093 0 00-17.492 7.566 23.982 23.982 0 00-.702 32.075A17.256 17.256 0 009.999 58a2 2 0 004 0 13.06 13.06 0 012.67-7.533A23.864 23.864 0 0032.019 56a23.77 23.77 0 0016.413-6.509A24.092 24.092 0 0056 32V12a4.004 4.004 0 00-4-4zm0 24a19.996 19.996 0 01-32.656 15.484L22.827 44h13.172a2 2 0 000-4h-9.172l6-6h9.172a2 2 0 000-4h-5.172l6.586-6.586a2 2 0 10-2.828-2.828l-6.586 6.586V22a2 2 0 00-4 0v9.172l-6 6V28a2 2 0 00-4 0v13.172l-3.484 3.484A19.997 19.997 0 0131.999 12h20v20z" />
    </svg>
  );
}
