//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: error-filled.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function ErrorFilledIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--error-filled', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 65 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M58.8 43.884L39.397 11.547a7.998 7.998 0 00-13.72-.001L6.275 43.884A8 8 0 0013.134 56H51.94a8 8 0 006.86-12.116zm-28.263-6.907v-11.82a4 4 0 01.316-1.564c.171-.443.438-.844.782-1.172.242-.25.57-.4.918-.421.501 0 1.002.38 1.503 1.142.272.335.44.743.481 1.173v11.82c0 .44-.306.862-.918 1.263-.581.392-1.267.6-1.968.601-.742 0-1.113-.34-1.114-1.022zm4.242 6.947a2.825 2.825 0 00-.572-1.354c-.561-.823-1.103-1.234-1.625-1.234a1.587 1.587 0 00-1.068.482 3.63 3.63 0 00-.872 1.309 4.446 4.446 0 00-.347 1.73c0 .762.422 1.143 1.264 1.143.781 0 1.545-.23 2.196-.662.683-.442 1.024-.914 1.024-1.414z"
        clipRule="evenodd"
      />
    </svg>
  );
}
