//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: external.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function ExternalIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--external', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path d="M59.914 23.848V7.909A3.93 3.93 0 0055.994 4H40.055a2.154 2.154 0 000 4.308h12.407L29.846 30.923a2.154 2.154 0 000 3.048c.393.39.922.614 1.476.624a2.154 2.154 0 001.529-.624l22.755-22.766v12.643a2.154 2.154 0 004.308 0z" />
      <path d="M12.217 60H47.4a8.228 8.228 0 008.217-8.174V38.462a2.154 2.154 0 00-4.308 0v13.321a3.92 3.92 0 01-3.909 3.91H12.217a3.92 3.92 0 01-3.91-3.867v-35.27a3.909 3.909 0 013.91-3.94h13.321a2.154 2.154 0 100-4.308H12.217A8.217 8.217 0 004 16.557v35.27A8.228 8.228 0 0012.217 60z" />
    </svg>
  );
}
