//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: face-id.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function FaceIdIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--face-id', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M20 10c-5.523 0-10 4.477-10 10v2a2 2 0 11-4 0v-2c0-7.732 6.268-14 14-14h2a2 2 0 110 4h-2zm20-2a2 2 0 012-2h2c7.732 0 14 6.268 14 14v2a2 2 0 11-4 0v-2c0-5.523-4.477-10-10-10h-2a2 2 0 01-2-2zM23.519 27c-1.074 0-1.485.402-1.73.893a2 2 0 11-3.579-1.786C19.163 24.197 21 23 23.52 23c2.713 0 4.31 1.578 5.168 2.926a2 2 0 01-3.374 2.148c-.218-.343-.458-.606-.723-.782-.243-.16-.57-.292-1.071-.292zm17 0c-1.074 0-1.485.402-1.73.893a2 2 0 11-3.578-1.786c.952-1.91 2.788-3.107 5.308-3.107 2.713 0 4.31 1.578 5.168 2.926a2 2 0 01-3.374 2.148c-.218-.343-.458-.606-.723-.782-.243-.16-.57-.292-1.071-.292zM21.57 37.602a2 2 0 012.828-.032C25.95 39.087 27.912 41 32 41c3.645 0 6.095-1.957 7.602-3.43a2 2 0 112.796 2.86C40.632 42.157 37.217 45 32 45c-5.724 0-8.671-2.881-10.393-4.565l-.005-.005a2 2 0 01-.032-2.828zM8 40a2 2 0 012 2v2c0 5.523 4.477 10 10 10h2a2 2 0 110 4h-2c-7.732 0-14-6.268-14-14v-2a2 2 0 012-2zm48 0a2 2 0 012 2v2c0 7.732-6.268 14-14 14h-2a2 2 0 110-4h2c5.523 0 10-4.477 10-10v-2a2 2 0 012-2z"
        clipRule="evenodd"
      />
    </svg>
  );
}
