//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: fiber.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function FiberIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--fiber', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path d="M44 28h-2V12a2 2 0 00-4 0v16h-4V6a2 2 0 10-4 0v22h-4V12a2 2 0 00-4 0v16h-2a4.005 4.005 0 00-4 4v24a4.005 4.005 0 004 4h24a4.005 4.005 0 004-4V32a4.005 4.005 0 00-4-4zM20 56V32h24l.003 24H20z" />
    </svg>
  );
}
