//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: film.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function FilmIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--film', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M56 28.667H26.331l30.13-6.55a2.166 2.166 0 001.663-2.542L55.958 8.74a2.166 2.166 0 00-2.605-1.687l-35.265 8.015-.129-.052-.035.089-12.238 2.781A2.167 2.167 0 004 20v32.5a4.338 4.338 0 004.333 4.333H56a4.338 4.338 0 004.333-4.333V33A4.338 4.338 0 0056 28.667zm-17.227-7.139l-7.248 1.576 2.924-7.31 7.26-1.65-2.888 7.218c-.022.055-.03.11-.047.166zm-12.359 2.687l-8.177 1.777 2.866-7.165 8.212-1.866-2.9 7.254zm27.044-5.88l-9.592 2.086 2.977-7.444 5.302-1.205 1.313 6.564zM8.333 21.73l7.636-1.735-2.844 7.109-4.792 1.041V21.73zm0 30.77V33H56l.003 19.5H8.333z"
        clipRule="evenodd"
      />
    </svg>
  );
}
