//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: filter.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function FilterIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--filter', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M57.846 41H46.793a8.603 8.603 0 00-16.663 0H6.154a2.154 2.154 0 100 4.308H30.13a8.603 8.603 0 0016.663 0h11.053a2.154 2.154 0 000-4.308zm-19.384 6.462a4.308 4.308 0 110-8.616 4.308 4.308 0 010 8.616zM6.154 23.769h11.053a8.603 8.603 0 0016.663 0h23.976a2.154 2.154 0 000-4.307H33.87a8.603 8.603 0 00-16.663 0H6.154a2.154 2.154 0 000 4.307zm19.384-6.461a4.308 4.308 0 110 8.615 4.308 4.308 0 010-8.615z"
        clipRule="evenodd"
      />
    </svg>
  );
}
