//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: focus.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function FocusIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--focus', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M32 4a2 2 0 012 2v4.09c10.554.95 18.96 9.356 19.91 19.91H58a2 2 0 110 4h-4.09C52.96 44.554 44.554 52.96 34 53.91V58a2 2 0 11-4 0v-4.09C19.446 52.96 11.04 44.554 10.09 34H6a2 2 0 110-4h4.09c.95-10.554 9.356-18.96 19.91-19.91V6a2 2 0 012-2zm2 45.89V45a2 2 0 10-4 0v4.89c-8.343-.922-14.968-7.547-15.89-15.89H19a2 2 0 100-4h-4.89c.922-8.343 7.547-14.968 15.89-15.89V19a2 2 0 104 0v-4.89c8.343.922 14.968 7.547 15.89 15.89H45a2 2 0 100 4h4.89c-.922 8.343-7.547 14.968-15.89 15.89z"
        clipRule="evenodd"
      />
    </svg>
  );
}
