//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: folder-copy.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function FolderCopyIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--folder-copy', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M12 8a8 8 0 00-8 8v21a8.001 8.001 0 007 7.938V49a8 8 0 008 8h33a8 8 0 008-8V31a8.001 8.001 0 00-7-7.938V20a8 8 0 00-8-8H32.624a6.12 6.12 0 00-5.742-4H12zm17 6.118c0-1.17-.948-2.118-2.118-2.118H12a4 4 0 00-4 4v21a4.002 4.002 0 003 3.874V27a8 8 0 018-8h14.294a6.708 6.708 0 016.138 4H49v-3a4 4 0 00-4-4H29v-1.882zM33.294 23A2.706 2.706 0 0136 25.706V27h16a4 4 0 014 4v18a4 4 0 01-4 4H19a4 4 0 01-4-4V27a4 4 0 014-4h14.294z"
        clipRule="evenodd"
      />
      <path fill-rule="evenodd" d="M20 35a2 2 0 012-2h27a2 2 0 110 4H22a2 2 0 01-2-2z" clip-rule="evenodd" />
    </svg>
  );
}
