//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: folder.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function FolderIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--folder', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M52 15H35.657A6.01 6.01 0 0030 11H10a6.007 6.007 0 00-6 6v28a8.01 8.01 0 008 8h40a8.01 8.01 0 008-8V23a8.01 8.01 0 00-8-8zm4 30a4.004 4.004 0 01-4 4H12a4.004 4.004 0 01-4-4V17a2.002 2.002 0 012-2h20a2.002 2.002 0 012 2v2h20a4.004 4.004 0 014 4v22zm-6-18a2 2 0 01-2 2H16a2 2 0 110-4h32a2 2 0 012 2z"
        clipRule="evenodd"
      />
    </svg>
  );
}
