//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: folder.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function FolderIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--folder', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M30 12a6 6 0 015.66 4H52a8 8 0 018 8v22a8 8 0 01-8 8H12a8 8 0 01-8-8V18a6 6 0 016-6zm0 4H10a2 2 0 00-2 2v28a4 4 0 004 4h40a4 4 0 004-4V24a4 4 0 00-4-4H32v-2a2 2 0 00-2-2zm18 10a2 2 0 110 4H16a2 2 0 110-4h32z"
      />
    </svg>
  );
}
