//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: games.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function GamesIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--games', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M26 41.998a2 2 0 01-2 2h-2v2a2 2 0 01-4 0v-2h-2a2 2 0 010-4h2v-2a2 2 0 014 0v2h2a2 2 0 012 2zm22-4a2 2 0 100 4 2 2 0 000-4zm-6 4a2 2 0 100 4 2 2 0 000-4zm17.981-.77a15.994 15.994 0 01-25.643 13.517 3.979 3.979 0 00-2.405-.747h-.223a3.44 3.44 0 00-2.048.747A15.997 15.997 0 014.02 41.228c.508-8.639 7.724-15.349 16.377-15.229H32v-2a8.009 8.009 0 018-8 4.004 4.004 0 004-4V8a2 2 0 014 0v4a8.009 8.009 0 01-8 8 4.004 4.004 0 00-4 4v2h7.604c8.653-.12 15.868 6.59 16.377 15.229zm-3.996.188c-.41-6.504-5.865-11.534-12.381-11.417H20.396c-6.516-.117-11.971 4.913-12.382 11.417A11.994 11.994 0 0027.242 51.56a7.366 7.366 0 014.468-1.562h.223a7.996 7.996 0 014.824 1.562 11.996 11.996 0 0019.228-10.144z"
        clipRule="evenodd"
      />
    </svg>
  );
}
