//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: getting-started.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function GettingStartedIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--getting-started', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M31.893 17.643a6.051 6.051 0 106.05 6.05 6.058 6.058 0 00-6.05-6.05zm0 8.068a2.017 2.017 0 110-4.034 2.017 2.017 0 010 4.034zm2.017 24.204v8.068a2.017 2.017 0 01-4.034 0v-8.068a2.017 2.017 0 014.034 0zm6.05 0v4.034a2.017 2.017 0 01-4.033 0v-4.034a2.017 2.017 0 014.034 0zm-12.101 0v4.034a2.017 2.017 0 01-4.034 0v-4.034a2.017 2.017 0 014.034 0zm25.814-11.553a17.703 17.703 0 00-7.28-10.227C46.428 15.426 37.77 7.47 34.34 4.832a4.014 4.014 0 00-4.893 0c-3.429 2.64-12.088 10.594-12.053 23.303a17.702 17.702 0 00-7.28 10.228 4.058 4.058 0 001.03 3.772 4.001 4.001 0 003.684 1.148l5.88-1.176c.239.522.48 1.044.748 1.576a4 4 0 003.596 2.198h13.684a4 4 0 003.596-2.198c.268-.532.509-1.054.748-1.576l5.88 1.176a4 4 0 003.683-1.148 4.059 4.059 0 001.031-3.773zm-39.635.93a12.921 12.921 0 013.78-6.308 34.179 34.179 0 001.361 5.304l-5.141 1.004zm24.697 2.555l-13.679.018C15.42 22.779 27.864 11.14 31.88 8.029c4.042 3.11 16.48 14.744 6.859 33.82l-.003-.002zm5.867-3.549a34.182 34.182 0 001.365-5.313 12.937 12.937 0 013.783 6.343l-5.148-1.03z"
        clipRule="evenodd"
      />
    </svg>
  );
}
