//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: graph.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function GraphIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--graph', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 65 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M58.39 55.833c0 1.197-.97 2.167-2.167 2.167H15.056a8.677 8.677 0 01-8.666-8.667V8.167a2.167 2.167 0 114.333 0v41.166a4.338 4.338 0 004.333 4.334h41.167c1.197 0 2.167.97 2.167 2.166zM17.223 40.667a2.16 2.16 0 001.532-.635l8.218-8.218 5.603 5.603a4.336 4.336 0 006.127 0L51.89 24.23v5.603a2.167 2.167 0 104.334 0v-8.666a4.338 4.338 0 00-4.334-4.334h-8.666a2.167 2.167 0 000 4.334h5.603L35.639 34.353l-5.602-5.603a4.435 4.435 0 00-6.128 0l-8.218 8.218a2.167 2.167 0 001.532 3.699z"
        clipRule="evenodd"
      />
    </svg>
  );
}
