//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: grid-view.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function GridViewIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--grid-view', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M10 8h18a2 2 0 012 2v18a2 2 0 01-2 2H10a2 2 0 01-2-2V10a2 2 0 012-2zm2 4v14h14V12H12zm-2 22h18a2 2 0 012 2v18a2 2 0 01-2 2H10a2 2 0 01-2-2V36a2 2 0 012-2zm2 4v14h14V38H12zM54 8H36a2 2 0 00-2 2v18a2 2 0 002 2h18a2 2 0 002-2V10a2 2 0 00-2-2zM38 26V12h14v14H38zm-2 8h18a2 2 0 012 2v18a2 2 0 01-2 2H36a2 2 0 01-2-2V36a2 2 0 012-2zm2 4v14h14V38H38z"
        clipRule="evenodd"
      />
    </svg>
  );
}
