//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: headphones.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function HeadphonesIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--headphones', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 65"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M54 33.763V31.5c0-12.15-9.85-22-22-22s-22 9.85-22 22v2.263A8.007 8.007 0 004 41.5v6a8.01 8.01 0 008 8h2a4.004 4.004 0 004-4v-14a4.004 4.004 0 00-4-4v-2c0-9.941 8.059-18 18-18s18 8.059 18 18v2a4.004 4.004 0 00-4 4v14a4.004 4.004 0 004 4h2a8.01 8.01 0 008-8v-6a8.007 8.007 0 00-6-7.737zM14.003 51.5H12a4.004 4.004 0 01-4-4v-6a4.004 4.004 0 014-4h2l.003 14zM56 47.5a4.004 4.004 0 01-4 4h-2l-.003-14H52a4.004 4.004 0 014 4v6z"
        clipRule="evenodd"
      />
    </svg>
  );
}
