//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: home-care.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function HomeCareIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--home-care', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path d="M46.001 46a2 2 0 01-2 2v2a8 8 0 01-16 0v-6c-4.41 0-8-3.252-8-7.25V26a2 2 0 012-2h4a2 2 0 010 4h-2v8.75c0 1.792 1.794 3.25 4 3.25h4c2.206 0 4-1.458 4-3.25V28h-2a2 2 0 110-4h4a2 2 0 012 2v10.75c0 3.998-3.588 7.25-8 7.25v6a4 4 0 108 0v-2a2 2 0 110-4h4a2 2 0 012 2zm12.066-16.828L36.244 7.349a6 6 0 00-8.485 0L5.936 29.172A4 4 0 008.764 36h1.237v18a4.004 4.004 0 004 4h10a2 2 0 000-4h-10V32H8.764l21.823-21.823a2.049 2.049 0 012.828 0L55.24 32H50v22h-2a2 2 0 100 4h2a4.004 4.004 0 004-4V36h1.238a4 4 0 002.828-6.828z" />
    </svg>
  );
}
