//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: home.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function HomeIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--home', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M58.795 29.24L36.361 6.808a6.167 6.167 0 00-8.722 0L5.205 29.24a4.112 4.112 0 002.907 7.02h3.328v18.503a4.116 4.116 0 004.112 4.112h32.896a4.116 4.116 0 004.112-4.112V36.26h3.328a4.112 4.112 0 002.907-7.02zm-10.347 2.908v22.616H15.552V32.148h-7.44L30.546 9.714a2.104 2.104 0 012.908 0l22.434 22.434h-7.44zm-18.504 8.224v6.168a4.116 4.116 0 004.112 4.112h6.168a4.116 4.116 0 004.112-4.112v-6.168a4.116 4.116 0 00-4.112-4.112h-6.168a4.116 4.116 0 00-4.112 4.112zm4.112 0h6.168l.003 6.168h-6.171v-6.168z"
        clipRule="evenodd"
      />
    </svg>
  );
}
