//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: hospital.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function HospitalIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--hospital', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path d="M26 18a2 2 0 012-2h2v-2a2 2 0 014 0v2h2a2 2 0 010 4h-2v2a2 2 0 01-4 0v-2h-2a2 2 0 01-2-2zm26-8v44a6.007 6.007 0 01-6 6H18a6.007 6.007 0 01-6-6V10a6.007 6.007 0 016-6h28a6.007 6.007 0 016 6zM30 48h-4v8h4v-8zm8 0h-4v8h4v-8zm10-38a2.003 2.003 0 00-2-2H18a2.003 2.003 0 00-2 2v44a2.003 2.003 0 002 2h4v-8a4.005 4.005 0 014-4h12a4.005 4.005 0 014 4v8h4a2.003 2.003 0 002-2V10zm-8 26H24a2 2 0 000 4h16a2 2 0 000-4zm0-8H24a2 2 0 000 4h16a2 2 0 000-4z" />
    </svg>
  );
}
