//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: image.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function ImageIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--image', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M51.5 8.166h-39a8.677 8.677 0 00-8.667 8.667v30.334a8.677 8.677 0 008.667 8.666h39a8.677 8.677 0 008.666-8.666V16.832A8.677 8.677 0 0051.5 8.167zm4.333 39A4.338 4.338 0 0151.5 51.5h-39a4.338 4.338 0 01-4.334-4.334V16.834A4.338 4.338 0 0112.5 12.5h39a4.338 4.338 0 014.333 4.333v30.334zM20.083 32a7.583 7.583 0 10-7.583-7.584A7.592 7.592 0 0020.083 32zm0-10.834a3.25 3.25 0 110 6.5 3.25 3.25 0 010-6.5zm32.948 13.635a2.166 2.166 0 11-3.063 3.064l-7.135-7.135-13.635 13.635a2.166 2.166 0 01-3.064 0l-4.968-4.968-7.135 7.135a2.167 2.167 0 01-3.063-3.064l7.134-7.135a4.336 4.336 0 016.128 0l3.436 3.436L39.77 27.666a4.336 4.336 0 016.128 0l7.134 7.135z"
        clipRule="evenodd"
      />
    </svg>
  );
}
