//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: info.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function InfoIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--info', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M32 6a26 26 0 0126 26c0 14.36-11.64 26-26 26S6 46.36 6 32 17.64 6 32 6zm0 4c-12.15 0-22 9.85-22 22s9.85 22 22 22a22 22 0 0022-22c0-12.15-9.85-22-22-22zm.89 16c.74 0 1.11.333 1.11 1v15.84a4 4 0 01-.3 1.56 3.2 3.2 0 01-.78 1.18A1.38 1.38 0 0132 46c-.513 0-1.03-.38-1.55-1.14a2.25 2.25 0 01-.48-1.18V27.86c0-.44.31-.86.92-1.26a3.531 3.531 0 012-.6zm.11-8c.827 0 1.233.38 1.22 1.14a4.41 4.41 0 01-.34 1.73 3.59 3.59 0 01-.88 1.31 1.58 1.58 0 01-1.01.48c-.52 0-1.06-.41-1.62-1.23a2.81 2.81 0 01-.57-1.35 1.81 1.81 0 011-1.42A4 4 0 0133 18z"
      />
    </svg>
  );
}
