//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: job-search.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function JobSearchIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--job-search', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path d="M57.586 48.758l-6.794-6.794a24.032 24.032 0 10-8.828 8.828l6.622 6.622a6.25 6.25 0 008.828 0l.172-.172a6 6 0 000-8.484zM10 30a20 20 0 1120 20 20.022 20.022 0 01-20-20zm44.758 24.414l-.172.172a2.244 2.244 0 01-3.172 0l-6.112-6.112a24.22 24.22 0 003.172-3.172l6.284 6.284a2.002 2.002 0 010 2.828zM37.536 26.658a8 8 0 10-15.073 0A10.008 10.008 0 0016 36a6.006 6.006 0 006 6h16a6.006 6.006 0 006-6 10.008 10.008 0 00-6.464-9.342zM30 20a4 4 0 110 8 4 4 0 010-8zm8 18H22a2.003 2.003 0 01-2-2 6.008 6.008 0 014.85-5.887 7.97 7.97 0 0010.3 0A6.007 6.007 0 0140 36a2.002 2.002 0 01-2 2z" />
    </svg>
  );
}
