//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: kontantkort.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function KontantkortIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--kontantkort', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M54 12a6 6 0 0 1 6 6v28a6 6 0 0 1-6 6H10a6 6 0 0 1-6-6V18a6 6 0 0 1 6-6zm0 4H10a2 2 0 0 0-2 2v28a2 2 0 0 0 2 2h44a2 2 0 0 0 2-2V18a2 2 0 0 0-2-2zM28 26.61a3.33 3.33 0 0 1 1.29 1.29 3.61 3.61 0 0 1 .46 1.83 3.17 3.17 0 0 1-.5 1.7 4 4 0 0 1-1.4 1.33l1.85 2.64a.66.66 0 0 1 .13.4 2 2 0 0 1-.33 1.09c-.22.33-.45.5-.69.5a.92.92 0 0 1-.7-.48l-2.52-3.59h-1.42v2.33a2.19 2.19 0 0 1-.35 1.2 1 1 0 0 1-.77.54c-.28 0-.55-.21-.83-.62a1.54 1.54 0 0 1-.27-.66v-8.94a.89.89 0 0 1 .5-.71 2 2 0 0 1 1.09-.33H26a3.91 3.91 0 0 1 2 .48zM19.81 26c.43 0 .64.2.64.58a2.36 2.36 0 0 1-.18.89 2 2 0 0 1-.51.73l-3.33 3.08 4.1 4a.52.52 0 0 1 .14.4 2.11 2.11 0 0 1-.31 1.13.85.85 0 0 1-.69.51A1 1 0 0 1 19 37l-4.44-4.47v3.12a2.11 2.11 0 0 1-.35 1.2 1 1 0 0 1-.76.54c-.28 0-.56-.21-.83-.62a1.45 1.45 0 0 1-.27-.66v-9a.89.89 0 0 1 .5-.71 1.94 1.94 0 0 1 1.09-.4c.42 0 .62.2.62.58v3.56l3.88-3.59a1.83 1.83 0 0 1 .64-.4 1.91 1.91 0 0 1 .73-.15zm6.1 2.24h-1.74v3.08h1.74a1.61 1.61 0 0 0 1.14-.45 1.42 1.42 0 0 0 .47-1.08 1.45 1.45 0 0 0-.46-1.11 1.6 1.6 0 0 0-1.15-.44z"
      />
    </svg>
  );
}
