//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: laptop.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function LaptopIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--laptop', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M58.34 46.21L56 41.53V16a4 4 0 00-4-4H12a4 4 0 00-4 4v25.53l-2.34 4.68A4 4 0 009.24 52h45.52a4 4 0 003.58-5.79zM12 16h40v24H12V16zM9.24 48l2-4h41.52l2 4H9.24z"
      />
    </svg>
  );
}
