//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: laptop.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function LaptopIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--laptop', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M59.558 46.79l-2.45-4.9V15.186A4.189 4.189 0 0052.924 11H11.076a4.189 4.189 0 00-4.185 4.185V41.89l-2.45 4.9a4.185 4.185 0 003.743 6.056h47.63a4.185 4.185 0 003.743-6.056zM11.077 15.186h41.847v25.108H11.077V15.185zM8.185 48.662l2.092-4.184h43.445l2.092 4.184H8.184z"
        clipRule="evenodd"
      />
    </svg>
  );
}
