//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: layers.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function LayersIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--layers', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path d="M54 30h-6V20a4.005 4.005 0 00-4-4H34v-6a4.004 4.004 0 00-4-4H10a4.004 4.004 0 00-4 4v20a4.004 4.004 0 004 4h6v10a4.005 4.005 0 004 4h10v6a4.005 4.005 0 004 4h20a4.005 4.005 0 004-4V34a4.005 4.005 0 00-4-4zm-44 0V10h20v6H20a4.005 4.005 0 00-4 4v10h-6zm10-10h24l.001 11.985L44 32l.001.015L44.003 44H20V20zm34 34H34v-6h10a4.005 4.005 0 004-4V34h6v20z" />
    </svg>
  );
}
