//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: letter.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function LetterIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--letter', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path d="M46 26a2 2 0 01-2 2H24a2 2 0 010-4h20a2 2 0 012 2zm-22-8h20a2 2 0 000-4H24a2 2 0 000 4zm20 16H24a2 2 0 000 4h20a2 2 0 000-4zM54 8v44a8.01 8.01 0 01-8 8H14a8.01 8.01 0 01-8-8v-2a4.004 4.004 0 014-4h4V12a8.01 8.01 0 018-8h28a4.004 4.004 0 014 4zM14 56h25.083A7.94 7.94 0 0138 52v-2H10v2a4.004 4.004 0 004 4zM50 8H22a4.004 4.004 0 00-4 4v34h20a4.004 4.004 0 014 4v2a4 4 0 108 0V8z" />
    </svg>
  );
}
