//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: link.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function LinkIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--link', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M37.383 27.972c4.572 4.583 4.572 12.001 0 16.584L25.368 56.57c-4.583 4.572-12.001 4.572-16.584 0L7.43 55.216c-4.572-4.583-4.572-12.001 0-16.584l8.14-8.14a2.132 2.132 0 013.014 3.015l-8.14 8.14a7.471 7.471 0 000 10.554l1.356 1.355a7.473 7.473 0 0010.554 0l12.015-12.015a7.471 7.471 0 000-10.554l-1.743-1.744a2.132 2.132 0 113.014-3.014l1.744 1.743zM56.571 8.784L55.216 7.43c-4.583-4.572-12.001-4.572-16.584 0L26.617 19.444c-4.572 4.583-4.572 12.001 0 16.584l1.744 1.743a2.132 2.132 0 103.014-3.014l-1.743-1.744a7.471 7.471 0 010-10.554l12.015-12.015a7.473 7.473 0 0110.554 0l1.355 1.355a7.471 7.471 0 010 10.554l-8.14 8.14a2.132 2.132 0 003.015 3.014l8.14-8.14c4.572-4.582 4.572-12 0-16.583z"
        clipRule="evenodd"
      />
    </svg>
  );
}
