//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: link.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function LinkIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--link', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M24.33 28.89c1.418 0 2.824.272 4.14.8l.2.08-3.21 3.21a7.08 7.08 0 00-1.13-.09 7 7 0 00-5 2l-5.56 5.56a7 7 0 109.9 9.9l5.56-5.56a7 7 0 001.92-6.28l3.17-3.17a11 11 0 01-2.21 12.36l-5.56 5.56a11 11 0 01-7.78 3.22 11.21 11.21 0 01-4.14-.8 11 11 0 01-3.64-18l5.57-5.57a10.93 10.93 0 017.77-3.22zm14.092-4.4a2 2 0 01.648 3.27L27.76 39.07a2 2 0 11-2.83-2.83l11.31-11.31a2 2 0 012.182-.44zM45.15 7.71c1.418 0 2.824.272 4.14.8a11 11 0 013.64 2.42 11 11 0 010 15.6l-5.44 5.44a11 11 0 01-7.78 3.22 11.13 11.13 0 01-4.14-.8l-.18-.08 3.21-3.21a7 7 0 006.06-2l5.39-5.44a7 7 0 00-9.9-9.9l-5.44 5.44a7 7 0 00-2 4.95 6.72 6.72 0 00.13 1.35l-3.17 3.17a11 11 0 012.26-12.3l5.44-5.44a11 11 0 017.78-3.22z"
      />
    </svg>
  );
}
