//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: lock-unlocked.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function LockUnlockedIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--lock-unlocked', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M28.14 5.3a14.08 14.08 0 0110.45 2.27 13.41 13.41 0 015.68 8.85l.73 4.24a2.029 2.029 0 01-4 .68l-.72-4.24a9.44 9.44 0 00-4-6.24 10.12 10.12 0 00-7.47-1.62c-5.364.831-9.047 5.842-8.24 11.21L21.69 27H46a6 6 0 012.34.47l.227.102A6 6 0 0152 33v6a19.81 19.81 0 01-.49 4.38c-2.24 9.936-11.59 16.6-21.714 15.478C19.673 57.736 12.01 49.185 12 39v-6a6 6 0 013.63-5.53l.274-.108a5.79 5.79 0 011.726-.342l-1-5.9C15.45 13.575 20.598 6.498 28.14 5.3zM46 31H18a2 2 0 00-.79.2h-.1A2 2 0 0016 33v6c-.001 1.174.13 2.345.39 3.49 1.788 7.95 9.266 13.287 17.366 12.392C41.856 53.988 47.989 47.15 48 39v-6a2 2 0 00-1.12-1.84h-.09A2 2 0 0046 31zm-13.303 4.057A4 4 0 0134 42.46V49a2 2 0 11-4 0v-6.54a4 4 0 012.697-7.403z"
      />
    </svg>
  );
}
