//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: lock-open.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function LockOpenIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--lock-open', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M46.33 24.744H23.52a10.364 10.364 0 1117.263-11.403 2.074 2.074 0 003.59-2.08c-3.893-6.747-12.42-9.217-19.315-5.594-6.896 3.622-9.702 12.043-6.356 19.077h-1.407A8.305 8.305 0 009 33.04v18.665A8.305 8.305 0 0017.296 60H46.33a8.305 8.305 0 008.295-8.295V33.04a8.305 8.305 0 00-8.295-8.296zm4.148 26.96a4.152 4.152 0 01-4.148 4.148H17.296a4.152 4.152 0 01-4.148-4.147V33.04a4.152 4.152 0 014.148-4.148H46.33a4.152 4.152 0 014.148 4.148v18.665zM33.886 41.336v6.222a2.074 2.074 0 11-4.147 0v-6.222a2.074 2.074 0 014.147 0z"
        clipRule="evenodd"
      />
    </svg>
  );
}
