//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: login.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function LoginIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--login', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M31.998 8a2 2 0 100 4h18a4 4 0 014 4v32a4 4 0 01-4 4h-18a2 2 0 100 4h18a8 8 0 008-8V16a8 8 0 00-8-8zm-3.303 10.685a2 2 0 00-.105 2.715l8.58 8.6H10a2 2 0 100 4h27.17l-8.58 8.59a2 2 0 102.82 2.82l12-12a1.79 1.79 0 00.25-.3.55.55 0 00.08-.15c.043-.063.08-.13.11-.2l.06-.2a.84.84 0 00.05-.17 2 2 0 000-.78.84.84 0 00-.05-.17l-.06-.2a1.28 1.28 0 00-.11-.2.55.55 0 00-.08-.15 1.79 1.79 0 00-.25-.31l-12-12a2 2 0 00-2.715.105z"
      />
    </svg>
  );
}
