//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: login.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function LoginIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--login', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M37.602 34.167H8.168a2.167 2.167 0 010-4.334h29.435l-9.3-9.301a2.167 2.167 0 013.063-3.064l12.999 12.999c.101.101.192.213.272.332.034.051.057.107.087.16.085.131.146.276.178.429.02.063.043.123.056.188.056.28.056.568 0 .848-.013.065-.037.125-.056.188a1.269 1.269 0 01-.178.428c-.03.054-.053.11-.087.161-.08.12-.17.23-.272.332l-13 12.999a2.167 2.167 0 01-3.064-3.064l9.302-9.301zM49.334 6h-26a2.167 2.167 0 000 4.333h26a4.338 4.338 0 014.334 4.334v34.666a4.338 4.338 0 01-4.334 4.334h-26a2.167 2.167 0 100 4.333h26A8.677 8.677 0 0058 49.333V14.667A8.677 8.677 0 0049.333 6z"
        clipRule="evenodd"
      />
    </svg>
  );
}
