//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: logout.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function LogoutIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--logout', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M34 8a2 2 0 110 4H16a4 4 0 00-4 4v32a4 4 0 004 4h18a2 2 0 110 4H16a8 8 0 01-8-8V16a8 8 0 018-8zm8.695 10.685a2 2 0 012.715-.105l12 12c.095.094.178.198.25.31a.55.55 0 01.08.15c.043.063.08.13.11.2l.06.2a.84.84 0 01.05.17 2 2 0 010 .78.84.84 0 01-.05.17l-.06.2a1.28 1.28 0 01-.11.2.55.55 0 01-.08.15 1.79 1.79 0 01-.25.3l-12 12a2 2 0 11-2.82-2.82L51.17 34H24a2 2 0 110-4h27.17l-8.58-8.6a2 2 0 01.105-2.715z"
      />
    </svg>
  );
}
