//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: map.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function MapIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--map', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M32 4c11.355 0 20.56 9.205 20.56 20.56 0 15.44-18.36 34.06-19.14 34.85a2.002 2.002 0 01-2.84 0C29.8 58.62 11.44 40 11.44 24.56 11.44 13.205 20.645 4 32 4zm0 4c-9.141.011-16.549 7.419-16.56 16.56C15.44 36 27.75 50.45 32 55.08 36.25 50.45 48.56 36 48.56 24.56 48.549 15.419 41.141 8.011 32 8zm0 6a10 10 0 0110 10c0 5.523-4.477 10-10 10s-10-4.477-10-10 4.477-10 10-10zm0 4a6 6 0 100 12 6 6 0 000-12z"
      />
    </svg>
  );
}
