//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: map.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function MapIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--map', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M31.916 14.458c-5.776 0-10.458 4.682-10.458 10.458 0 5.775 4.682 10.457 10.458 10.457 5.775 0 10.457-4.682 10.457-10.457-.006-5.773-4.685-10.452-10.457-10.458zm0 16.732a6.275 6.275 0 116.274-6.274 6.281 6.281 0 01-6.274 6.274zm0-27.19C20.369 4.013 11.013 13.37 11 24.916c0 13.06 14.254 29.391 18.625 34.087a3.141 3.141 0 002.29.997h.003a3.141 3.141 0 002.29-.999c4.37-4.694 18.623-21.025 18.623-34.085C52.818 13.37 43.461 4.013 31.915 4zm0 51.312c-4.11-4.54-16.733-19.387-16.733-30.396 0-9.242 7.491-16.733 16.733-16.733 9.24 0 16.732 7.491 16.732 16.733 0 11.009-12.624 25.857-16.733 30.396z"
        clipRule="evenodd"
      />
    </svg>
  );
}
