//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: measuring-health.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function MeasuringHealthIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--measuring-health', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path d="M50 32a5.996 5.996 0 00-2 11.65V46a10 10 0 01-20 0V31.882A18.022 18.022 0 0044 14v-4a4.004 4.004 0 00-4-4h-2.555a4 4 0 100 4H40v4a14 14 0 01-28 0v-4h2.555a4 4 0 100-4H12a4.004 4.004 0 00-4 4v4a18.022 18.022 0 0016 17.882V46a14 14 0 0028 0v-2.35A5.996 5.996 0 0050 32zm0 8a2 2 0 110-4 2 2 0 010 4z" />
    </svg>
  );
}
