//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: media-content.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function MediaContentIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--media-content', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M20 4a8 8 0 00-8 8v2a2 2 0 104 0v-2a4 4 0 014-4h17v8a4 4 0 004 4h7v3a2 2 0 104 0v-4.724a4 4 0 00-1.046-2.697L41.572 5.303A4 4 0 0038.618 4H20zm25.922 12L41 10.609V16h4.922z"
        clipRule="evenodd"
      />
      <path d="M52 41.5a2 2 0 10-4 0V52a4 4 0 01-4 4H16V46a2 2 0 10-4 0v10a4 4 0 004 4h28a8 8 0 008-8V41.5z" />
      <path
        fill-rule="evenodd"
        d="M19.5 38a8.5 8.5 0 100-17 8.5 8.5 0 000 17zm0 4C26.404 42 32 36.404 32 29.5S26.404 17 19.5 17 7 22.596 7 29.5 12.596 42 19.5 42zm24.597-17.793a2 2 0 00-2.912.379A1.994 1.994 0 0040.6 26v14.053c-1.486-.803-3.265-1.195-5.135-1.024-4.675.426-8.153 4.203-7.767 8.437.386 4.234 4.489 7.322 9.164 6.896 4.675-.426 8.152-4.204 7.766-8.438a7.084 7.084 0 00-.068-.526c.026-.129.04-.262.04-.398V29.833l5.863 4.886a2 2 0 102.56-3.073l-8.926-7.439zm-7.598 26.171c2.855-.26 4.298-2.42 4.146-4.091-.153-1.672-1.962-3.535-4.817-3.275-2.856.26-4.299 2.42-4.146 4.091.152 1.672 1.961 3.535 4.817 3.275z"
        clip-rule="evenodd"
      />
    </svg>
  );
}
