//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: menu.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function MenuIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--menu', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M50 44a2 2 0 110 4H14a2 2 0 110-4zm0-14a2 2 0 110 4H14a2 2 0 110-4zm0-14a2 2 0 110 4H14a2 2 0 110-4z"
      />
    </svg>
  );
}
