//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: microphone.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function MicrophoneIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--microphone', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M32.131 46c6.624-.008 11.993-5.376 12-12V16c0-6.627-5.372-12-12-12-6.627 0-12 5.373-12 12v18c.008 6.624 5.376 11.992 12 12zm0-38a8.01 8.01 0 018 8v18a8 8 0 11-16 0v-4h6a2 2 0 100-4h-6v-4h6a2 2 0 000-4h-6v-2a8.01 8.01 0 018-8zm17.92 34.89a19.874 19.874 0 01-15.92 11V58a2 2 0 01-4 0v-4.11a19.874 19.874 0 01-15.92-11 2 2 0 113.583-1.78 16.007 16.007 0 0028.675 0 2 2 0 113.582 1.78z"
        clipRule="evenodd"
      />
    </svg>
  );
}
