//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: mms.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function MmsIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--mms', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path d="M47.85 21.49a2 2 0 11-4 0 2 2 0 014 0z" />
      <path
        fillRule="evenodd"
        d="M50.07 10H13.93a9.75 9.75 0 00-9.73 9.74v16.78a9.76 9.76 0 009.73 9.74h9.61V52a2 2 0 001.24 1.85 2 2 0 002.22-.44l4.93-4.92 2.22-2.23h16c2.13 0 4.2-.703 5.89-2a10.001 10.001 0 002.62-3 9.67 9.67 0 001.22-4.72v-16.8A9.75 9.75 0 0050.07 10zM33.28 42.26a2 2 0 00-.92.23c-.178.09-.34.208-.48.35l-4.34 4.33v-2.91a2 2 0 00-2-2H13.93a5.73 5.73 0 01-5.72-5.44l10.22-10.23a2 2 0 012.84 0l10.25 10.25L37 42.26h-3.72zm9.31 0h7.48a5.68 5.68 0 003.01-.86l-8.81-8.81a2 2 0 00-2.84 0l-4.25 4.26 5.41 5.41zm13.21-5.74a5.534 5.534 0 01-.26 1.69l-8.45-8.45a6 6 0 00-8.49 0L34.35 34 24.09 23.76a6 6 0 00-8.49 0l-7.4 7.41V19.74A5.74 5.74 0 0113.93 14h36.14a5.75 5.75 0 015.73 5.74v16.78z"
        clipRule="evenodd"
      />
    </svg>
  );
}
