//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: mms.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function MmsIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--mms', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M50.07 10a9.75 9.75 0 0 1 9.81 9.74v16.8a9.67 9.67 0 0 1-1.22 4.72 10 10 0 0 1-2.62 3 9.68 9.68 0 0 1-5.89 2h-16l-2.22 2.23L27 53.41a2 2 0 0 1-2.22.44A2 2 0 0 1 23.54 52v-5.74h-9.61a9.76 9.76 0 0 1-9.73-9.74V19.74c.005-5.373 4.357-9.729 9.73-9.74zM19.85 25.998a2 2 0 0 0-1.42.592L8.21 36.82a5.73 5.73 0 0 0 5.72 5.44h11.61a2 2 0 0 1 2 2v2.91l4.34-4.33c.14-.142.302-.26.48-.35a2 2 0 0 1 .92-.23H37l-5.48-5.42-10.25-10.25a2 2 0 0 0-1.42-.592zm23 6a2 2 0 0 0-1.42.592l-4.25 4.26 5.41 5.41h7.48a5.68 5.68 0 0 0 3.01-.86l-8.81-8.81a2 2 0 0 0-1.42-.592zM50.07 14H13.93a5.74 5.74 0 0 0-5.73 5.74v11.43l7.4-7.41a6 6 0 0 1 8.49 0L34.35 34l4.25-4.24a6 6 0 0 1 8.49 0l8.45 8.45a5.53 5.53 0 0 0 .26-1.69V19.74A5.75 5.75 0 0 0 50.07 14zm-4.22 5.49a2 2 0 1 1 0 4 2 2 0 0 1 0-4z"
      />
    </svg>
  );
}
