//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: mobile.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function MobileIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--mobile', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M40 4a8 8 0 0 1 8 8v40a8 8 0 0 1-8 8H24a8 8 0 0 1-8-8V12a8 8 0 0 1 8-8zm4 44H20v4a4 4 0 0 0 4 4h16a4 4 0 0 0 4-4v-4zm-12 2a2 2 0 1 1 0 4 2 2 0 0 1 0-4zm8-42H24a4 4 0 0 0-4 4v32h24V12a4 4 0 0 0-4-4z"
      />
    </svg>
  );
}
