//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: mobile-broadband.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function MobileBroadbandIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--mobile-broadband', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path d="M32 4H16a8.01 8.01 0 00-8 8v40a8.01 8.01 0 008 8h16a8.01 8.01 0 008-8V12a8.01 8.01 0 00-8-8zm-20 8a4.004 4.004 0 014-4h16a4.004 4.004 0 014 4v32H12V12zm24 40a4.005 4.005 0 01-4 4H16a4.005 4.005 0 01-4-4v-4h24v4zm-14 0a2 2 0 114 0 2 2 0 01-4 0zm30-24a9.943 9.943 0 01-2.928 7.071 2.003 2.003 0 01-2.829.001 2.003 2.003 0 01-.001-2.829 6 6 0 000-8.486 2 2 0 112.83-2.828A9.942 9.942 0 0152 28zm8 0a17.88 17.88 0 01-5.272 12.728 2 2 0 01-2.829-2.829 14 14 0 000-19.798 2 2 0 112.829-2.829A17.88 17.88 0 0160 28z" />
    </svg>
  );
}
