//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: money-euro.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function MoneyEuroIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--money-euro', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M21.11 14.05A21 21 0 0160 25a21.001 21.001 0 01-10 17.89 21 21 0 01-7 7A21.09 21.09 0 0125 60a21 21 0 01-10.99-38.95 21 21 0 017-7zM11.21 29A17 17 0 0025 56a17.06 17.06 0 009.91-3.21A21.67 21.67 0 0132 53c-11.598 0-21-9.402-21-21a22.29 22.29 0 01.21-3zm7.03-7A17 17 0 0032 49a16.9 16.9 0 0010-3.24A20.84 20.84 0 0118.24 22zM39 8c-9.389 0-17 7.611-17 17s7.611 17 17 17a17 17 0 0017-17c0-9.389-7.611-17-17-17zm1.56 5.47A9.38 9.38 0 0145.72 15a1 1 0 01.47.85 3.5 3.5 0 01-1 2.5 1.28 1.28 0 01-.88.41 1.37 1.37 0 01-.6-.19 6.58 6.58 0 00-3.22-1A5.45 5.45 0 0035.4 21H43c.53 0 .78.25.78.72 0 1.11-.75 2.28-1.42 2.28h-7.78a8.55 8.55 0 000 1.06 6.54 6.54 0 000 .94h7.35c.54 0 .79.25.79.72 0 1.11-.72 2.28-1.42 2.28h-6a5.21 5.21 0 005.09 3.53 10.54 10.54 0 002.9-.56 7.24 7.24 0 011.71-.35c.73 0 1.11.35 1.11 1a3.47 3.47 0 01-1.45 2.94 9.7 9.7 0 01-4.55 1c-4.67 0-8.17-2.81-9.53-7.58h-1.27a.68.68 0 01-.45-.19 2.32 2.32 0 01-1-1.48c0-.64 1.08-1.33 2.06-1.33h.28a4.92 4.92 0 010-.94 6.42 6.42 0 010-1.06h-.47a.68.68 0 01-.45-.19 2.32 2.32 0 01-1-1.48c0-.64 1.08-1.33 2.05-1.33h.45c1.64-4.64 5.4-7.51 9.78-7.51z"
      />
    </svg>
  );
}
