//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: more-low.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function MoreLowIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--more-low', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M43 42c0 2.75 2.25 5 5 5s5-2.25 5-5-2.25-5-5-5-5 2.25-5 5zm-6 0c0-2.75-2.25-5-5-5s-5 2.25-5 5 2.25 5 5 5 5-2.25 5-5zm-16 0c0-2.75-2.25-5-5-5s-5 2.25-5 5 2.25 5 5 5 5-2.25 5-5z"
      />
    </svg>
  );
}
