//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: music.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function MusicIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--music', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M52.491 10.872a3.986 3.986 0 00-3.391-.768l-22 5.077a3.981 3.981 0 00-3.1 3.897V38.84a9.755 9.755 0 00-5-1.353c-4.963 0-9 3.59-9 8 0 4.412 4.037 8 9 8s9-3.588 9-8V19.08l22-5.078v18.84a9.755 9.755 0 00-5-1.354c-4.963 0-9 3.59-9 8 0 4.412 4.037 8 9 8s9-3.588 9-8V14.001a3.977 3.977 0 00-1.509-3.129zM19 49.487c-2.757 0-5-1.794-5-4s2.243-4 5-4 5 1.794 5 4-2.243 4-5 4zm21-10c0 2.206 2.243 4 5 4s5-1.794 5-4-2.243-4-5-4-5 1.794-5 4z"
        clipRule="evenodd"
      />
    </svg>
  );
}
