//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: mute.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function MuteIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--mute', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M51.428 11.676l1.749-2.137a2.167 2.167 0 10-3.354-2.744l-13.49 16.487v-9.885a4.333 4.333 0 00-7.397-3.064L18.103 21.167h-3.436A8.677 8.677 0 006 29.833v4.334a8.677 8.677 0 008.667 8.666h3.436l1.228 1.23-8.508 10.398a2.167 2.167 0 103.354 2.745l8.234-10.064 6.525 6.525a4.333 4.333 0 007.397-3.064V30.125l6.276-7.67A19.239 19.239 0 0145 32c.118 4.19-1.23 8.29-3.813 11.59a2.167 2.167 0 003.293 2.82A22.356 22.356 0 0049.333 32a23.054 23.054 0 00-3.832-13.079l3.11-3.803A28.806 28.806 0 0153.668 32c0 7.059-2.18 13.652-5.98 18.09a2.167 2.167 0 003.293 2.82C55.44 47.696 58 40.075 58 32c0-7.79-2.4-15.134-6.572-20.324zM19.898 38.5h-5.231a4.338 4.338 0 01-4.334-4.333v-4.334a4.338 4.338 0 014.334-4.333h5.23L32 13.397v15.181l-9.911 12.114-2.192-2.192zM32 50.603l-6.832-6.831L32 35.422v15.181z"
        clipRule="evenodd"
      />
    </svg>
  );
}
