//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: new-contact.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function NewContactIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--new-contact', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path d="M49.86 31.712a16.11 16.11 0 00-11.413-10.547 13 13 0 10-23.557.006A16.015 16.015 0 002.667 36.702v4a8.01 8.01 0 008 8h20.59a13.997 13.997 0 1018.603-16.99zM26.667 6.702a9 9 0 11-9 9 9.01 9.01 0 019-9zm-16 38a4.004 4.004 0 01-4-4v-4a12.015 12.015 0 0110.707-11.928 12.959 12.959 0 0018.58.007 12.106 12.106 0 019.11 5.941c-.133-.004-.263-.02-.397-.02a14.016 14.016 0 00-14 14h-20zm34 10a10 10 0 1110-10 10.012 10.012 0 01-10 10zm7-10a2 2 0 01-2 2h-3v3a2 2 0 01-4 0v-3h-3a2 2 0 110-4h3v-3a2 2 0 014 0v3h3a2 2 0 012 2z" />
    </svg>
  );
}
