//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: news.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function NewsIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--news', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path d="M36 36a2 2 0 01-2 2H18a2 2 0 010-4h16a2 2 0 012 2zm-2 6H18a2 2 0 000 4h16a2 2 0 000-4zm2-24v10a2 2 0 01-2 2H18a2 2 0 01-2-2V18a2 2 0 012-2h16a2 2 0 012 2zm-4 2H20v6h12v-6zm24 2v28a8.01 8.01 0 01-8 8H16a8.01 8.01 0 01-8-8V10a4.004 4.004 0 014-4h28a4.004 4.004 0 014 4v8h8a4.005 4.005 0 014 4zM41.083 54A7.94 7.94 0 0140 50V10H12v40a4.005 4.005 0 004 4h25.083zM52 22h-8v28a4 4 0 108 0V22z" />
    </svg>
  );
}
