//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: offering.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function OfferingIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--offering', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path d="M58.299 33.47a6.422 6.422 0 00-8.3-.613V26a4.004 4.004 0 004-4v-6a4.005 4.005 0 00-4-4h-2a7.989 7.989 0 00-14-5.274A7.99 7.99 0 0020 12h-2a4.004 4.004 0 00-4 4v6a4.004 4.004 0 004 4v8.09a3.97 3.97 0 00-2 1.082l-10 10a4.004 4.004 0 000 5.656L13.173 58a4.003 4.003 0 005.656 0l2-2h22.344A3.972 3.972 0 0046 54.828L58.299 42.53a6.412 6.412 0 000-9.058zm-12.3 2.753l-2.282 1.957A6.01 6.01 0 0038 34h-2v-8h10v10.223zM50 16l.004 6H36v-6h14zM40 8a4.004 4.004 0 014 4h-8a4.004 4.004 0 014-4zM28 8a4.004 4.004 0 014 4h-8a4.004 4.004 0 014-4zm-10 8h14v6H18v-6zm14 10v8H22v-8h10zm23.472 13.701L43.17 52h-24L16 55.172 8.828 48l10-10H38a2 2 0 01.527 3.93c-.246.047-.496.07-.747.07H28a2 2 0 100 4h10a5.97 5.97 0 001.431-.173 8.01 8.01 0 003.556-1.753l9.217-7.9A2.405 2.405 0 0155.47 39.7z" />
    </svg>
  );
}
