//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: org-chart.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function OrgChartIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--org-chart', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M55.692 40.615h-6.461v-6.461a4.312 4.312 0 00-4.308-4.308h-10.77v-6.461h15.078a4.312 4.312 0 004.307-4.308V8.307A4.312 4.312 0 0049.231 4H14.769a4.312 4.312 0 00-4.308 4.308v10.769a4.312 4.312 0 004.308 4.308h15.077v6.461h-10.77a4.312 4.312 0 00-4.307 4.308v6.461H8.307A4.312 4.312 0 004 44.923v10.77A4.312 4.312 0 008.308 60h15.077a4.312 4.312 0 004.307-4.308V44.923a4.312 4.312 0 00-4.307-4.308h-4.309v-6.461h25.847v6.461h-4.308a4.312 4.312 0 00-4.307 4.308v10.77A4.312 4.312 0 0040.615 60h15.077A4.312 4.312 0 0060 55.692V44.923a4.312 4.312 0 00-4.308-4.308zM14.77 8.308h34.462v10.769H14.769V8.307zm8.616 47.384H8.308V44.923h15.077v10.77zm32.308 0H40.615V44.923h15.078v10.77z"
        clipRule="evenodd"
      />
    </svg>
  );
}
