//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: password-visible.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function PasswordVisibleIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--password-visible', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path d="M32 20a12 12 0 1012 12 12.013 12.013 0 00-12-12zm0 20a8 8 0 118-8 8.01 8.01 0 01-8 8zm6.25-8a2 2 0 01-4 0 2.003 2.003 0 00-2-2 2 2 0 010-4 6.006 6.006 0 016 6zm10.878-12.164C43.54 16.018 37.618 14 32 14 16.919 14 4 28.582 4 32c0 3.418 12.919 18 28 18s28-14.582 28-18c0-2.477-5.182-8.275-10.872-12.164zM32 46C19.852 46 9.531 34.912 8.092 32 9.532 29.088 19.852 18 32 18c6.075 0 11.44 2.794 14.871 5.139a32.513 32.513 0 019.032 8.873C54.441 34.942 44.133 46 32 46z" />
    </svg>
  );
}
