//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: password-invisible.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function PasswordInvisibleIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--password-invisible', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path d="M49.128 19.836c-.432-.295-.868-.559-1.303-.832l5.59-5.59a2 2 0 00-2.83-2.828l-6.4 6.401A28.26 28.26 0 0032 14C16.919 14 4 28.582 4 32c0 2.104 4.898 8.434 12.178 12.993l-5.592 5.593a2 2 0 102.828 2.828l6.405-6.405A28.19 28.19 0 0032 50c15.081 0 28-14.582 28-18 0-2.477-5.182-8.275-10.872-12.164zM8.092 32C9.532 29.088 19.852 18 32 18a23.55 23.55 0 019.174 1.998l-2.232 2.232A11.98 11.98 0 0022.23 38.942L19.073 42.1C13.17 38.609 8.97 33.779 8.092 32zM40 32a7.984 7.984 0 01-12.056 6.884l6.378-6.378A1.996 1.996 0 0038.25 32c0-.957-.231-1.9-.673-2.75l1.307-1.306A7.94 7.94 0 0140 32zm-16 0a7.985 7.985 0 0112.056-6.884l-1.394 1.394A5.96 5.96 0 0032.25 26a1.995 1.995 0 00-.87 3.793l-6.264 6.263A7.939 7.939 0 0124 32zm8 14a23.5 23.5 0 01-9.175-1.997l2.233-2.233A11.98 11.98 0 0041.77 25.058l3.156-3.156c.7.415 1.353.832 1.945 1.237a32.513 32.513 0 019.032 8.873C54.441 34.942 44.133 46 32 46z" />
    </svg>
  );
}
