//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: pebble.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function PebbleIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--pebble', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M59 17.517C59 7.476 51.703 4 43.638 4 26.739 4 6 15.2 6 29.49 6 40.69 20.978 60 32.116 60 42.87 60 59 42.234 59 17.517z"
        clipRule="evenodd"
      />
    </svg>
  );
}
