//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: people-hub.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function PeopleHubIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--people-hub', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path d="M53.998 40a5.981 5.981 0 00-4.293 1.817l-4.638-2.141a17.899 17.899 0 00-5.903-19.768l2.533-4.054a6.016 6.016 0 10-3.389-2.122l-2.536 4.058a17.966 17.966 0 00-21.208 28.148l-2.27 2.52a6.002 6.002 0 102.974 2.677l2.266-2.518a17.92 17.92 0 0025.845-5.315l4.647 2.144A6 6 0 1053.998 40zm-11-32a2 2 0 110 4 2 2 0 010-4zm-15 12a13.998 13.998 0 0112.89 19.462c-.078-.153-.142-.314-.229-.463a10.019 10.019 0 00-5.127-4.333 7.999 7.999 0 10-15.07-.008 10.043 10.043 0 00-5.358 4.794A14 14 0 0127.998 20zm0 16a4 4 0 110-8 4 4 0 010 8zm-18 20a2 2 0 110-4 2 2 0 010 4zm18-8a13.953 13.953 0 01-9.99-4.21 6.005 6.005 0 014.841-5.677 7.97 7.97 0 0010.288.01 5.94 5.94 0 014.848 5.671A13.952 13.952 0 0127.998 48zm26 0a2 2 0 110-4.001 2 2 0 010 4.001z" />
    </svg>
  );
}
