//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: pet-dog.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function PetDogIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--pet-dog', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path d="M56.877 17.517l-9.705-3.235-7.866-9.44A3 3 0 0034 6.762v13.681a4.018 4.018 0 01-3.693 3.99l-18.995 1.461-3.455-8.637a2 2 0 00-3.714 1.486L8 28.387v12.785L5.172 44A3.974 3.974 0 004 46.828V52a6.007 6.007 0 006 6h2a6.006 6.006 0 006-6v-1.04L26.7 44h5.79l3.173 11.1A4.016 4.016 0 0039.51 58H42a6.006 6.006 0 006-6v-5.845c0-3.247.478-6.477 1.419-9.586L51.47 30h2.967a3.994 3.994 0 003.88-3.03l1.173-4.687a4.02 4.02 0 00-2.614-4.766zM54.437 26H46a2 2 0 000 4h1.28l-1.696 5.433-.031.11A37.218 37.218 0 0044 46.155V52a2.003 2.003 0 01-2 2h-2.491l-3.172-11.099a4.017 4.017 0 00-3.847-2.9H26.7c-.908 0-1.789.31-2.498.876l-8.702 6.96a3.982 3.982 0 00-1.5 3.125V52a2.003 2.003 0 01-2 2h-2a2.003 2.003 0 01-2-2v-5.172L10.828 44A3.97 3.97 0 0012 41.172v-11.32l18.613-1.432A8.037 8.037 0 0038 20.443V9.523l6.099 7.32c.476.572 1.102 1 1.808 1.234l9.703 3.235L54.438 26z" />
    </svg>
  );
}
