//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: phone.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function PhoneIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--phone', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M58.742 44.261L49.681 35.2a4.54 4.54 0 00-6.273 0l-4.166 4.166a2.221 2.221 0 01-3.138.001l-11.47-11.471a2.216 2.216 0 010-3.136l4.167-4.167a4.442 4.442 0 000-6.272l-9.062-9.063a4.54 4.54 0 00-6.273 0l-3.629 3.63c-7.783 7.8-7.783 20.428 0 28.228l17.048 17.048c7.8 7.783 20.428 7.783 28.229 0l3.63-3.63a4.442 4.442 0 00-.002-6.272zm-6.765 6.766c-6.067 6.053-15.89 6.053-21.956 0L12.973 33.979c-6.053-6.067-6.053-15.89 0-21.956l3.63-3.63 9.061 9.063-4.166 4.166a6.652 6.652 0 000 9.41l11.47 11.472a6.664 6.664 0 009.41-.001l4.166-4.167 9.062 9.062-3.629 3.629z"
        clipRule="evenodd"
      />
    </svg>
  );
}
