//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: pie-chart.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function PieChartIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--pie-chart', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M38.406 4.017a3.983 3.983 0 00-3.034 1.01 4.028 4.028 0 00-1.319 2.978v21.943H55.99a4.039 4.039 0 002.984-1.321 3.95 3.95 0 001.01-3.031c-1.127-11.418-10.16-20.451-21.578-21.58zm-.35 21.925l-.038-17.937a20.045 20.045 0 0117.974 17.937H38.055zm5.9 10.017H28.042V20.045a4.037 4.037 0 00-1.339-3 3.951 3.951 0 00-3.057-.992C12.236 17.299 3.693 27.095 4.008 38.568c.316 11.474 9.386 20.784 20.847 21.401.393.021.784.032 1.173.031 11.248.003 20.695-8.464 21.92-19.645a3.951 3.951 0 00-.992-3.057 4.037 4.037 0 00-3-1.34zm-18.89 20.009c-9.368-.507-16.782-8.112-17.05-17.49-.27-9.377 6.697-17.395 16.02-18.437v15.918a4.011 4.011 0 004.008 4.007l15.922-.041c-1.06 9.508-9.346 16.543-18.9 16.043z"
        clipRule="evenodd"
      />
    </svg>
  );
}
