//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: play.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function PlayIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--play', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M18 54.75a6.09 6.09 0 01-2.9-.75 5.93 5.93 0 01-3.1-5.26V15.26a6 6 0 019.16-5.11l29.91 16.78a6 6 0 010 10.14l-.09.06-29.82 16.72c-.95.588-2.043.9-3.16.9zm0-41.5a2.11 2.11 0 00-1 .26 2 2 0 00-1 1.75v33.48a2 2 0 003.07 1.69h.09L49 33.67a2 2 0 000-3.34L19.07 13.57a2 2 0 00-1.07-.32z"
      />
    </svg>
  );
}
