//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: plus-minus.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function PlusMinusIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--plus-minus', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M45 14.666H19c-9.573 0-17.333 7.76-17.333 17.334 0 9.573 7.76 17.333 17.333 17.333h26c9.573 0 17.334-7.76 17.334-17.333 0-9.573-7.76-17.334-17.334-17.334zM45 45H19c-7.18 0-13-5.82-13-13s5.82-13 13-13h26c7.18 0 13 5.82 13 13s-5.82 13-13 13zM27.667 32c0 1.196-.97 2.166-2.167 2.166H14.667a2.167 2.167 0 110-4.333H25.5c1.197 0 2.167.97 2.167 2.167zM51.5 32c0 1.196-.97 2.166-2.166 2.166h-3.25v3.25a2.167 2.167 0 01-4.334 0v-3.25H38.5a2.167 2.167 0 110-4.333h3.25v-3.25a2.167 2.167 0 014.334 0v3.25h3.25c1.196 0 2.166.97 2.166 2.167z"
        clipRule="evenodd"
      />
    </svg>
  );
}
