//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: police.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function PoliceIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--police', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M38.36 41.78a2.1 2.1 0 01-.94-.23L32 38.7l-5.42 2.85a2 2 0 01-2.11-.15 2 2 0 01-.8-2l1-6-4.39-4.28a2 2 0 011.11-3.41l6.06-.88 2.72-5.5a2 2 0 013.58 0l2.72 5.5 6.06.88a2 2 0 011.11 3.41l-4.35 4.28 1 6a2 2 0 01-2 2.34l.07.04zM32 34.44a1.91 1.91 0 01.93.23l2.77 1.45-.53-3.12a2 2 0 01.58-1.77L38 29.09l-3.1-.45a2 2 0 01-1.51-1.1L32 24.74l-1.38 2.8a2 2 0 01-1.51 1.1l-3.1.45 2.24 2.18a2 2 0 01.58 1.73l-.53 3.08 2.77-1.45c.29-.14.61-.206.93-.19z"
        clipRule="evenodd"
      />
      <path
        fill-rule="evenodd"
        d="M32 57a1.837 1.837 0 01-.41 0C18.08 54.11 10 43.56 10 35c.097-2.94.499-5.863 1.2-8.72 1.11-5.3 1.68-8.66-.59-10.84a2 2 0 010-2.85l5-5a2 2 0 012.35-.36 13.21 13.21 0 0013.13 0 2 2 0 011.86 0 13.21 13.21 0 0013.13 0 2 2 0 012.35.36l5 5a2 2 0 010 2.85c-2.27 2.18-1.7 5.54-.59 10.84A42.42 42.42 0 0154 35c0 8.56-8.08 19.11-21.59 22a1.837 1.837 0 01-.41 0zM14.69 14.13c2.375 3.662 1.394 8.369.437 12.97l-.007.03A39.373 39.373 0 0014 35c0 6.73 6.87 15.43 18 18 11.13-2.52 18-11.22 18-18a39.367 39.367 0 00-1.12-7.9c-1-4.58-2-9.3.43-13l-2.72-2.71A16.89 16.89 0 0132 11.23a16.89 16.89 0 01-14.59.19l-2.72 2.71z"
        clip-rule="evenodd"
      />
    </svg>
  );
}
