//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: portal.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function PortalIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--portal', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path d="M13 17.707c0 .85-.672 1.54-1.5 1.54s-1.5-.69-1.5-1.54c0-.85.672-1.54 1.5-1.54s1.5.69 1.5 1.54zm5 0c0 .85-.672 1.54-1.5 1.54s-1.5-.69-1.5-1.54c0-.85.672-1.54 1.5-1.54s1.5.69 1.5 1.54z" />
      <path
        fillRule="evenodd"
        d="M8 11a4 4 0 00-4 4v34a4 4 0 004 4h48a4 4 0 004-4V15a4 4 0 00-4-4H8zm0 4h48v5.64H8V15zm0 9.64V49h48V24.64H8z"
        clipRule="evenodd"
      />
      <path
        fillRule="evenodd"
        d="M32 26a7 7 0 00-6.386 9.872A6.998 6.998 0 0022 42v1a4 4 0 004 4h12a4 4 0 004-4v-1a6.998 6.998 0 00-3.614-6.128A7 7 0 0032 26zm-3 7a3 3 0 116 0 3 3 0 01-6 0zm6.53 6.047A6.968 6.968 0 0132 40a6.968 6.968 0 01-3.53-.953A3 3 0 0026 42v1h12v-1a3 3 0 00-2.47-2.953z"
        clipRule="evenodd"
      />
    </svg>
  );
}
