//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: premises-small.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function PremisesSmallIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--premises-small', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path d="M16 15a1 1 0 011-1h2a1 1 0 011 1v2a1 1 0 01-1 1h-2a1 1 0 01-1-1v-2zm0 7a1 1 0 011-1h2a1 1 0 011 1v2a1 1 0 01-1 1h-2a1 1 0 01-1-1v-2zm0 7a1 1 0 011-1h2a1 1 0 011 1v2a1 1 0 01-1 1h-2a1 1 0 01-1-1v-2zm0 7a1 1 0 011-1h2a1 1 0 011 1v2a1 1 0 01-1 1h-2a1 1 0 01-1-1v-2zm14-21a1 1 0 011-1h2a1 1 0 011 1v2a1 1 0 01-1 1h-2a1 1 0 01-1-1v-2zm-7 0a1 1 0 011-1h2a1 1 0 011 1v2a1 1 0 01-1 1h-2a1 1 0 01-1-1v-2zm0 7a1 1 0 011-1h2a1 1 0 011 1v2a1 1 0 01-1 1h-2a1 1 0 01-1-1v-2zm0 7a1 1 0 011-1h2a1 1 0 011 1v2a1 1 0 01-1 1h-2a1 1 0 01-1-1v-2zm0 7a1 1 0 011-1h2a1 1 0 011 1v2a1 1 0 01-1 1h-2a1 1 0 01-1-1v-2z" />
      <path
        fillRule="evenodd"
        d="M8 8a4 4 0 014-4h26a4 4 0 014 4v9.01c.166-.007.333-.01.5-.01C49.956 17 56 23.044 56 30.5S49.956 44 42.5 44c-.167 0-.334-.003-.5-.01V56a4 4 0 01-4 4H12a4 4 0 01-4-4V8zm30 35.232c-5.243-1.853-9-6.854-9-12.732 0-5.878 3.757-10.879 9-12.732V8H12v48h7v-9a2 2 0 012-2h8a2 2 0 012 2v9h7V43.232zM27 56h-4v-7h4v7zm6-25.5a9.5 9.5 0 1119 0 9.5 9.5 0 01-19 0z"
        clipRule="evenodd"
      />
      <path d="M46.071 32.256c0-1.456-.798-2.394-2.59-3.066-.686-.266-1.176-.462-1.47-.616-.588-.28-.756-.49-.756-.868 0-.504.574-.854 1.372-.854.504 0 1.064.182 1.68.546.14.084.252.126.35.126.434 0 .854-.658.854-1.33a.458.458 0 00-.21-.406 4.651 4.651 0 00-2.604-.798 3.97 3.97 0 00-1.68.35c-1.022.462-1.722 1.358-1.722 2.408 0 1.386.798 2.184 2.87 2.954.742.266 1.246.518 1.526.742.28.224.42.504.42.826 0 .63-.602 1.036-1.512 1.036-.77 0-1.358-.28-1.988-.994a.538.538 0 00-.406-.154c-.63 0-1.274.42-1.274.826 0 .112.056.266.168.448.182.322.462.616.826.882.728.532 1.722.896 2.674.896.63 0 1.204-.126 1.736-.378 1.05-.49 1.736-1.442 1.736-2.576z" />
    </svg>
  );
}
