//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: premises-datacenter.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function PremisesDatacenterIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--premises-datacenter', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M14 10a4 4 0 00-4 4v36a4 4 0 004 4h36a4 4 0 004-4V14a4 4 0 00-4-4H14zm0 4h36v36H38v-9a2 2 0 00-2-2h-8a2 2 0 00-2 2v9H14V14zm16 36h4v-7h-4v7z"
        clipRule="evenodd"
      />
      <path
        fillRule="evenodd"
        d="M20 23a2 2 0 012-2h20a2 2 0 110 4H22a2 2 0 01-2-2zm0 9a2 2 0 012-2h20a2 2 0 110 4H22a2 2 0 01-2-2z"
        clipRule="evenodd"
      />
    </svg>
  );
}
