//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: premises-large.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function PremisesLargeIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--premises-large', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path d="M16 15a1 1 0 011-1h2a1 1 0 011 1v2a1 1 0 01-1 1h-2a1 1 0 01-1-1v-2zm0 7a1 1 0 011-1h2a1 1 0 011 1v2a1 1 0 01-1 1h-2a1 1 0 01-1-1v-2zm0 7a1 1 0 011-1h2a1 1 0 011 1v2a1 1 0 01-1 1h-2a1 1 0 01-1-1v-2zm0 7a1 1 0 011-1h2a1 1 0 011 1v2a1 1 0 01-1 1h-2a1 1 0 01-1-1v-2zm14-21a1 1 0 011-1h2a1 1 0 011 1v2a1 1 0 01-1 1h-2a1 1 0 01-1-1v-2zm-7 0a1 1 0 011-1h2a1 1 0 011 1v2a1 1 0 01-1 1h-2a1 1 0 01-1-1v-2zm0 7a1 1 0 011-1h2a1 1 0 011 1v2a1 1 0 01-1 1h-2a1 1 0 01-1-1v-2zm0 7a1 1 0 011-1h2a1 1 0 011 1v2a1 1 0 01-1 1h-2a1 1 0 01-1-1v-2zm0 7a1 1 0 011-1h2a1 1 0 011 1v2a1 1 0 01-1 1h-2a1 1 0 01-1-1v-2z" />
      <path
        fillRule="evenodd"
        d="M8 8a4 4 0 014-4h26a4 4 0 014 4v9.01c.166-.007.333-.01.5-.01C49.956 17 56 23.044 56 30.5S49.956 44 42.5 44c-.167 0-.334-.003-.5-.01V56a4 4 0 01-4 4H12a4 4 0 01-4-4V8zm30 35.232c-5.243-1.853-9-6.854-9-12.732 0-5.878 3.757-10.879 9-12.732V8H12v48h7v-9a2 2 0 012-2h8a2 2 0 012 2v9h7V43.232zM27 56h-4v-7h4v7zm6-25.5a9.5 9.5 0 1119 0 9.5 9.5 0 01-19 0z"
        clipRule="evenodd"
      />
      <path d="M45.022 35c.14 0 .28-.07.434-.196.28-.266.504-.77.504-1.274 0-.322-.168-.49-.518-.49h-3.64v-7.42c0-.336-.182-.504-.546-.504-.686 0-1.4.462-1.4.91v7.854c0 .266.476 1.12.966 1.12h4.2z" />
    </svg>
  );
}
