//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: press-button.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function PressButtonIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--press-button', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M46.06 30.964a6.186 6.186 0 00-2.293.437 6.246 6.246 0 00-2.986-3.799 14.514 14.514 0 10-17.535 4.028v2.607a6.335 6.335 0 00-7.173-2.218 6.224 6.224 0 00-3.454 8.546l7.123 14.746A8.34 8.34 0 0027.212 60h16.774a8.306 8.306 0 008.296-8.296V37.186a6.229 6.229 0 00-6.222-6.222zM19.098 18.519a10.37 10.37 0 1116.592 8.296v-8.117a6.368 6.368 0 00-5.618-6.372 6.223 6.223 0 00-6.826 6.193v8.296a10.392 10.392 0 01-4.148-8.296zm29.037 33.185a4.152 4.152 0 01-4.148 4.148H27.212a4.17 4.17 0 01-3.736-2.344L16.354 38.76a2.077 2.077 0 011.16-2.852 1.85 1.85 0 01.646-.115 2.287 2.287 0 012.008 1.324l2.472 5.118a2.075 2.075 0 001.867 1.172h.813a2.074 2.074 0 002.074-2.074V18.519a2.073 2.073 0 012.285-2.063 2.19 2.19 0 011.863 2.242v14.34a2.074 2.074 0 004.148 0 2.074 2.074 0 114.148 0v4.148a2.074 2.074 0 004.148 0 2.074 2.074 0 114.149 0v14.518z"
        clipRule="evenodd"
      />
    </svg>
  );
}
