//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: present.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function PresentIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--present', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M56 17h-8.061A8.99 8.99 0 0032 10.356 8.993 8.993 0 0016.056 17H8a3.848 3.848 0 00-4 3.668v6.666A3.848 3.848 0 008 31v18a8.01 8.01 0 008 8h32a8.01 8.01 0 008-8V31a3.848 3.848 0 004-3.666v-6.666A3.848 3.848 0 0056 17zm-17-6a4.972 4.972 0 014.893 6h-9.781A4.953 4.953 0 0139 11zm-19 5a5 5 0 119.889 1h-9.784A5.03 5.03 0 0120 16zm10 5v6H8v-6h22zM12 49V31h18v22H16a4.004 4.004 0 01-4-4zm40 0a4.004 4.004 0 01-4 4H34V31h18v18zM34 27v-6h22v6H34z"
        clipRule="evenodd"
      />
    </svg>
  );
}
