//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: print.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function PrintIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--print', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path d="M22 42a2 2 0 012-2h16a2 2 0 110 4H24a2 2 0 01-2-2zm2 5a2 2 0 100 4h16a2 2 0 100-4H24z" />
      <path
        fillRule="evenodd"
        d="M56 25h-4v-6.172A4 4 0 0050.828 16L40 5.172A4 4 0 0037.172 4H20a8 8 0 00-8 8v13H8a4 4 0 00-4 4v17a4 4 0 004 4h4v6a4 4 0 004 4h28a8 8 0 008-8v-2h4a4 4 0 004-4V29a4 4 0 00-4-4zM16 12a4 4 0 014-4h16v8a4 4 0 004 4h8v5H16V12zm24 4v-5.172L45.172 16H40zM12 46H8V29h48v17h-4V33H12v13zm4-9v19h28a4 4 0 004-4V37H16z"
        clipRule="evenodd"
      />
    </svg>
  );
}
