//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: product-mobilpant.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function ProductMobilpantIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--product-mobilpant', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M36.92 4a8 8 0 018 8v13.12l2.74-2.74a2 2 0 112.83 2.83l-5.54 5.54a2.89 2.89 0 01-4.05 0l-5.54-5.54a2.001 2.001 0 012.83-2.83l2.73 2.74V12a4 4 0 00-4-4h-16a4 4 0 00-4 4v32h24v-7.36a2 2 0 114 0V52a8 8 0 01-8 8h-16a8 8 0 01-8-8V12a8 8 0 018-8zm4 44h-24v4a4 4 0 004 4h16a4 4 0 004-4v-4zm-12 2a2 2 0 110 4 2 2 0 010-4z"
      />
    </svg>
  );
}
