//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: product-ladeavtale.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function ProductLadeavtaleIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--product-ladeavtale', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M27.41 25.29a2 2 0 00-1.41-.58H15.82a3.67 3.67 0 00-3.82 3.5v9a3.68 3.68 0 003.82 3.5H38a2 2 0 001.41-3.42l-12-12zM16 36.7v-8h9.17l8 8H16zm40-14h-.25a8 8 0 00-7.75-6H12a8 8 0 00-8 8v16a8 8 0 008 8h36a8 8 0 007.75-6H56c2.24 0 4-2.05 4-4.67V27.37c0-2.61-1.76-4.66-4-4.66v-.01zM56 38c.01.235-.05.468-.17.67H52v2a4 4 0 01-4 4H12a4 4 0 01-4-4v-16a4 4 0 014-4h36a4 4 0 014 4v2h3.83c.12.199.179.428.17.66V38z"
      />
    </svg>
  );
}
