//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: product-bedriftsnett.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function ProductBedriftsnettIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--product-bedriftsnett', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M33.88 8.38L53.82 18.7A4.14 4.14 0 0156 22.35V52a4.13 4.13 0 01-4.1 4.1h-18a4.13 4.13 0 01-4.13-4.1v-7.65a2.025 2.025 0 014.05 0V52a.07.07 0 00.08.08h18A.07.07 0 0052 52V22.35L32 12h-.13L12 22.3v29.63a.07.07 0 00.07.08h10.2a2.025 2.025 0 010 4.05H12.1A4.13 4.13 0 018 51.93V22.35a4.11 4.11 0 012.17-3.63L30 8.38a4.1 4.1 0 013.88 0zm9.62 15.04a14.27 14.27 0 010 20.2 2 2 0 01-2.83-2.83 10.26 10.26 0 000-14.54 2.001 2.001 0 012.83-2.83zm-21.32-.636A2 2 0 0123 26.25a10.28 10.28 0 000 14.54 2 2 0 01-1.249 3.414l-.156.006-.17-.008a2 2 0 01-1.235-.582 14.27 14.27 0 010-20.2 2 2 0 011.99-.636zm16.23 4.366a9 9 0 010 12.75 2 2 0 01-1.41.58 2 2 0 01-1.41-3.41 5 5 0 000-7.09 2 2 0 112.82-2.83zm-11.198-.513A2.008 2.008 0 0128.1 30a5 5 0 000 7.09 2 2 0 010 2.83 2 2 0 01-1.41.56 2 2 0 01-1.42-.58 9 9 0 010-12.75 2.008 2.008 0 011.942-.513zm4.578 4.843a2.04 2.04 0 110 4.08 2.04 2.04 0 010-4.08z"
      />
    </svg>
  );
}
