//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: question.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function QuestionIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--question', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M32 4C16.536 4 4 16.536 4 32s12.536 28 28 28 28-12.536 28-28C59.983 16.543 47.457 4.017 32 4zm0 51.692C18.915 55.692 8.308 45.085 8.308 32S18.915 8.308 32 8.308 55.692 18.915 55.692 32C55.678 45.079 45.08 55.678 32 55.692z"
        clipRule="evenodd"
      />
      <path
        fill-rule="evenodd"
        d="M31.942 37.572l4.369-4.665.424-.462c3.02-3.329 4.03-5.38 4.03-7.936 0-1.4-.34-2.715-1.06-3.86-1.4-2.29-4.073-3.732-7.423-3.732-3.525 0-6.97 1.824-9.024 4.76l-.138.202c-.297.424-.424.806-.424 1.103 0 .72 1.23 3.011 2.587 3.011.255 0 .51-.085.764-.254.212-.17.551-.51 1.018-1.018 1.823-2.036 3.053-2.8 4.708-2.8 1.908 0 3.308 1.273 3.308 2.97 0 1.484-.806 2.884-2.715 4.962l-4.114 4.369c-.297.381-.466.72-.466 1.06 0 .34.212.89.636 1.612.636.975 1.315 1.484 2.036 1.484.466 0 .933-.254 1.484-.806zm-1.06 9.925c-1.654 0-3.224-2.757-3.224-3.817 0-1.485 2.418-3.054 4.75-3.054 1.23 0 1.867.552 1.867 1.697 0 1.739-.806 3.52-1.824 4.453-.509.467-1.018.721-1.569.721z"
        clip-rule="evenodd"
      />
    </svg>
  );
}
