//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: rack.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function RackIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--rack', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M18 13a2 2 0 012-2h8a2 2 0 110 4h-8a2 2 0 01-2-2zm0 14a2 2 0 012-2h8a2 2 0 110 4h-8a2 2 0 01-2-2zm0 14a2 2 0 012-2h8a2 2 0 110 4h-8a2 2 0 01-2-2z"
        clipRule="evenodd"
      />
      <path
        fill-rule="evenodd"
        d="M20 4a8 8 0 00-8 8v40a8 8 0 008 8h24a8 8 0 008-8V12a8 8 0 00-8-8H20zm28 42V36H16v10h32zm-32 4v2a4 4 0 004 4h24a4 4 0 004-4v-2H16zm32-28v10H16V22h32zM16 12a4 4 0 014-4h24a4 4 0 014 4v6H16v-6z"
        clip-rule="evenodd"
      />
      <path d="M38 13a2 2 0 11-4 0 2 2 0 014 0zm0 14a2 2 0 11-4 0 2 2 0 014 0zm0 14a2 2 0 11-4 0 2 2 0 014 0zm6-28a2 2 0 11-4 0 2 2 0 014 0zm0 14a2 2 0 11-4 0 2 2 0 014 0zm0 14a2 2 0 11-4 0 2 2 0 014 0z" />
    </svg>
  );
}
