//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: radio.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function RadioIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--radio', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path d="M24 28a4 4 0 100 8 4 4 0 000-8z" />
      <path
        fillRule="evenodd"
        d="M12 32c0-6.627 5.373-12 12-12s12 5.373 12 12-5.373 12-12 12-12-5.373-12-12zm12-8a8 8 0 100 16 8 8 0 000-16z"
        clipRule="evenodd"
      />
      <path d="M40 32a2 2 0 012-2h8a2 2 0 110 4h-8a2 2 0 01-2-2zm2 6a2 2 0 100 4h8a2 2 0 100-4h-8zm-2-14a2 2 0 012-2h8a2 2 0 110 4h-8a2 2 0 01-2-2z" />
      <path
        fill-rule="evenodd"
        d="M34 10a2 2 0 10-4 0v2h-4v-2a2 2 0 10-4 0v2h-4v-2a2 2 0 10-4 0v2h-2a8 8 0 00-8 8v24a8 8 0 008 8h40a8 8 0 008-8V20a8 8 0 00-8-8H34v-2zm-22 6a4 4 0 00-4 4v24a4 4 0 004 4h40a4 4 0 004-4V20a4 4 0 00-4-4H12z"
        clip-rule="evenodd"
      />
    </svg>
  );
}
