//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: record.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function RecordIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--record', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path d="M37 32a5 5 0 11-10 0 5 5 0 0110 0z" />
      <path
        fillRule="evenodd"
        d="M16.444 55.281A28 28 0 1047.556 8.717a28 28 0 00-31.112 46.564zm2.222-43.236a24 24 0 1126.668 39.911 24 24 0 01-26.668-39.911z"
        clipRule="evenodd"
      />
    </svg>
  );
}
