//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: recycle.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function RecycleIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--recycle', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M56.513 49.368a8.585 8.585 0 01-7.486 4.3h-9.63l2.802 2.8a2.167 2.167 0 01-3.064 3.064l-6.5-6.5c-.033-.032-.055-.07-.085-.103a2.159 2.159 0 01-.093-.114 2.153 2.153 0 01-.285-.475l-.007-.01v-.004a2.154 2.154 0 01-.152-.688 2.173 2.173 0 01.028-.558l.005-.013a2.158 2.158 0 01.246-.636 2.15 2.15 0 01.343-.462l6.5-6.5a2.166 2.166 0 013.064 3.063l-2.802 2.802h9.63a4.333 4.333 0 003.772-6.465l-5.54-9.802a2.167 2.167 0 113.772-2.133l5.54 9.802a8.586 8.586 0 01-.058 8.632zM19.912 23.053a2.166 2.166 0 002.952-.82l5.363-9.488a4.334 4.334 0 017.545 0l5.985 10.589H38.5a2.167 2.167 0 000 4.333h8.666c1.197 0 2.167-.97 2.167-2.167v-8.666a2.167 2.167 0 10-4.333 0v3.43l-5.455-9.652a8.668 8.668 0 00-15.09 0l-5.363 9.489a2.168 2.168 0 00.82 2.952zm7.754 26.28H14.973a4.333 4.333 0 01-3.773-6.465l5.633-9.964v3.43a2.167 2.167 0 104.333 0v-8.667c0-1.197-.97-2.167-2.166-2.167h-8.667a2.167 2.167 0 000 4.333h3.258L7.428 40.736a8.667 8.667 0 007.545 12.93h12.693a2.167 2.167 0 000-4.333z"
        clipRule="evenodd"
      />
    </svg>
  );
}
