//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: register.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function RegisterIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--register', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path d="M42 61.333H14a4 4 0 01-4-4v-44a8.009 8.009 0 018-8h28a4 4 0 014 4v15.025a2 2 0 11-4 0V9.333H18a4 4 0 00-4 4v44h28a4.011 4.011 0 003.459-2 2 2 0 013.463 2 8.026 8.026 0 01-6.922 4z" />
      <path d="M40.865 32.888c-.405-3.453-1.748-5.989-3.93-7.583a8 8 0 10-13.87 0c-2.182 1.594-3.525 4.131-3.93 7.585a3.967 3.967 0 00.98 3.1 4.015 4.015 0 003 1.347h13.772a4.015 4.015 0 003-1.347 3.966 3.966 0 00.978-3.102zM30 17.333a4 4 0 110 8 4 4 0 010-8zm-6.887 16l-.006.021c.3-2.57 1.2-4.233 2.819-5.148a7.924 7.924 0 008.148 0c1.623.914 2.515 2.571 2.813 5.128H23.113zM39.626 53.7a4 4 0 01-3.9-4.869l1.193-5.363A3.99 3.99 0 0138 41.508l12.172-12.175a4 4 0 015.656 0L60 33.505a4 4 0 010 5.656L47.826 51.333a4 4 0 01-1.963 1.077L40.5 53.604c-.287.064-.58.096-.874.096zm1.2-9.367l-1.192 5.363L45 48.507l12.172-12.174L53 32.161 40.826 44.333zm-9.826 4H21a2 2 0 010-4h10a2 2 0 010 4z" />
    </svg>
  );
}
