//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: reservation.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function ReservationIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--reservation', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path d="M32 8c7.495 0 13.316 2.145 17.586 6.414C53.856 18.684 56 24.504 56 32a2 2 0 104 0c0-8.505-2.522-15.35-7.586-20.414C47.35 6.522 40.504 4 32 4a2 2 0 100 4zm-15 6a3 3 0 11-6 0 3 3 0 016 0zM7 35a3 3 0 100-6 3 3 0 000 6zm10 15a3 3 0 11-6 0 3 3 0 016 0zm33 3a3 3 0 100-6 3 3 0 000 6zm-18 7a3 3 0 100-6 3 3 0 000 6zm2-35v7h12a2 2 0 110 4H32a2 2 0 01-2-2v-9a2 2 0 114 0z" />
    </svg>
  );
}
