//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: route.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function RouteIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--route', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path d="M18 50a2.448 2.448 0 001.787-.778C22.256 46.57 28 39.778 28 34a10 10 0 00-20 0c0 5.773 5.743 12.567 8.21 15.219A2.452 2.452 0 0018 50zm0-22a6.007 6.007 0 016 6c0 3.157-3.019 7.751-6 11.22-2.98-3.469-6-8.066-6-11.22a6.007 6.007 0 016-6zm28 4a2.448 2.448 0 001.787-.778C50.256 28.57 56 21.778 56 16a10 10 0 00-20 0c0 5.773 5.743 12.567 8.21 15.219A2.45 2.45 0 0046 32zm0-22a6.007 6.007 0 016 6c0 3.157-3.019 7.751-6 11.22-2.98-3.469-6-8.066-6-11.22a6.007 6.007 0 016-6zM18 36a2 2 0 110-4 2 2 0 010 4zm28-18a2 2 0 110-4 2 2 0 010 4zm10 20a2 2 0 01-2 2H41.473a5.962 5.962 0 00-5.592 3.825l-3.033 7.799A9.937 9.937 0 0123.528 58H10a2 2 0 110-4h13.527a5.962 5.962 0 005.592-3.825l3.033-7.799A9.937 9.937 0 0141.472 36H54a2 2 0 012 2z" />
    </svg>
  );
}
