//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: router.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function RouterIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--router', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M52 33H12a8.01 8.01 0 00-8 8v6a8.01 8.01 0 008 8h40a8.01 8.01 0 008-8v-6a8.01 8.01 0 00-8-8zm4 14a4.004 4.004 0 01-4 4H12a4.004 4.004 0 01-4-4v-6a4.004 4.004 0 014-4h40a4.004 4.004 0 014 4v6zm-26-3a2 2 0 01-2 2H16a2 2 0 110-4h12a2 2 0 012 2zm12 0a2 2 0 11-4 0 2 2 0 014 0zm8 0a2 2 0 11-4 0 2 2 0 014 0zM15.543 17.848a2 2 0 01.215-2.82c9.337-8.037 23.147-8.037 32.484 0a2 2 0 01-2.605 3.034c-7.839-6.75-19.436-6.75-27.274 0a2 2 0 01-2.82-.214zM32 19a11.822 11.822 0 018.416 3.486 2 2 0 01-2.83 2.828 7.898 7.898 0 00-11.172 0 2 2 0 11-2.83-2.828A11.822 11.822 0 0132 19z"
        clipRule="evenodd"
      />
    </svg>
  );
}
