//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: ruler.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function RulerIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--ruler', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path d="M54 38H26V10a4.004 4.004 0 00-4-4H10a4.004 4.004 0 00-4 4v44a4.004 4.004 0 004 4h44a4.005 4.005 0 004-4V42a4.005 4.005 0 00-4-4zm0 16H10V10h12v4h-6a2 2 0 000 4h6v4h-4a2 2 0 000 4h4v4h-6a2 2 0 000 4h6v4h-4a2 2 0 000 4h4v4a2 2 0 004 0v-4h4v6a2 2 0 004 0v-6h4v4a2 2 0 004 0v-4h4v6a2 2 0 004 0v-6h4v12z" />
    </svg>
  );
}
