//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: satellite.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function SatelliteIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--satellite', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path d="M16.07 24.48a2 2 0 01-1.42-.59L9 18.23a2 2 0 010-2.82l9.9-9.9a2 2 0 012.82 0l5.66 5.65A2 2 0 0124.55 14l-4.24-4.25-7.07 7.07 4.24 4.24a2 2 0 01-1.41 3.42zM47.18 55.59a2 2 0 01-1.41-.59l-5.66-5.65a2 2 0 012.83-2.83l4.24 4.24 7.07-7.07L50 39.45a2 2 0 112.83-2.83l5.65 5.66a2 2 0 010 2.82L48.59 55a2 2 0 01-1.41.59zM21.88 49.34v-.28-.21a1.35 1.35 0 010 .49z" />
      <path d="M21.88 49.34v-.28-.21a1.35 1.35 0 010 .49z" />
      <path d="M21.88 49.34v-.28-.21a1.35 1.35 0 010 .49z" />
      <path d="M55.07 20.24L43.76 8.93a6 6 0 00-8.49 0l-22 22a2 2 0 00-.59 1.42 2 2 0 00.59 1.41l1.87 1.87A12.77 12.77 0 009 37.29a2 2 0 00-1 1.47 2 2 0 00.57 1.69l3.23 3.24a6 6 0 008.49 8.49l3.24 3.23A2 2 0 0025 56h.28a2 2 0 001.47-1 12.77 12.77 0 001.63-6.09l1.87 1.87a2 2 0 001.41.59 2 2 0 001.34-.61l22-22a6 6 0 00.07-8.52zM14.65 49.35a2 2 0 010-2.83l2.83 2.83a2 2 0 01-2.83 0zm-.05-7.22a1.46 1.46 0 01.55 0H15a2.07 2.07 0 00-.4 0zm9.58 8.26l-2.84-2.84-4.89-4.89-2.84-2.85a9 9 0 0110.57 10.58zM52.24 25.9L31.62 46.52l-7.07-7.07-7.07-7.07L38.1 11.76a2 2 0 012.83 0l11.31 11.31a2 2 0 010 2.83z" />
    </svg>
  );
}
