//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: save.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function SaveIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--save', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path d="M54.828 16L48 9.172A3.974 3.974 0 0045.172 8H16a8.009 8.009 0 00-8 8v32a8.009 8.009 0 008 8h32a8.009 8.009 0 008-8V18.829A3.971 3.971 0 0054.828 16zM21 12h12v9H21v-9zm16 0h4v9h-4v-9zm6 40H21V38h22v14zm9-4a4 4 0 01-4 4h-1V38a4 4 0 00-4-4H21a4 4 0 00-4 4v14h-1a4 4 0 01-4-4V16a4 4 0 014-4h1v9a4 4 0 004 4h20a4 4 0 004-4v-9h.172L52 18.829V48z" />
    </svg>
  );
}
