//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: savings.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function SavingsIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--savings', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M56 27h-1.103a18.547 18.547 0 00-2.746-4.846l1.808-8.75a2 2 0 00-3.037-2.088l-7.317 4.683a11.991 11.991 0 00-23.067-.554l-.215.098c-.43.193-.86.387-1.264.604C12.814 19.478 8.85 24.93 8.129 31H6a2 2 0 100 4h2.128c.679 5.715 4.238 10.884 9.872 14.25V53a4.004 4.004 0 004 4h4a4.004 4.004 0 004-4v-2h4v2a4.004 4.004 0 004 4h4a4.004 4.004 0 004-4v-3.75A21.343 21.343 0 0054.003 41H56a4.004 4.004 0 004-4v-6a4.004 4.004 0 00-4-4zM32 11a8.01 8.01 0 018 8 7.916 7.916 0 01-2.725 6h-10.55A7.917 7.917 0 0124 19a8.01 8.01 0 018-8zm20.743 26H56v-6h-2.552c-.898 0-1.687-.6-1.926-1.466a14.489 14.489 0 00-3.04-5.55 2.001 2.001 0 01-.44-1.707l1.04-5.035-5.19 3.322a11.82 11.82 0 01-1.734 4.81A1.997 1.997 0 0141 29H22a1.998 1.998 0 01-.353-3.964 11.826 11.826 0 01-1.58-4.863C14.999 23.2 12 27.93 12 33c0 5.352 3.343 10.331 8.941 13.32A2 2 0 0122 48.083V53h4v-2a4.004 4.004 0 014-4h4a4.004 4.004 0 014 4v2h4v-4.916a2 2 0 011.059-1.765 17.24 17.24 0 007.848-8.112A2 2 0 0152.743 37z"
        clipRule="evenodd"
      />
    </svg>
  );
}
