//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: security-camera.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function SecurityCameraIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--security-camera', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M20.501 5.805l36.345 20.983c3.61 2.085 3.976 7.017 1.019 9.656a8.002 8.002 0 01-13.489 8.46l-1.848 1.145a6 6 0 01-6.159.094l-11.517-6.65v9.477a2 2 0 01-2 2H8.104v6.98a2 2 0 11-4 0V41.112a2 2 0 114 0v5.857h12.748v-9.786L7 29.188a6 6 0 01-2.196-8.197l7.5-12.99A6 6 0 0120.5 5.805zm34.345 24.448L18.5 9.269a2 2 0 00-2.732.732l-7.5 12.99A2 2 0 009 25.723L38.369 42.68a2 2 0 002.053-.031L54.9 33.685c1.285-.796 1.257-2.676-.053-3.432zm-7.03 12.522l6.65-4.118a4.002 4.002 0 01-6.65 4.118z"
        clipRule="evenodd"
      />
    </svg>
  );
}
