//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: security.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function SecurityIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--security', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M33.15 7.36a68.33 68.33 0 0019.42 9.72A2 2 0 0154 19c0 18.88-7.08 32.26-21 39.76a2 2 0 01-1 .24 2 2 0 01-.95-.24c-14-7.5-21-20.88-21-39.76a2 2 0 011.43-1.92 68.33 68.33 0 0019.37-9.72 2 2 0 012.3 0zM32 11.46a72.4 72.4 0 01-18 9c.34 16.31 6.24 27.54 18 34.25C43.76 48 49.66 36.77 50 20.46a72.4 72.4 0 01-18-9zm7.488 12.877A2 2 0 0140.53 27.8l-9.43 11a2 2 0 01-1.44.7h-.02a2 2 0 01-1.41-.59l-4.72-4.71a2.001 2.001 0 012.83-2.83l3.19 3.19 8-9.36a2 2 0 011.958-.863z"
      />
    </svg>
  );
}
