//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: send.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function SendIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--send', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M8.416 6.293C5.997 5.18 3.386 7.418 4.13 9.968L10.543 32 4.129 54.032c-.743 2.55 1.868 4.788 4.287 3.675l49.778-22.895c2.408-1.107 2.408-4.517 0-5.624L8.416 6.293zm5.84 23.642L8.743 10.991 49.93 29.935H14.256zm0 4.13L8.743 53.01 49.93 34.066H14.257z"
        clipRule="evenodd"
      />
    </svg>
  );
}
