//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: sense-car.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function SenseCarIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--sense-car', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path d="M52 34h-5.172L38 25.172A3.974 3.974 0 0035.172 24H17.355a3.983 3.983 0 00-3.715 2.515L10.645 34H8a4.005 4.005 0 00-4 4v6a8.006 8.006 0 007.338 7.967A5.99 5.99 0 0022.65 52H42a1.99 1.99 0 00.337-.034A5.99 5.99 0 0053.65 52H56a4.004 4.004 0 004-4v-6a8.01 8.01 0 00-8-8zM17 52a2 2 0 110-4 2 2 0 010 4zm31 0a2 2 0 110-4 2 2 0 010 4zm8-4h-2.35a5.991 5.991 0 00-11.313.034A2 2 0 0042 48H22.65a5.99 5.99 0 00-11.277-.063A3.996 3.996 0 018 44v-6h4.007a1.977 1.977 0 00.633-.114 1.98 1.98 0 00.451-.213l.02-.011a2.003 2.003 0 00.467-.447c.111-.14.203-.295.272-.46l.007-.012L17.355 28h17.817l9.413 9.413a2 2 0 00.306.25c.048.032.1.054.149.081.063.038.128.073.196.103.065.024.132.045.2.062.057.017.112.04.172.052.13.026.26.039.392.039h6a4.005 4.005 0 014 4v6zM32.663 9.15a2 2 0 011.347-2.487A16.02 16.02 0 0153.917 17.43a1.999 1.999 0 11-3.834 1.14 12.02 12.02 0 00-14.933-8.073 2.001 2.001 0 01-2.487-1.347zm13.223 10.184a2.001 2.001 0 11-3.772 1.332 4.008 4.008 0 00-5.105-2.44 2 2 0 11-1.334-3.77 8.006 8.006 0 0110.21 4.878z" />
    </svg>
  );
}
