//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: services.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function ServicesIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--services', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M13 46a5 5 0 110 10 5 5 0 010-10zm20 0a5 5 0 110 10 5 5 0 010-10zm18 0a5 5 0 110 10 5 5 0 010-10zM13 27a5 5 0 110 10 5 5 0 010-10zm19 0a5 5 0 110 10 5 5 0 010-10zm19 0a5 5 0 110 10 5 5 0 010-10zM13 8a5 5 0 110 10 5 5 0 010-10zm19 0a5 5 0 110 10 5 5 0 010-10zm19 0a5 5 0 110 10 5 5 0 010-10z"
      />
    </svg>
  );
}
