//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: services.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function ServicesIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--services', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M12 18a4 4 0 118 0 4 4 0 01-8 0zm4 10a4 4 0 100 8 4 4 0 000-8zm-4 18a4 4 0 118 0 4 4 0 01-8 0zm16-28a4 4 0 118 0 4 4 0 01-8 0zm4 10a4 4 0 100 8 4 4 0 000-8zm-4 18a4 4 0 118 0 4 4 0 01-8 0zm16-28a4 4 0 118 0 4 4 0 01-8 0zm4 10a4 4 0 100 8 4 4 0 000-8zm-4 18a4 4 0 118 0 4 4 0 01-8 0z"
        clipRule="evenodd"
      />
    </svg>
  );
}
