//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: share.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function ShareIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--share', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path d="M40.929 40.929c-.29.294-.563.606-.814.934l-16.458-7.315a10.062 10.062 0 000-5.1l16.405-7.383a10.02 10.02 0 10-1.74-3.603l-16.44 7.397a10.07 10.07 0 10.003 12.278l16.458 7.315a9.98 9.98 0 102.586-4.523zm2.828-29.172a6 6 0 110 8.486 5.985 5.985 0 010-8.486zM18.243 36.243a5.997 5.997 0 110-8.486 6.011 6.011 0 010 8.486zm34 16a5.997 5.997 0 110-8.486 6.011 6.011 0 010 8.486z" />
    </svg>
  );
}
