//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: shopping.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function ShoppingIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--shopping', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path d="M48 16h-4a12 12 0 00-24 0h-4a4.005 4.005 0 00-4 4v34a4.005 4.005 0 004 4h32a4.005 4.005 0 004-4V20a4.005 4.005 0 00-4-4zM32 8a8.01 8.01 0 018 8H24a8.01 8.01 0 018-8zm16 46H16V20h4v4a2 2 0 004 0v-4l16-.002V24a2 2 0 004 0v-4.002h4V54z" />
    </svg>
  );
}
