//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: shuffle.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function ShuffleIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--shuffle', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M7.32 18.28c11 0 16.4 4.27 20.86 9 .45.48.9 1 1.35 1.47.29.33.58.67.88 1 .6.67 1.19 1.34 1.8 2 .45.49.91 1 1.38 1.45 3.93 4 8.71 7.17 17.91 7.54l-2.15-2.15-.51-.59a2.001 2.001 0 012.83-2.83l5.68 5.68a2.89 2.89 0 010 4.15l-5.68 5.69a2 2 0 01-1.42.58 2 2 0 01-1.41-.58 2 2 0 010-2.83l3.08-3.08c-10.78-.32-16.58-4.22-21-8.57-.48-.48-.94-1-1.39-1.44-.74-.79-1.43-1.58-2.12-2.35l-.58-.65c-.45-.51-.89-1-1.34-1.49-4.15-4.48-8.56-8-18.17-8a2 2 0 110-4zm18.2 14.95l.43.48.9 1c.44.53.89 1.02 1.36 1.52-4.45 4.76-9.84 9-20.85 9a2 2 0 110-4c9.6 0 14-3.52 18.16-8zm26.14-20.39l5.68 5.68a2.89 2.89 0 01.01 4.09l-5.68 5.69a2 2 0 01-1.42.58 2 2 0 01-1.41-.58 2 2 0 010-2.83l2.71-2.71c-9.21.37-14 3.57-17.92 7.54-.45-.48-.89-1-1.34-1.48l-.35-.4-1-1.11c4.38-4.35 10.17-8.25 20.95-8.57L50 16.84l-1.17-1.17a2.001 2.001 0 012.83-2.83z"
      />
    </svg>
  );
}
