//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: shuffle.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function ShuffleIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--shuffle', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M35.541 27.431a2.001 2.001 0 01.005-2.829l4.286-4.27A7.949 7.949 0 0145.478 18h7.694l-2.586-2.586a2 2 0 012.828-2.828l6 6a2 2 0 010 2.828l-6 6a2 2 0 01-2.828-2.828L53.172 22h-7.694a4.024 4.024 0 00-2.822 1.166l-4.286 4.27a2.002 2.002 0 01-2.829-.005zm17.873 9.155a2 2 0 10-2.828 2.828L53.172 42H45.48a3.973 3.973 0 01-2.824-1.167L32.552 30.756a1.183 1.183 0 00-.337-.336L22.1 20.334C20.502 18.742 18.39 18 15.452 18H6a2 2 0 100 4h9.452c2.338 0 3.245.59 3.824 1.167l8.862 8.837-8.86 8.83A3.98 3.98 0 0116.452 42H6a2 2 0 100 4h10.453a7.955 7.955 0 005.648-2.332l8.87-8.839 8.861 8.836A7.947 7.947 0 0045.48 46h7.692l-2.586 2.586a2 2 0 002.828 2.828l6-6a2 2 0 000-2.828l-6-6z"
        clipRule="evenodd"
      />
    </svg>
  );
}
