//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: smart-wifi.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function SmartWifiIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--smart-wifi', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path d="M39.073 35.929a2 2 0 11-2.828 2.829 6.002 6.002 0 00-8.487 0 2 2 0 01-2.828-2.83 10.001 10.001 0 0114.143 0zM32 41a3 3 0 100 6 3 3 0 000-6zm26.933-7.47A3.988 3.988 0 0155.239 36H54v18a4.005 4.005 0 01-4 4H14a4.004 4.004 0 01-4-4V36H8.764a4 4 0 01-2.828-6.828L27.759 7.349a5.998 5.998 0 018.484 0l21.824 21.823a3.988 3.988 0 01.867 4.359zM55.239 32L33.415 10.177a2.049 2.049 0 00-2.828 0L8.764 32h5.237v22h36V32h5.238zm-35.965-1.727a2 2 0 002.828 2.828 14 14 0 0119.799 0 2 2 0 002.828-2.828 17.996 17.996 0 00-25.455 0z" />
    </svg>
  );
}
