//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: smartwatch.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function SmartwatchIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--smartwatch', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M14.23 9.276A6 6 0 0119.975 5h8.048a6 6 0 015.747 4.276l1.86 6.2A7.99 7.99 0 0139 22v20a7.99 7.99 0 01-3.37 6.524l-1.86 6.2A6 6 0 0128.025 59h-8.048a6 6 0 01-5.747-4.276l-1.86-6.2A7.99 7.99 0 019 42V22a7.99 7.99 0 013.37-6.524l1.86-6.2zM16.987 50l1.073 3.575A2 2 0 0019.976 55h8.048a2 2 0 001.915-1.425L31.012 50H16.988zM29.94 10.425L31.012 14H16.988l1.073-3.575A2 2 0 0119.976 9h8.048a2 2 0 011.915 1.425zM17 18a4 4 0 00-4 4v20a4 4 0 004 4h14a4 4 0 004-4V22a4 4 0 00-4-4H17zm33.315 16.87c.622-2.384.671-5.785-1.98-9.76a2 2 0 013.33-2.22c3.349 5.026 3.398 9.624 2.52 12.99a15.416 15.416 0 01-1.617 3.9c-.272.46-.52.824-.706 1.08a9.526 9.526 0 01-.303.394l-.025.03-.009.01-.003.004-.002.002s.014-.017-.002.002a2 2 0 01-3.043-2.595l1.84-3.837zm0 0a11.417 11.417 0 01-1.195 2.882 9.247 9.247 0 01-.62.923l-.018.022-.005.007 1.838-3.834z"
        clipRule="evenodd"
      />
      <path d="M42.336 29.11c1.15 1.725 1.044 3.255.854 4.073-.143.614-.216.728-.441 1.08-.075.116-.166.258-.282.453-.467.784-.601 2.089.232 2.803a2 2 0 002.82-.217l.003-.004.003-.004.008-.008.018-.022a4.14 4.14 0 00.188-.245c.11-.151.253-.36.407-.622.306-.52.67-1.27.914-2.204.504-1.929.454-4.527-1.396-7.302a2 2 0 00-3.328 2.219z" />
    </svg>
  );
}
