//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: smiley-sad.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function SmileySadIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--smiley-sad', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M32 4C16.536 4 4 16.536 4 32s12.536 28 28 28 28-12.536 28-28C59.983 16.543 47.457 4.017 32 4zm0 51.692C18.915 55.692 8.308 45.085 8.308 32S18.915 8.308 32 8.308 55.692 18.915 55.692 32C55.678 45.079 45.08 55.678 32 55.692zM20.154 25.538a3.23 3.23 0 116.461 0 3.23 3.23 0 01-6.461 0zm17.23 0a3.23 3.23 0 116.462 0 3.23 3.23 0 01-6.461 0zm7.174 17.404c-.663.987-2 1.251-2.989.589a17.163 17.163 0 00-19.138 0 2.154 2.154 0 11-2.4-3.578 21.474 21.474 0 0123.938 0c.988.663 1.252 2 .59 2.989z"
        clipRule="evenodd"
      />
    </svg>
  );
}
