//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: smiley-happy.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function SmileyHappyIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--smiley-happy', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 65"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M32 4.5c-15.464 0-28 12.536-28 28s12.536 28 28 28 28-12.536 28-28c-.017-15.457-12.543-27.983-28-28zm0 51.692c-13.085 0-23.692-10.607-23.692-23.692S18.915 8.808 32 8.808 55.693 19.415 55.693 32.5C55.678 45.579 45.079 56.177 32 56.192zm16.517-18.77a17.237 17.237 0 01-33.034 0 2.154 2.154 0 014.128-1.228 12.929 12.929 0 0024.777 0 2.154 2.154 0 014.129 1.228zM20.154 26.039a3.23 3.23 0 116.461 0 3.23 3.23 0 01-6.461 0zm17.23 0a3.23 3.23 0 116.462 0 3.23 3.23 0 01-6.461 0z"
        clipRule="evenodd"
      />
    </svg>
  );
}
