//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: snowflake.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function SnowflakeIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--snowflake', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M56.279 29.58a2.166 2.166 0 101.701-3.984l-6.178-2.639 5.123-2.988a2.167 2.167 0 10-2.183-3.743l-4.88 2.846.752-6.234a2.166 2.166 0 00-4.302-.519l-1.144 9.491-5.106 2.979a10.824 10.824 0 00-5.895-3.404V15.75l7.8-5.85a2.166 2.166 0 10-2.6-3.466l-5.2 3.9V6a2.167 2.167 0 10-4.333 0v4.334l-5.2-3.9a2.166 2.166 0 10-2.6 3.466l7.8 5.85v5.635a10.825 10.825 0 00-5.895 3.404l-5.107-2.979-1.144-9.49a2.166 2.166 0 00-4.301.518l.75 6.234-4.878-2.846a2.167 2.167 0 10-2.184 3.743l5.123 2.988-6.178 2.64a2.166 2.166 0 101.702 3.984l9.14-3.904 4.886 2.85a10.662 10.662 0 000 6.945l-4.887 2.85-9.14-3.902a2.166 2.166 0 10-1.7 3.984l6.177 2.639-5.123 2.988a2.167 2.167 0 002.184 3.743l4.879-2.846-.751 6.235a2.165 2.165 0 104.301.518l1.144-9.491 5.107-2.979a10.824 10.824 0 005.895 3.404v5.635l-7.8 5.85a2.166 2.166 0 002.6 3.466l5.2-3.9V58a2.167 2.167 0 104.333 0v-4.333l5.2 3.9a2.167 2.167 0 102.6-3.466l-7.8-5.85v-5.636a10.825 10.825 0 005.895-3.404l5.106 2.98 1.144 9.49a2.166 2.166 0 104.302-.518l-.752-6.235 4.88 2.846a2.167 2.167 0 102.183-3.743l-5.186-3.025 6.058-2.693a2.166 2.166 0 10-1.76-3.959l-8.912 3.96-4.873-2.842a10.66 10.66 0 000-6.944l4.887-2.85 9.14 3.903zM32 38.5a6.5 6.5 0 116.5-6.5 6.507 6.507 0 01-6.5 6.5z"
        clipRule="evenodd"
      />
    </svg>
  );
}
