//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: sorter.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function SorterIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--sorter', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M33.153 42.686L20.301 55.414a2.034 2.034 0 01-2.857 0L4.592 42.686a1.986 1.986 0 010-2.828 2.034 2.034 0 012.856 0l9.405 9.314V10c0-1.105.904-2 2.02-2a2.01 2.01 0 012.02 2v39.172l9.404-9.314a2.033 2.033 0 012.856 0 1.986 1.986 0 010 2.828zm-2.306-21.372L43.699 8.586a2.034 2.034 0 012.857 0l12.852 12.728a1.986 1.986 0 010 2.828 2.034 2.034 0 01-2.856 0l-9.405-9.314V54c0 1.105-.904 2-2.02 2a2.01 2.01 0 01-2.02-2V14.828l-9.404 9.314a2.033 2.033 0 01-2.856 0 1.986 1.986 0 010-2.828z"
        clipRule="evenodd"
      />
    </svg>
  );
}
