//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: speedometer-normal.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function SpeedometerNormalIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--speedometer-normal', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path d="M2.67 50.52c-1.34 0-2.48-1.03-2.58-2.39-.06-.79-.09-1.6-.09-2.39 0-4.06.78-8.01 2.33-11.73A2.593 2.593 0 117.12 36a25.345 25.345 0 00-1.85 11.74c.11 1.43-.96 2.67-2.38 2.78h-.2zm55.92.03h-.22a2.59 2.59 0 01-2.37-2.8c.06-.69.09-1.4.09-2.11 0-14.04-11.42-25.46-25.46-25.46-4.81 0-9.49 1.35-13.54 3.9a2.59 2.59 0 01-2.76-4.38 30.55 30.55 0 0116.3-4.69c16.89 0 30.64 13.74 30.64 30.64 0 .85-.04 1.7-.1 2.53a2.598 2.598 0 01-2.58 2.38zM30.96 48.8c-.6 0-1.2-.21-1.69-.62L5.77 28.04a2.585 2.585 0 01-.28-3.65 2.585 2.585 0 013.65-.28l23.5 20.14c1.09.93 1.21 2.57.28 3.65-.51.6-1.24.91-1.97.91z" />
    </svg>
  );
}
