//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: speedometer-dots.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function SpeedometerDotsIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--speedometer-dots', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path d="M4.32 31.496a2.371 2.371 0 00-.039.781 25.29 25.29 0 00-.015.946c0 7.414 2.937 14.148 7.707 19.109.836.867 2.18.98 3.152.27l3.629-2.668a2.401 2.401 0 00-2.844-3.868l-1.86 1.368a22.694 22.694 0 01-4.956-13.036H12a2.399 2.399 0 000-4.796H9.352a22.73 22.73 0 015.414-11.438l1.972 1.973a2.407 2.407 0 003.395 0 2.4 2.4 0 000-3.395l-1.828-1.828a22.868 22.868 0 0111.293-4.39v2.808a2.4 2.4 0 104.8 0v-2.809c2.04.211 3.993.688 5.832 1.391a2.404 2.404 0 003.102-1.383 2.404 2.404 0 00-1.383-3.101A27.79 27.79 0 0032 5.602a27.711 27.711 0 00-18.309 6.87 2.412 2.412 0 00-1.14 1.055c-4.727 4.633-7.797 10.946-8.23 17.97zM51.031 12.97a2.407 2.407 0 010 3.394L32.363 35.031a2.4 2.4 0 11-3.394-3.394l18.668-18.668a2.4 2.4 0 013.394 0zm2.38 6.558a2.4 2.4 0 013.237 1.024 27.412 27.412 0 013.082 12.672c0 7.414-2.933 14.148-7.707 19.109-.832.867-2.18.98-3.148.27l-3.629-2.668a2.398 2.398 0 112.84-3.868l1.86 1.368a22.64 22.64 0 004.956-13.036h-4.238a2.399 2.399 0 010-4.796h3.98a22.515 22.515 0 00-2.257-6.84 2.4 2.4 0 011.023-3.235zm0 0" />
    </svg>
  );
}
