//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: split.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function SplitIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--split', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path d="M22.458 34H6a2 2 0 010-4h16.766l9.587-9.596A7.95 7.95 0 0138 18.072h15l-2.586-2.586a2 2 0 012.828-2.828l6 6a2 2 0 010 2.828l-6 6a2 2 0 01-2.828-2.828L53 22.072H38a4.024 4.024 0 00-2.823 1.166l-8.9 8.909 8.9 8.779A4.023 4.023 0 0038 42.092h15l-2.586-2.586a2 2 0 012.828-2.828l6 6a2 2 0 010 2.828l-6 6a2 2 0 11-2.828-2.828L53 46.092H38a7.949 7.949 0 01-5.647-2.332L22.458 34z" />
    </svg>
  );
}
