//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: spyware.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function SpywareIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--spyware', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path d="M30 22.864V37.33c0 .833.372 1.25 1.113 1.25.702 0 1.387-.256 1.97-.735.611-.491.917-1.006.917-1.546V21.833a3.046 3.046 0 00-.481-1.436c-.5-.931-1.002-1.397-1.504-1.397-.348.025-.675.209-.917.515a4.098 4.098 0 00-.782 1.435A5.854 5.854 0 0030 22.864zm3.681 20.47a2.352 2.352 0 00-.429-1.087c-.42-.66-.827-.99-1.218-.99-.304.015-.59.154-.802.387-.287.295-.51.654-.653 1.05-.173.44-.261.912-.26 1.389 0 .611.316.917.947.917.586 0 1.16-.185 1.648-.532.511-.354.767-.732.767-1.134z" />
      <path
        fillRule="evenodd"
        d="M34.418 7.387a31.732 31.732 0 0017.65 6.614 4.003 4.003 0 013.932 4v10c0 22.616-18.705 28.7-22.455 29.69a6.04 6.04 0 01-3.092 0C26.705 56.702 8 50.618 8 28.002V18a4.003 4.003 0 013.933-4 31.731 31.731 0 0017.65-6.614 3.95 3.95 0 014.835 0zm-1.896 46.438C37.092 52.618 52 47.19 52 28V18c-.038 0-.075 0-.113-.003a35.711 35.711 0 01-19.916-7.446 35.374 35.374 0 01-19.858 7.446A2.142 2.142 0 0112 18h-.003L12 28c0 19.19 14.907 24.618 19.477 25.825.342.091.702.091 1.045 0z"
        clipRule="evenodd"
      />
    </svg>
  );
}
