//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: star.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function StarIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--star', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M45.6 54.92a1.911 1.911 0 01-.93-.23L32 48l-12.67 6.69a2 2 0 01-2.1-.15 2 2 0 01-.8-2l2.42-14.1L8.6 28.49a2 2 0 011.11-3.41L23.87 23l6.34-12.83a2 2 0 013.58 0L40.13 23l14.16 2.06a2 2 0 011.11 3.41l-10.25 10 2.42 14.1a2 2 0 01-2 2.34l.03.01zM32 43.78a2 2 0 01.93.22l10 5.27L41 38.12a2 2 0 01.57-1.77l8.1-7.89-11.16-1.63A2 2 0 0137 25.74L32 15.6l-5 10.14a2 2 0 01-1.5 1.09l-11.2 1.63 8.1 7.89a2 2 0 01.6 1.77l-1.94 11.15 10-5.27a2 2 0 01.94-.22z"
      />
    </svg>
  );
}
