//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: star-filled.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function StarFilledIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--star-filled', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M55.4 28.49l-10.25 10 2.42 14.1a2 2 0 0 1-2 2.34 1.913 1.913 0 0 1-.93-.23L32 48l-12.67 6.69a2 2 0 0 1-2.1-.15 2 2 0 0 1-.8-2l2.42-14.1L8.6 28.49a2 2 0 0 1 1.11-3.41L23.87 23l6.34-12.83a2 2 0 0 1 3.58 0L40.13 23l14.16 2.06a2 2 0 0 1 1.11 3.41v.02z"
      />
    </svg>
  );
}
