//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: star.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function StarIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--star', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M59.763 25.024a4.236 4.236 0 00-4.065-2.915h-14.67L36.046 7.875a4.291 4.291 0 00-8.102-.001l-4.982 14.235H8.292a4.292 4.292 0 00-2.606 7.701l11.987 9.167-4.921 14.763a4.292 4.292 0 006.584 4.836l12.659-9.143 12.66 9.143a4.228 4.228 0 005.051-.02 4.227 4.227 0 001.532-4.817l-4.921-14.762 11.987-9.167a4.237 4.237 0 001.459-4.786zM43.712 35.568a4.295 4.295 0 00-1.466 4.767l4.921 14.762-12.66-9.143a4.284 4.284 0 00-5.024 0l-12.66 9.143 4.922-14.764a4.294 4.294 0 00-1.465-4.765L8.293 26.4h14.67a4.294 4.294 0 004.05-2.873l4.982-14.235 4.982 14.234a4.294 4.294 0 004.051 2.874h14.67l-11.986 9.167z"
        clipRule="evenodd"
      />
    </svg>
  );
}
