//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: star-filled.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function StarFilledIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--star-filled', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path d="M28.202 7.746c1.223-3.661 6.373-3.661 7.596 0l4.974 14.879h15.213c3.863 0 5.49 4.954 2.386 7.267l-12.145 9.05 4.922 14.726c1.233 3.689-2.935 6.818-6.102 4.582L32 49.036 18.954 58.25c-3.167 2.236-7.335-.893-6.102-4.582l4.922-14.726-12.145-9.05c-3.103-2.313-1.477-7.267 2.386-7.267h15.213l4.974-14.88z" />
    </svg>
  );
}
