//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: store.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function StoreIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--store', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M52 8a8 8 0 016 2.69A8 8 0 0160 16v32a8 8 0 01-8 8H12a8 8 0 01-8-8V16a8 8 0 018-8zm-6 28h-4a2 2 0 00-2 2v14h8V38a2 2 0 00-2-2zm10-10.54a6 6 0 01-8 0 6 6 0 01-8 0 6 6 0 01-8 0 6 6 0 01-8 0 6 6 0 01-8 0 6 6 0 01-8 0V48a4 4 0 004 4h24V38a6 6 0 016-6h4a6 6 0 016 6v14a4 4 0 004-4zM26 32a6 6 0 016 6v4a6 6 0 01-6 6h-8a6 6 0 01-6-6v-4a6 6 0 016-6zm0 4h-8a2 2 0 00-2 2v4a2 2 0 002 2h8a2 2 0 002-2v-4a2 2 0 00-2-2zm28-23h-4v8a2 2 0 104 0v-8zm-8 0h-4v8a2 2 0 104 0v-8zm-8 0h-4v8a2 2 0 104 0v-8zm-8 0h-4v8a2 2 0 104 0v-8zm-8 0h-4v8a2 2 0 104 0v-8zm-8 0h-4v8a2 2 0 104 0v-8z"
      />
    </svg>
  );
}
