//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: stream.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function StreamIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--stream', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M8.07 18.499a5 5 0 00-5 5v18a5 5 0 005 5h46a5 5 0 005-5v-18a5 5 0 00-5-5h-46zm13.424 19.748c-.198.162-.378.252-.558.252h-5.4c-.63 0-1.242-1.098-1.242-1.44V26.96c0-.576.918-1.17 1.8-1.17.468 0 .702.216.702.648v9.54h4.68c.45 0 .666.216.666.63 0 .648-.288 1.296-.648 1.638zm3.288.36c-.63 0-1.242-1.098-1.242-1.44V26.96c0-.576.918-1.17 1.8-1.17.468 0 .702.216.702.648v10.206c0 .99-.63 1.962-1.26 1.962zm9.601-1.206c-.288.738-.72 1.206-1.206 1.206h-.522c-.342 0-.666-.234-.99-.702a2.763 2.763 0 01-.27-.522L27.58 27.375a1.265 1.265 0 01-.108-.414c0-.576.918-1.17 1.8-1.17.378 0 .594.144.684.45l3.042 8.622 2.79-8.064c.162-.522.99-1.008 1.782-1.008.468 0 .702.216.702.648 0 .306-.054.594-.162.882L34.383 37.4zm13.161.846c-.198.162-.378.252-.558.252h-6.102c-.63 0-1.242-1.098-1.242-1.44v-9.99c0-.576.918-1.17 1.8-1.17h5.922c.45 0 .666.216.666.63 0 .648-.288 1.296-.648 1.638-.198.162-.378.252-.558.252h-4.68v2.538h4.41c.414 0 .63.198.63.594 0 .882-.558 1.746-1.134 1.746h-3.906v2.682h5.382c.45 0 .666.216.666.63 0 .648-.288 1.296-.648 1.638z"
        clipRule="evenodd"
      />
    </svg>
  );
}
