//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: suitcase.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function SuitcaseIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--suitcase', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M52 18H42v-6a4.004 4.004 0 00-4-4H26a4.004 4.004 0 00-4 4v6H12a8.01 8.01 0 00-8 8v22a8.01 8.01 0 008 8h40a8.01 8.01 0 008-8V26a8.01 8.01 0 00-8-8zm-6 4v30H18V22h28zM26 12h12v6H26v-6zM8 48V26a4.004 4.004 0 014-4h2v30h-2a4.004 4.004 0 01-4-4zm48 0a4.004 4.004 0 01-4 4h-2V22h2a4.004 4.004 0 014 4v22z"
        clipRule="evenodd"
      />
    </svg>
  );
}
