//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: summary.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function SummaryIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--summary', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M48 4H20a8.01 8.01 0 00-8 8v44a4.004 4.004 0 004 4h28a8.01 8.01 0 008-8V8a4.004 4.004 0 00-4-4zm0 48a4.004 4.004 0 01-4 4l-28 .003V12a4.004 4.004 0 014-4h28v44zm-18-8a2 2 0 012-2h8a2 2 0 110 4h-8a2 2 0 01-2-2zm0-12a2 2 0 012-2h8a2 2 0 110 4h-8a2 2 0 01-2-2zm0-12a2 2 0 012-2h8a2 2 0 110 4h-8a2 2 0 01-2-2zm-8 12a2 2 0 114 0 2 2 0 01-4 0zm0-12a2 2 0 114 0 2 2 0 01-4 0zm0 24a2 2 0 114 0 2 2 0 01-4 0z"
        clipRule="evenodd"
      />
    </svg>
  );
}
