//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: sync.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function SyncIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--sync', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M10.334 34.167A2.167 2.167 0 018.167 32a23.83 23.83 0 0141.167-16.354v-5.313a2.167 2.167 0 114.333 0v10.834c0 1.196-.97 2.166-2.167 2.166H40.667a2.167 2.167 0 010-4.333h5.864a19.498 19.498 0 00-34.03 13c0 1.197-.97 2.167-2.167 2.167zm43.333-4.334c-1.197 0-2.167.97-2.167 2.167a19.498 19.498 0 01-34.03 13h5.864a2.167 2.167 0 100-4.334H12.5c-1.196 0-2.166.97-2.166 2.167v10.834a2.167 2.167 0 104.333 0v-5.313A23.83 23.83 0 0055.834 32c0-1.197-.97-2.167-2.167-2.167z"
        clipRule="evenodd"
      />
    </svg>
  );
}
