//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: tablet.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function TabletIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--tablet', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M44 4H20a8.01 8.01 0 00-8 8v40a8.01 8.01 0 008 8h24a8.01 8.01 0 008-8V12a8.01 8.01 0 00-8-8zm-28 8a4.004 4.004 0 014-4h24a4.004 4.004 0 014 4v32H16V12zm32 40a4.004 4.004 0 01-4 4H20a4.004 4.004 0 01-4-4v-4h32v4zm-18 0a2 2 0 114 0 2 2 0 01-4 0z"
        clipRule="evenodd"
      />
    </svg>
  );
}
