//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: tag.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function TagIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--tag', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path d="M38 55.512a7.975 7.975 0 01-5.656-2.34L9.172 30A3.972 3.972 0 018 27.171V12a4 4 0 014-4h15.171A3.972 3.972 0 0130 9.172l23.172 23.172a8.007 8.007 0 010 11.312l-9.516 9.516A7.976 7.976 0 0138 55.512zM12 12v15.171l23.172 23.173a4.006 4.006 0 005.656 0l9.516-9.516a4 4 0 000-5.656L27.172 12H12z" />
      <path d="M21 27a6 6 0 110-12 6 6 0 010 12zm0-8a2 2 0 100 4 2 2 0 000-4z" />
    </svg>
  );
}
