//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: temperature.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function TemperatureIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--temperature', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path d="M28.002 40.35V16a2 2 0 00-4 0v24.35a6 6 0 104 0zm-2 7.65a2 2 0 110-4 2 2 0 010 4zm14-32a2 2 0 012-2h8a2 2 0 010 4h-8a2 2 0 01-2-2zm0 8a2 2 0 012-2h4a2 2 0 010 4h-4a2 2 0 01-2-2zm12 8a2 2 0 01-2 2h-8a2 2 0 110-4h8a2 2 0 012 2zm-16-18a10 10 0 00-20 0v22.22a13.875 13.875 0 00-3.92 11.284 14.028 14.028 0 0012.343 12.41 14.113 14.113 0 0010.918-3.485 13.979 13.979 0 00.659-20.207V14zm-3.33 39.45a9.992 9.992 0 01-16.646-7.992 9.993 9.993 0 013.31-6.895l.666-.596V14a6 6 0 1112 0v23.967l.665.596a9.979 9.979 0 01.006 14.886l-.001.001z" />
    </svg>
  );
}
