//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: thinking.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function ThinkingIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--thinking', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path d="M35 4a23.028 23.028 0 00-22.987 22.225l-4.55 5.118A4 4 0 0010.455 38H12v8a4.005 4.005 0 004 4h6a4.004 4.004 0 014 4v2a4.005 4.005 0 004 4h16a4.004 4.004 0 004-4V46l.036-1.093A24.042 24.042 0 0058 27 23.026 23.026 0 0035 4zm12.4 37.897a4.048 4.048 0 00-1.4 3.038V56H30v-2a8.01 8.01 0 00-8-8h-6V34h-5.546L16 27.76V27a19 19 0 0138 0 20.264 20.264 0 01-6.6 14.897zM36 39a2 2 0 11-4 0 2 2 0 014 0zm5.305-20.046a7.988 7.988 0 01-1.203 9.773l-4.688 4.687a2 2 0 01-2.828-2.828l4.687-4.688a3.995 3.995 0 00.602-4.885 3.448 3.448 0 00-5.395-.665l-1.066 1.066a2 2 0 01-2.828-2.828l1.066-1.066a7.448 7.448 0 0111.653 1.434z" />
    </svg>
  );
}
