//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: time-waiting.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function TimeWaitingIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--time-waiting', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M32 54a3 3 0 1 1 0 6 3 3 0 0 1 0-6zm18-7a3 3 0 1 1 0 6 3 3 0 0 1 0-6zm-36 0a3 3 0 1 1 0 6 3 3 0 0 1 0-6zm18-24a2 2 0 0 1 2 2v7h12a2 2 0 1 1 0 4H32a2 2 0 0 1-2-2v-9a2 2 0 0 1 2-2zM7 29a3 3 0 1 1 0 6 3 3 0 0 1 0-6zM32 4c8.505 0 15.35 2.522 20.414 7.586C57.478 16.65 60 23.496 60 32a2 2 0 1 1-4 0c0-7.495-2.145-13.316-6.414-17.586C45.316 10.144 39.496 8 32 8a2 2 0 1 1 0-4zm-18 7a3 3 0 1 1 0 6 3 3 0 0 1 0-6z"
      />
    </svg>
  );
}
