//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: train.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function TrainIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--train', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path d="M54 44V12a8.01 8.01 0 00-8-8H18a8.01 8.01 0 00-8 8v32a4.004 4.004 0 004 4h3.73l-7.265 8.72a2 2 0 103.072 2.56L16.27 56h31.46l2.734 3.28a2 2 0 003.072-2.56L46.27 48H50a4.004 4.004 0 004-4zm-3.997-14H34V16h16l.002 14zM18 8h28a4.004 4.004 0 014 4H14a4.004 4.004 0 014-4zm-4 8h16v14H14V16zm5.603 36l3.333-4h18.128l3.333 4H19.604zM14 44V34h36.002v10H14zm32-5a3 3 0 11-6 0 3 3 0 016 0zm-22 0a3 3 0 11-6 0 3 3 0 016 0z" />
    </svg>
  );
}
