//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: trailer.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function TrailerIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--trailer', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M58.102 23.833a3.975 3.975 0 00-3.891-.175l-6.782 3.391a8.035 8.035 0 00-4.472-4.476A10.994 10.994 0 1026.521 22h-4.604a8 8 0 10-13.323.772A8.003 8.003 0 004 30v10a8.01 8.01 0 008 8h15.172l-8.586 8.586a2 2 0 102.828 2.828L30 50.828l8.586 8.586a2 2 0 002.828-2.828L32.828 48H40a8.008 8.008 0 007.429-5.05l6.782 3.392A4 4 0 0060 42.764V27.236a3.975 3.975 0 00-1.898-3.403zM28 15a7 7 0 117 7 7.008 7.008 0 01-7-7zm-13-1a4 4 0 110 8 4 4 0 010-8zm29 26a4.004 4.004 0 01-4 4H12a4.004 4.004 0 01-4-4V30a4.004 4.004 0 014-4h28a4.004 4.004 0 014 4v10zm12 2.764l-8-4v-7.528l8-4v15.528z"
        clipRule="evenodd"
      />
    </svg>
  );
}
