//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: transfer.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function TransferIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--transfer', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M46 41a3 3 0 11-6 0 3 3 0 016 0zm-25-3a3 3 0 100 6 3 3 0 000-6zm39-16v6a4.004 4.004 0 01-4 4h-2v14a4.004 4.004 0 01-4 4v4a4.004 4.004 0 01-4 4h-4a4.004 4.004 0 01-4-4v-4H26v4a4.004 4.004 0 01-4 4h-4a4.004 4.004 0 01-4-4v-4a4.004 4.004 0 01-4-4V32H8a4.004 4.004 0 01-4-4v-6a4.004 4.004 0 014-4h2v-4a8.01 8.01 0 018-8h28a8.01 8.01 0 018 8v4h2a4.004 4.004 0 014 4zM30 32V18H14v14h16zm4 0h16.001v-1.988L50 30l.001-.012v-9.983L50 20v-2H34v14zM14 14h36a4.004 4.004 0 00-4-4H18a4.004 4.004 0 00-4 4zm-4 14v-6H8v6h2zm12 22h-4v4h4v-4zm24 0h-4v4h4v-4zm4.002-4V36H14v10h36.002zM56 22h-2v6h2v-6z"
        clipRule="evenodd"
      />
    </svg>
  );
}
