//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: trash.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function TrashIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--trash', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M38 4a6 6 0 016 6v2h12a2 2 0 110 4h-4v38a6 6 0 01-6 6H18a6 6 0 01-6-6V16H8a2 2 0 110-4h12v-2a6 6 0 016-6zm10 12H16v38a2 2 0 002 2h28a2 2 0 002-2V16zm-24 6a2 2 0 012 2v24a2 2 0 11-4 0V24a2 2 0 012-2zm8 0a2 2 0 012 2v24a2 2 0 11-4 0V24a2 2 0 012-2zm8 0a2 2 0 012 2v24a2 2 0 11-4 0V24a2 2 0 012-2zM38 8H26a2 2 0 00-2 2v2h16v-2a2 2 0 00-2-2z"
      />
    </svg>
  );
}
