//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: tv.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function TvIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--tv', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M52 10H12a8.01 8.01 0 00-8 8v22a8.01 8.01 0 008 8h40a8.01 8.01 0 008-8V18a8.01 8.01 0 00-8-8zm4 30a4.005 4.005 0 01-4 4H12a4.005 4.005 0 01-4-4V18a4.005 4.005 0 014-4h40a4.005 4.005 0 014 4v22zM44 52a2 2 0 01-2 2H22a2 2 0 110-4h20a2 2 0 012 2zM31 19.993a3.62 3.62 0 01-.633 2.07 1.74 1.74 0 01-1.381.937H25v12.993a3.62 3.62 0 01-.633 2.069c-.27.528-.791.881-1.381.938-.5 0-.998-.359-1.497-1.076a2.403 2.403 0 01-.489-1.13V23h-4.014c-.5 0-.998-.359-1.497-1.076a2.402 2.402 0 01-.489-1.13c0-.442.302-.851.906-1.228A3.656 3.656 0 0117.878 19h12c.748 0 1.122.331 1.122.993zm18-.031c0 .447-.082.89-.24 1.309L43.23 37.21a3.85 3.85 0 01-.788 1.309 1.388 1.388 0 01-1.002.48h-.775c-.499 0-.989-.346-1.47-1.041-.165-.24-.3-.5-.4-.775l-5.663-15.832a1.823 1.823 0 01-.16-.615 1.5 1.5 0 01.84-1.189 3.292 3.292 0 011.83-.547.922.922 0 011.016.668L41.01 34l4.302-13.504c.183-.457.531-.83.975-1.042a3.294 3.294 0 011.67-.454c.695 0 1.042.32 1.042.962z"
        clipRule="evenodd"
      />
    </svg>
  );
}
