//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: tv-next.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function TvNextIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--tv-next', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M57.998 6v52a2 2 0 01-2 2h-6a2 2 0 01-2-2V36.35L10.921 59.51a3.22 3.22 0 01-4.257-.768l-.177-.255a3.217 3.217 0 01-.489-1.704V7.376a3.35 3.35 0 011.91-3.1 3.227 3.227 0 013.013.213l37.077 23.16V6a2 2 0 012-2h6a2 2 0 012 2z"
        clipRule="evenodd"
      />
    </svg>
  );
}
