//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: tv-pause.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function TvPauseIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--tv-pause', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path d="M54 6v52a2 2 0 01-2 2H42a2 2 0 01-2-2V6a2 2 0 012-2h10a2 2 0 012 2zM22 4H12a2 2 0 00-2 2v52a2 2 0 002 2h10a2 2 0 002-2V6a2 2 0 00-2-2z" />
    </svg>
  );
}
