//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: tv-play.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function TvPlayIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--tv-play', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M54.362 35.087L15.584 59.429A3.657 3.657 0 0110 56.275V7.59a3.657 3.657 0 015.584-3.155l38.778 24.343a3.738 3.738 0 010 6.309z"
        clipRule="evenodd"
      />
    </svg>
  );
}
