//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: tv-simple.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function TvSimpleIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--tv-simple', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M46 50a2 2 0 110 4H20a2 2 0 110-4h26zm6-40a8 8 0 018 8v22a8 8 0 01-8 8H12a8 8 0 01-8-8V18a8 8 0 018-8h40zm0 4H12a4 4 0 00-4 4v22a4 4 0 004 4h40a4 4 0 004-4V18a4 4 0 00-4-4z"
      />
    </svg>
  );
}
