//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: tv-stop.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function TvStopIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--tv-stop', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path d="M8 14a6 6 0 016-6h36a6 6 0 016 6v36a6 6 0 01-6 6H14a6 6 0 01-6-6V14z" />
    </svg>
  );
}
