//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: vcard.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function VcardIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--vcard', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M31.643 27.077a6.933 6.933 0 01-1.067 3.698c3.74.758 6.425 4.02 6.424 7.802v.885C37 41.416 35.401 43 33.429 43H15.57C13.6 43 12 41.416 12 39.462v-.885c-.001-3.783 2.684-7.044 6.424-7.802a6.933 6.933 0 01-1.067-3.698c0-3.909 3.198-7.077 7.143-7.077s7.143 3.168 7.143 7.077zM28 27.5a3.5 3.5 0 10-7 0 3.5 3.5 0 007 0zM31.583 39c.783 0 1.417-.537 1.417-1.2v-.6c.002-2.265-2.116-4.122-4.788-4.2-2.128 1.581-5.31 1.581-7.438 0-2.666.084-4.776 1.94-4.774 4.2v.6c0 .663.634 1.2 1.417 1.2h14.166z"
        clipRule="evenodd"
      />
      <path d="M39 21h11a2 2 0 110 4H39a2 2 0 110-4zm11 7H39a2 2 0 100 4h11a2 2 0 100-4z" />
      <path
        fill-rule="evenodd"
        d="M10 12h44a6 6 0 016 6v28a6 6 0 01-6 6H10a6 6 0 01-6-6V18a6 6 0 016-6zm0 4h44a2 2 0 012 2v28a2 2 0 01-2 2H10a2 2 0 01-2-2V18a2 2 0 012-2z"
        clip-rule="evenodd"
      />
    </svg>
  );
}
