//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: video-conference.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function VideoConferenceIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--video-conference', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path d="M52 12H12a8.01 8.01 0 00-8 8v20a8.01 8.01 0 008 8h18v4h-8a2 2 0 000 4h20a2 2 0 000-4h-8v-4h18a8.01 8.01 0 008-8V20a8.01 8.01 0 00-8-8zM20 44a8.018 8.018 0 016.28-7.81 9.945 9.945 0 0011.44 0A8.018 8.018 0 0144 44H20zm6-16a6 6 0 116 6 6.006 6.006 0 01-6-6zm30 12a4.005 4.005 0 01-4 4h-4a12.04 12.04 0 00-7.326-11.044 10 10 0 10-17.348 0A12.04 12.04 0 0016 44h-4a4.004 4.004 0 01-4-4V20a4.004 4.004 0 014-4h40a4.005 4.005 0 014 4v20z" />
    </svg>
  );
}
