//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: video.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function VideoIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--video', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M52 12H12a8.01 8.01 0 00-8 8v24a8.01 8.01 0 008 8h40a8.01 8.01 0 008-8V20a8.01 8.01 0 00-8-8zm4 32a4.004 4.004 0 01-4 4H12a4.004 4.004 0 01-4-4V20a4.004 4.004 0 014-4h40a4.004 4.004 0 014 4v24zM40.346 28.608l-10.227-6.392A4 4 0 0024 25.608v12.784a4 4 0 006.12 3.392l10.226-6.391a4 4 0 000-6.785zM28 38.392V25.608L38.227 32 28 38.392z"
        clipRule="evenodd"
      />
    </svg>
  );
}
