//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: voicemail.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function VoicemailIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--voicemail', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M48 21a12 12 0 00-9 20H25a12 12 0 10-9 4h32c6.627 0 12-5.373 12-12s-5.373-12-12-12zM16 41a8 8 0 110-16 8 8 0 010 16zm32 0a8 8 0 110-16 8 8 0 010 16z"
      />
    </svg>
  );
}
