//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: voicemail.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function VoicemailIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--voicemail', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M49.333 20.084a13 13 0 00-9.75 21.666H24.417a13 13 0 10-9.75 4.334h34.666c7.18 0 13-5.82 13-13s-5.82-13-13-13zM14.667 41.75a8.667 8.667 0 110-17.333 8.667 8.667 0 010 17.333zm34.666 0a8.667 8.667 0 110-17.333 8.667 8.667 0 010 17.333z"
        clipRule="evenodd"
      />
    </svg>
  );
}
