//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: volume.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function VolumeIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--volume', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M33.658 9.332a4.32 4.32 0 00-4.722.94L18.103 21.105h-3.436A8.677 8.677 0 006 29.772v4.333a8.677 8.677 0 008.667 8.667h3.436l10.833 10.833a4.333 4.333 0 007.397-3.064V13.335a4.321 4.321 0 00-2.675-4.003zM32 50.542L19.897 38.437h-5.23a4.338 4.338 0 01-4.334-4.333v-4.333a4.338 4.338 0 014.334-4.334h5.23L32 13.335v37.206zm17.333-18.604a22.355 22.355 0 01-4.853 14.41 2.167 2.167 0 01-3.293-2.819A17.987 17.987 0 0045 31.94c.118-4.19-1.23-8.29-3.813-11.591a2.167 2.167 0 013.293-2.819 22.356 22.356 0 014.853 14.41zm8.667 0c0 8.077-2.559 15.697-7.02 20.91a2.167 2.167 0 01-3.293-2.819c3.8-4.439 5.98-11.032 5.98-18.09 0-7.06-2.18-13.652-5.98-18.091a2.167 2.167 0 013.293-2.819C55.44 16.242 58 23.862 58 31.94z"
        clipRule="evenodd"
      />
    </svg>
  );
}
