//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: wavelength.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function WavelengthIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--wavelength', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path d="M60 28a2 2 0 01-2 2c-2.9 0-3.608 2.241-4.532 7.355C52.658 41.848 51.546 48 45 48c-6.656 0-7.629-8.378-8.486-15.77C35.682 25.07 34.872 20 32 20c-2.872 0-3.682 5.07-4.514 12.23C26.63 39.622 25.656 48 19 48c-6.546 0-7.657-6.152-8.468-10.645C9.608 32.241 8.9 30 6 30a2 2 0 110-4c6.546 0 7.657 6.152 8.468 10.645C15.392 41.759 16.1 44 19 44c2.872 0 3.682-5.07 4.514-12.23C24.37 24.378 25.344 16 32 16c6.656 0 7.629 8.378 8.486 15.77C41.318 38.93 42.128 44 45 44c2.9 0 3.608-2.241 4.532-7.355C50.342 32.152 51.454 26 58 26a2 2 0 012 2z" />
    </svg>
  );
}
