//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: weather.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function WeatherIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--weather', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M43 16.873a9 9 0 012.933 17.512A9.468 9.468 0 0149 41.373c0 .494-.038.98-.11 1.453A6.5 6.5 0 0146 54.854v.02H12v-.015a8.5 8.5 0 01-8-8.486c0-4.544 3.882-8.617 8.083-8.523A13.046 13.046 0 0112 36.373c0-7.456 6.268-13.5 14-13.5 2.983 0 5.748.9 8.019 2.433A8.998 8.998 0 0143 16.873zm-17 10c-5.555 0-10 4.287-10 9.5 0 .347.02.689.058 1.025l.518 4.554-4.583-.103C10.1 41.806 8 44.016 8 46.373a4.5 4.5 0 004.232 4.492l.133.008H45.6l.098-.007a2.5 2.5 0 001.104-4.628l-2.269-1.39.404-2.629c.042-.277.064-.56.064-.846 0-3.037-2.462-5.5-5.439-5.5l-3.135.048-.977-2.668c-1.38-3.771-5.14-6.38-9.449-6.38zm26.99 9.962l1.438 1.39a2 2 0 01-2.779 2.877l-1.438-1.39a2 2 0 112.778-2.877zM43 20.873a5 5 0 100 10 5 5 0 000-10zm15 5a2 2 0 010 4h-2a2 2 0 110-4h2zM30.181 14.517l1.439 1.39a2 2 0 01-2.779 2.877l-1.438-1.39a2 2 0 112.778-2.877zm25.696-1.033a2 2 0 01-.049 2.828l-1.439 1.39a2 2 0 01-2.778-2.878l1.438-1.39a2 2 0 012.828.05zM40.917 9a2 2 0 012 2v2a2 2 0 11-4 0v-2a2 2 0 012-2z"
        clipRule="evenodd"
      />
    </svg>
  );
}
