//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: wireless.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function WirelessIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--wireless', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M35.85 51.333a4.333 4.333 0 11-8.666 0 4.333 4.333 0 018.666 0zm22.39-33.788c-15.543-12.727-37.903-12.727-53.445 0a2.167 2.167 0 102.744 3.353c13.946-11.42 34.01-11.42 47.956 0a2.166 2.166 0 102.745-3.353zM31.517 34a16.227 16.227 0 00-10.658 4.003 2.167 2.167 0 002.848 3.267 11.852 11.852 0 0115.62 0 2.167 2.167 0 002.848-3.267A16.227 16.227 0 0031.517 34zm0-13a29.28 29.28 0 00-18.683 6.755 2.166 2.166 0 102.77 3.332c9.222-7.672 22.605-7.672 31.827 0a2.167 2.167 0 102.77-3.332A29.28 29.28 0 0031.516 21z"
        clipRule="evenodd"
      />
    </svg>
  );
}
