//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: wireless-off.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function WirelessOffIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--wireless-off', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path d="M36 50a4 4 0 11-8 0 4 4 0 018 0zm20.667-31.19a38.874 38.874 0 00-7.446-4.78l4.259-4.684a2 2 0 00-2.96-2.692l-5.191 5.711a38.87 38.87 0 00-37.996 6.446 2 2 0 002.533 3.095 34.884 34.884 0 0132.53-6.315l-6.148 6.763a26.726 26.726 0 00-21.494 5.881 2 2 0 102.557 3.076A23.017 23.017 0 0132 26c.3 0 .598.027.898.04L10.52 50.653a1.997 1.997 0 00.133 2.825 1.998 1.998 0 002.826-.133l11.962-13.159a10.933 10.933 0 0113.767.524 2 2 0 002.629-3.016A14.979 14.979 0 0032 34c-.325 0-.647.018-.969.039l6.649-7.314a23.002 23.002 0 019.01 4.586 2.001 2.001 0 003.28-1.72 2.002 2.002 0 00-.724-1.356 26.98 26.98 0 00-8.589-4.785l5.755-6.33a34.924 34.924 0 017.722 4.786 1.999 1.999 0 002.533-3.095z" />
    </svg>
  );
}
