//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: world.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function WorldIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--world', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M32 4C16.536 4 4 16.536 4 32s12.536 28 28 28 28-12.536 28-28C59.983 16.543 47.457 4.017 32 4zm6.462 10.77V9.21a23.767 23.767 0 0112.832 9.066l-3.586 3.586c-.404.404-.63.951-.631 1.523v4.307h-2.755l-1.172-3.516a4.303 4.303 0 00-4.087-2.945h-4.91v-1.262l3.678-3.677c.403-.404.63-.952.63-1.523zm-21.54-1.032v7.881l-6.828 1.366a23.81 23.81 0 016.829-9.247zM32 55.692a23.67 23.67 0 01-23.285-28.04l.016-.002 9.038-1.807a4.32 4.32 0 003.462-4.224V10.908A23.537 23.537 0 0134.154 8.41v5.467l-3.046 3.046a4.279 4.279 0 00-1.262 3.046v1.262a4.312 4.312 0 004.308 4.307h4.91l1.662 4.99A2.154 2.154 0 0042.769 32h6.462c1.19 0 2.154-.964 2.154-2.154v-5.569l2.146-2.146A23.678 23.678 0 0132 55.692zm2.154-19.384H21.23a4.312 4.312 0 00-4.308 4.307v2.154a4.312 4.312 0 004.308 4.308h3.416l3.045 3.046a4.278 4.278 0 003.046 1.262h3.416a4.312 4.312 0 004.307-4.308v-6.462a4.312 4.312 0 00-4.307-4.307zm0 10.769h-3.416l-3.046-3.046a4.279 4.279 0 00-3.045-1.262H21.23v-2.154h12.923v6.462z"
        clipRule="evenodd"
      />
    </svg>
  );
}
