//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: world.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function WorldIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--world', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path d="M32 6a26 26 0 0126 26c0 14.36-11.64 26-26 26S6 46.36 6 32 17.64 6 32 6zm0 4a21.84 21.84 0 00-10 2.41v9.95a4 4 0 01-3.22 3.96L10.38 28l-.1.566A21.53 21.53 0 0010 32c0 12.15 9.85 22 22 22s22-9.85 22-22a21.761 21.761 0 00-2-9.17l-2 2V30a2 2 0 01-2 2h-6a2 2 0 01-1.9-1.37L38.56 26H34a4 4 0 01-4-4v-1.17A4 4 0 0131.17 18L34 15.17v-5.08c-.66-.09-1.33-.09-2-.09zm2 26a4 4 0 014 4v6a4 4 0 01-4 4h-3.17A4 4 0 0128 48.83L25.17 46H22a4 4 0 01-4-4v-2a4 4 0 014-4zm0 4H22v2h3.17A4 4 0 0128 43.17L30.83 46H34v-6zm16-3v5h-8v-5h8zM38 10.84V16a2 2 0 01-.59 1.41L34 20.83V22h4.56a4 4 0 013.79 2.73L43.44 28H46v-4a2 2 0 01.59-1.41l3.33-3.33A22.07 22.07 0 0038 10.84zM18 15a22.19 22.19 0 00-6.34 8.59L18 22.32z" />
    </svg>
  );
}
