//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: youtube.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function YoutubeIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--youtube', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M59.142 20.696s-.644-3.913-2.146-5.653c-2.145-2.173-4.506-2.173-5.578-2.39C43.694 12 31.893 12 31.893 12s-11.801 0-19.525.652c-1.073.218-3.433.218-5.579 2.392-1.716 1.739-2.145 5.652-2.145 5.652S4 25.26 4 29.826v4.348c0 4.565.644 9.13.644 9.13s.643 3.913 2.145 5.652c2.146 2.174 4.935 2.174 6.223 2.392 4.505.435 19.095.652 19.095.652s11.801 0 19.525-.652c1.073-.218 3.433-.218 5.579-2.392 1.716-1.739 2.145-5.652 2.145-5.652S60 38.74 60 34.174v-4.348c-.215-4.565-.858-9.13-.858-9.13zM26.1 39.39V23.52l15.019 8.044-15.02 7.826z"
        clipRule="evenodd"
      />
    </svg>
  );
}
