//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by scripts/generate-icons.js.
//
// Generated from: zoom.svg
//

import React from 'react';
import cs from 'classnames';

interface Props {
  style?: React.CSSProperties;
  className?: string;
  title?: string;
}

export function ZoomIcon(props: Props) {
  return (
    <svg
      className={cs('Icon', 'Icon--zoom', props.className)}
      style={props.style}
      aria-hidden={props.title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 64 64"
    >
      {props.title && <title>{props.title}</title>}
      <path
        fillRule="evenodd"
        d="M58.606 55.543L47.773 44.71a2.153 2.153 0 00-.658-.446c8.248-9.776 7.325-24.316-2.094-32.97-9.419-8.655-23.985-8.347-33.03.698-9.044 9.044-9.352 23.61-.698 33.03 8.654 9.419 23.195 10.342 32.97 2.093.107.245.258.469.446.658l10.833 10.834a2.167 2.167 0 003.064-3.064zm-29.698-7.135c-10.77 0-19.5-8.73-19.5-19.5s8.73-19.5 19.5-19.5 19.5 8.73 19.5 19.5c-.013 10.765-8.736 19.488-19.5 19.5z"
        clipRule="evenodd"
      />
      <path fillRule="evenodd" d="M29 18a2 2 0 012 2v18a2 2 0 11-4 0V20a2 2 0 012-2z" clipRule="evenodd" />
      <path fillRule="evenodd" d="M18 29a2 2 0 012-2h18a2 2 0 010 4H20a2 2 0 01-2-2z" clipRule="evenodd" />
    </svg>
  );
}
