---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: 987227049932.dkr.ecr.eu-west-1.amazonaws.com/teliaoss/concourse-awscli
    tag: 'latest'

inputs:
  - name: styleguide

outputs:
  - name: styleguide

params:
  source:
  destination:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  AWS_SESSION_TOKEN:
  AWS_DEFAULT_REGION: eu-west-1

run:
  path: sh
  args:
    - styleguide/ci/tasks/aws-s3-sync/task.sh
