config:
  webhook: &webhook-config
    check_every: 24h
    webhook_token: KC8SFDCTLb
  failure: &slack-failure
    put: slack-alert
    params:
      channel: '#styleguide-deploy'
      icon_emoji: ':x:'
      text: |
        *Styleguide*: Build failed
        https://concourse.common-services.telia.io/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME

  success: &slack-success
    put: slack-alert
    params:
      channel: '#styleguide-deploy'
      icon_emoji: ':heavy_check_mark:'
      text: |
        *Styleguide*: Latest version is live at https://styleguide.channelapi.telia.no/#/

# TODO Add aws bucket config here

resource_types:
  - name: slack-notification
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource
      tag: latest

  - name: pull-request
    type: docker-image
    source:
      repository: teliaoss/github-pr-resource
      tag: latest

  - name: node_modules-cache-resource-type
    type: docker-image
    source:
      repository: ymedlop/npm-cache-resource
      tag: "8"

  - name: s3-resource
    type: docker-image
    source:
      repository: 18fgsa/s3-resource-simple

resources:
  - name: styleguide-pr
    type: pull-request
    check_every: 24h
    webhook_token: KC8SFDCTLb
    source:
      repository: TeliaSoneraNorge/styleguide
      ignore_paths: [ ci ]
      access_token: ((teliasoneranorge-access-token))

  - name: styleguide
    type: git
    source:
      uri: git@github.com:TeliaSoneraNorge/styleguide.git
      branch: feature/concourse-pipeline
      private_key: ((styleguide-deploy-key))
      ignore_paths: [ package.json, component-lib/package.json ]

  - name: node-tasks
    type: git
    source:
        uri: git@github.com:mhd999/go-tasks.git
        branch: master
        private_key: ((channel-api-functions-deploy-key))

  - name: slack-alert
    type: slack-notification
    source:
      url: https://hooks.slack.com/services/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

  - name: node_modules
    type: node_modules-cache-resource-type
    source: &source-config
      uri: git@github.com:TeliaSoneraNorge/styleguide.git
      branch: feature/concourse-pipeline
      private_key: ((channel-api-functions-deploy-key))
      paths:
        - package.json

  - name: node_modules-component-lib
    type: node_modules-cache-resource-type
    source:
      project-path: component-lib
      <<: *source-config

groups:
  - name: Master
    jobs:
    - cache
    - build-and-upload
    - version-patch-and-publish-npm

  - name: PR
    jobs:
    - lint-pr

jobs:
  - name: cache
    serial: true
    plan:
    - aggregate:
      - get: styleguide
        trigger: true
        passed:
      - get: node_modules
        passed:
      - get: node_modules-component-lib
        passed:

#   - name: lint
#     serial: true
#     serial_groups: [lint-job]
#     public: true
#     plan:
#     - aggregate:
#       - get: styleguide
#         trigger: true
#         version: every
#         passed:
#       - get: node-tasks
#         params:
#           submodules:
#           - node
    # - task: run-lint
    #   file: node-tasks/node/8.10.0.yml
    #   input_mapping:
    #     source: styleguide
    #     dependencies: node_modules
    #   params:
    #     command: lint
    #     directory: /
    #   on_failure: *slack-failure

  - name: lint-pr
    serial: true
    public: true
    plan:
    - aggregate:
      - get: styleguide-pr
        trigger: true
        version: every
        passed:
      - get: node_modules
        passed:
      - get: node-tasks
        params:
          submodules:
          - node

    - task: run-lint
      file: node-tasks/node/8.10.0.yml
      input_mapping:
        source: styleguide-pr
        dependencies: node_modules
      params:
        command: lint
        directory: /
      on_failure: *slack-failure

  - name: build-and-upload
    serial: true
    serial_groups: [lint-job, build-and-upload-job]
    plan:
    - aggregate:
      - get: styleguide
        trigger: true
        passed: [ cache ]
      - get: node_modules
        passed: [ cache ]
      - get: node_modules-component-lib
        passed: [ cache ]
    - task: build
      file: styleguide/ci/tasks/build/build-website.yml
      input_mapping:
        styleguide: styleguide
        node_modules: node_modules
        node_modules-component-lib: node_modules-component-lib
      on_failure: *slack-failure

    - task: release-to-s3
      file: styleguide/ci/tasks/aws-s3-sync/task.yml
      input_mapping:
        styleguide: styleguide
      params:
        source: dist/
        destination: s3://styleguide.channelapi.telia.no
        AWS_DEFAULT_REGION: eu-west-1
        AWS_ACCESS_KEY_ID: ((telia-no-channelapi-prod-access-key))
        AWS_SECRET_ACCESS_KEY: ((telia-no-channelapi-prod-secret-key))
        AWS_SESSION_TOKEN: ((telia-no-channelapi-prod-session-token))
      on_failure: *slack-failure
      on_success: *slack-success

  - name: version-patch-and-publish-npm
    serial: true
    serial_groups: [update-version]
    plan:
    - aggregate:
      - get: styleguide
        trigger: false
        passed: [ build-and-upload ]
      - get: node_modules-component-lib
        passed: [ build-and-upload ]
    - task: build-component-lib
      file: styleguide/ci/tasks/build/build-component-lib.yml
      input_mapping:
        styleguide: styleguide
        node_modules: node_modules-component-lib
    - task: update-and-publish-version
      file: styleguide/ci/tasks/update-publish-version/task.yml
      input_mapping:
        styleguide: styleguide
      params:
        update_type: patch
    - put: styleguide
      params:
        repository: styleguide
        rebase: true





