---
platform: linux

image_resource:
  type: docker-image
  source: {repository: node, tag: "8-alpine" }

inputs:
  - name: styleguide

run:
  path: sh
  args:
  - -exc
  - |
    cd styleguide/component-lib && npm run publish
