name: Build on PR
on:
  pull_request:
    branches:
      - 'master'
      - '!dependabot/**'
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  build-and-deploy-website:
    strategy:
      matrix:
        node-version: ['16.x']
    name: Build check
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # Runs a set of commands using the runners shell
      - name: Running versions ${{ matrix.node-version }}
        run: |
          echo "Node Version: $(node --version)"
          echo "NPM Version: $(npm --version)"
          aws --version

      - name: Install
        run: |
          npm ci

      - name: Build
        run: |
          npm run build:css
          npm run build:icons
          npm run build-storybook
          # Important: the icon zip will be placed inside dist-storybook, so it must
          #            be run _after_ build-storybook.
          npm run build:icons-zip
          npm run build:zip
          mv assets/* dist-storybook
          npm run build:ts-types

      - name: Lint
        run: |
          npm run lint
